### ISSUE TITLE
Mono

### ISSUE THREAD

**Issue by haf** [Topshelf/Topshelf#107]
Make it compile and run services on mono.

My plan of attack:

 * Conditional Compile the `Topshelf/Runtime/Windows`
 * Similarly, but opposite, `Topshelf/Runtime/Linux`
 * Enable the service to print an **upstart** script when given such a command, on mono.
 * Enable the service when `service.exe install` to install an upstart script
 * `ServiceRecoveryHostConfigurator` is directly depedent on Windows-only namespace. Create a configurator for Unix, named the same -- it would be mutually exclusive, but could have a very similar API.

**Comment by mfloryan** [comment]
Did you guys make any progress on this? The conditional compilation of the Windows stuff would be a good first step.

`Topshelf v3.1.135.0, .NET Framework v4.0.30319.17020
Default Error: 0 : Unable to get parent process (ignored) System.EntryPointNotFoundException: CreateToolhelp32Snapshot
  at (wrapper managed-to-native) Topshelf.Runtime.Windows.Kernel32:CreateToolhelp32Snapshot (uint,uint)
  at Topshelf.Runtime.Windows.WindowsHostEnvironment.GetParent (System.Diagnostics.Process child) [0x00000] in <filename unknown>:0`

**Comment by haf** [comment]
I'm usually writing apps for linux only now, and they can be started in the foreground.

**Comment by mfloryan** [comment]
Indeed they can. We're currently writing some services that need to run on both Windows and Linux. I'll see if there are some simple tweaks to be done.

**Comment by TravisTheTechie** [comment]
I believe this will be address via using [`dotnet`](https://github.com/dotnet/cli) in the future. Closing in favor of that effort when `dotnet` finally stabilizes.
