### ISSUE TITLE
Service can hung in case of unhanled exception

### ISSUE THREAD

**Issue by IlyaGrebnov** [Topshelf/Topshelf#113]
Any unhanded exceptions can cause service to hung in "stopping" action, because thread is blocked from termination by infinity loop in CatchUnhandledException callback, so any Thread.Join or Task.WaitAll will cause a deadlock.

**Comment by jods4** [comment]
The repro is easy:

1. Create a background thread, crash it with an exception. This thread goes into `CatchUnhandledException`, which for some reason attempts to rename it and then spin in an infinite sleep loop.
2. Previous point will also trigger a shutdown of your service. Inside `Stop`, do a join `worker.Join()` on the background thread, something pretty natural to do.
3. Application is deadlocked. Topshelf is spin-looping the crashed thread and main thread waits for the thread to complete.

I don't know what this infinite loop is there for, but it has nasty, unexpected side-effects.
