### ISSUE TITLE
Win32Exception starting host with TopShelf 3.0.105

### ISSUE THREAD

**Issue by flipdoubt** [Topshelf/Topshelf#117]
Updated to TopShelf 3.0.105 via Nuget after updating all solutions to .NET 4.0. I did not change any of my code, so I start the host as follows:

```
private static void _TryRun(string fileName, string pluginDirectory, string serviceName)
{
    try
    {
        HostFactory.Run(x =>
                            {
                                x.Service<IScheduledCommandRunner>(configurator =>
                                                                        {
                                                                            configurator.ConstructUsing(
                                                                                name =>
                                                                                _TryRunBootstrapper(fileName,
                                                                                                    pluginDirectory,
                                                                                                    serviceName));
                                                                            configurator.WhenStarted(
                                                                                runner => runner.StartRunning());
                                                                            configurator.WhenStopped(
                                                                                runner => runner.StopRunning());
                                                                        });

                                x.SetServiceName(serviceName);
                                var displayName = GetConfigString("serviceDisplayName",
                                                                    "CEO Maintenance Service");
                                x.SetDisplayName(displayName);
                                var description =
                                    GetConfigString("serviceDescription",
                                                    "Runs scheduled tasks to maintain the Image Executive CEO document server.");
                                x.SetDescription(description);
                            }
            );
    }
    catch (Exception e)
    {
        Console.WriteLine(e);
        throw;
    }
}
```

I try installing the service and auto-starting as NetworkService with the following:
CeoMaintenanceService.exe install --autostart --networkservice start

This produces the following output and error:
Configuration Result:
[Success] Name CeoMaintenanceService
[Success] DisplayName CEO Maintenance Service
[Success] Description Runs scheduled tasks to maintain the Image Executive CEO document server.
[Success] ServiceName CeoMaintenanceService
Topshelf v3.0.105.0, .NET Framework v4.0.30319.18010

Running a transacted installation.

Beginning the Install phase of the installation.
Installing CEO Maintenance Service service
Installing service CeoMaintenanceService...
Service CeoMaintenanceService has been successfully installed.
Creating EventLog source CeoMaintenanceService in log Application...

The Install phase completed successfully, and the Commit phase is beginning.

The Commit phase completed successfully.

The transacted install has completed.
Topshelf.Hosts.StartHost Error: 0 : The service failed to start., System.Invalid
OperationException: Cannot start service CeoMaintenanceService on computer '.'.
---> System.ComponentModel.Win32Exception: The service did not respond to the st
art or control request in a timely fashion
   --- End of inner exception stack trace ---
   at System.ServiceProcess.ServiceController.Start(String[] args)
   at Topshelf.Runtime.Windows.WindowsHostEnvironment.StartService(String servic
eName)
   at Topshelf.Hosts.StartHost.Run()

d:\CeoServer\Utilities\CeoMaintenanceService>

**Comment by Markeli** [comment]
@jonathankarsh thanks a lot!

**Comment by MalikOsama** [comment]
@jonathankarsh thank u so much
