### ISSUE TITLE
Command Line unknown ARGS

### ISSUE THREAD

**Issue by scobrown** [Topshelf/Topshelf#119]
When running from ReSharper in an integration test (nUnit).

[Failure] Command Line An unknown command-line option was found: ARGUMENT: "a774f2fd-f3a2-
4b4f-8e42-43ee5c5a5184"

It appears that the unit test framework is passing a random guid.  If I look at the current process there are no args, so I don't understand where this is coming from.  I'll try and debug but thought I would check if you know the cause offhand.

**Comment by Davidsual** [comment]
Thank you for your answer scobrown.

I am trying to run TopShelf in a class library for unit test purpose... but I found out that topshelf host is running just in a console application project.

**Comment by nullpainter** [comment]
This isn't a particularly great solution as it prevents regular command-line parsing (for example, service installation).
