### ISSUE TITLE
Default tracing does not work

### ISSUE THREAD

**Issue by chaliy** [Topshelf/Topshelf#131]
Release binaries (installed from nuget) compiled without TRACE defined. This actually produce:

    // Topshelf.Logging.TraceLogWriter
    private void LogInternal(LoggingLevel level, object obj, Exception exception)
    {
    	if (obj != null)
    	{
    		obj.ToString();
    	}
    }

... default tracing never trace at all. Can you please add TRACE symbol to your build?

**Comment by drusellers** [comment]
@chaliy I think this is fixed now - https://github.com/Topshelf/Topshelf/blob/develop/src/Topshelf/Logging/TraceLogWriter.cs#L560 

I'm going to go ahead and close the issue. Feel free to reopen it.
