### ISSUE TITLE
Make Topshelf compatible with the WIX installer

### ISSUE THREAD

**Issue by EvgeniyGrishnov** [Topshelf/Topshelf#145]
Top shelf is convinient for a local debug as console app and test deploy as window service but when you'll try to create service as .msi product you'll have problems.
Manual files copying with typing 'Myservice.exe install' in console is not good product deployment solution for the end user.

Problem described here, but solution does not work with the latest topshelf version:
http://perezgb.com/2011/10/19/installing-a-topshelf-service-using-wix

**Comment by vir** [comment]
Wix can be used to install topshelf service. You just have to make sure that service name in wix file _exactly_ match service name in call to topshelf's SetServiceName().

**Comment by yusukemasuda** [comment]
That's enough if we just do installation of windows service.
However I want to configure the windows service more, such as recovery behavior, permission to control (start, stop etc.), and service dependency.
Wix toolset has a lot of options to configure windows service.
We can take a option to give up TopShelf, but I would respect the TopShelf features, if it is possible. That’s how much I love the topshelf.
I believe Wix and TopShelf combination is the best.
I think that many people will agree with this.
I hope it to enable to install with MSI in production, use the original topshelf feature in development.

Please see the wix windows service options:
https://wixtoolset.org/documentation/manual/v3/xsd/wix/serviceinstall.html
https://wixtoolset.org/documentation/manual/v3/xsd/wix/serviceconfig.html
https://wixtoolset.org/documentation/manual/v3/xsd/wix/permissionex.html
https://wixtoolset.org/documentation/manual/v3/xsd/wix/servicedependency.html

Sincerely,
