### ISSUE TITLE
Service args

### ISSUE THREAD

**Issue by phatboyg** [Topshelf/Topshelf#146]
Come up with a better way to give arguments to services.

**Comment by crosswins** [comment]
This would also be helpful for passing args through to the WhenCustomCommandReceived() event which I haven't been able to figure out yet

**Comment by IanYates** [comment]
:+1:

**Comment by gwicksted** [comment]
Suggestion: Unix style where everything after the " - " is passed verbatim during service start:
```bash
$ myapp.exe -install - --config="myconfig.config"
```

The ` --config="myconfig.config"` would be appended to the end of the start args.

Allow the API to set this string as well as the CLI.  Store the string following the dash in `HostSettings` then append it to arguments in CreateHostInstaller.  It's easy to filter out prior to parsing normal args and you don't have to worry about escaping quotes etc.
