### ISSUE TITLE
Allow custom commandline switches added using AddCommandLineSwitch() to appear in the HELP list

### ISSUE THREAD

**Issue by williamwsmith** [Topshelf/Topshelf#149]
This is a wish list item.  However it would improve the user experience.  Allow for a help description to be added as well.

**Comment by drusellers** [comment]
@phatboyg can we easily move from the text file to something generated?

**Comment by ChrisRichner** [comment]
+1

**Comment by TravisTheTechie** [comment]
Happy to review a PR on this, but don't think there's enough interest for me to do it.
