### ISSUE TITLE
can not run rake global_version

### ISSUE THREAD

**Issue by mpseidel** [Topshelf/Topshelf#167]
Hi, 
I am probably doing something wrong here. I tried to follow your contrib instructions but could not run the rake global_version task. I got the output below.
Running rake compile did generate the SolutionVersion.cs.

What am I missing?

*\* Invoke global_version (first_time)
*\* Execute global_version
rake aborted!
uninitialized constant FORMAL_VERSION
C:/ruby200/lib/ruby/2.0.0/rake/ext/module.rb:36:in `const_missing'
C:/xx/GitHub/Topshelf/rakefile.rb:34:in`block in <top (required)>'
C:/ruby200/lib/ruby/gems/2.0.0/gems/albacore-0.3.5/lib/albacore/support/createtask.rb:18:in `call'
C:/ruby200/lib/ruby/gems/2.0.0/gems/albacore-0.3.5/lib/albacore/support/createtask.rb:18:in`block in assemblyinfo'
C:/ruby200/lib/ruby/2.0.0/rake/task.rb:228:in `call'
C:/ruby200/lib/ruby/2.0.0/rake/task.rb:228:in`block in execute'
C:/ruby200/lib/ruby/2.0.0/rake/task.rb:223:in `each'
C:/ruby200/lib/ruby/2.0.0/rake/task.rb:223:in`execute'
C:/ruby200/lib/ruby/2.0.0/rake/task.rb:166:in `block in invoke_with_call_chain'
C:/ruby200/lib/ruby/2.0.0/monitor.rb:211:in`mon_synchronize'
C:/ruby200/lib/ruby/2.0.0/rake/task.rb:159:in `invoke_with_call_chain'
C:/ruby200/lib/ruby/2.0.0/rake/task.rb:152:in`invoke'
C:/ruby200/lib/ruby/2.0.0/rake/application.rb:143:in `invoke_task'
C:/ruby200/lib/ruby/2.0.0/rake/application.rb:101:in`block (2 levels) in top_level'
C:/ruby200/lib/ruby/2.0.0/rake/application.rb:101:in `each'
C:/ruby200/lib/ruby/2.0.0/rake/application.rb:101:in`block in top_level'
C:/ruby200/lib/ruby/2.0.0/rake/application.rb:110:in `run_with_threads'
C:/ruby200/lib/ruby/2.0.0/rake/application.rb:95:in`top_level'
C:/ruby200/lib/ruby/2.0.0/rake/application.rb:73:in `block in run'
C:/ruby200/lib/ruby/2.0.0/rake/application.rb:160:in`standard_exception_handling'
C:/ruby200/lib/ruby/2.0.0/rake/application.rb:70:in `run'
C:/ruby200/bin/rake:37:in`<main>'
Tasks: TOP => global_version

**Comment by mikesigs** [comment]
I just hit this issue too. Simply running `rake` seems to work. No need to run `rake global_version`. Recommend just updating the README.

**Comment by TravisTheTechie** [comment]
Build is using fake now.
