### ISSUE TITLE
Silent exit with invalid service and "unstarted" NLog.

### ISSUE THREAD

**Issue by pettys** [Topshelf/Topshelf#171]
We were pulling our hair out over this for quite a while before we found it was just a space in our service name. The following code produces this behavior:

```C#
public class EmptyService {
	public EmptyService() {
		NLog.LogManager.GetCurrentClassLogger().Info("Hello, World!");
	}
}

public class Program {

	static void Main() {
		HostFactory.Run(x => {
			x.UseNLog();
			x.Service<EmptyService>((ServiceConfigurator<EmptyService> s) => {
				s.ConstructUsing(() => new EmptyService());
				s.WhenStarted(svc => { });
				s.WhenStopped(svc => { });
			});

			x.StartAutomatically();
			x.RunAsLocalSystem();

			x.SetServiceName("Bad Name");
		});
	}

}
```
Running this from the command line gives the following experience:
```Shell
C:\code\EmptyService\bin\Debug>EmptyService.exe

C:\code\EmptyService\bin\Debug>EmptyService.exe -help

C:\code\EmptyService\bin\Debug>EmptyService.exe install

C:\code\EmptyService\bin\Debug>
```

**Problem:** The program exits silently regardless of how it's run. No output, no feedback, and exit code is 0.

(NLog is correctly configured to log to console. The configuration is pasted below for competeness.)

**Things that cause something better to happen:**

* If `x.UserNLog();` is commented out then we receive a great error via the console.
* If `Bad Name` is changed to `BadName` then the service starts successfully and writes info to the console via NLog.
* *Interesting:* If we write to NLog *before* calling `HostFactory.Run` then we get a little bit of help, which is way better than nothing:
```
2014-03-28 11:14:18.7233|INFO|ConsoleEngineRunner.Program|Hello, World!
2014-03-28 11:14:18.7943|ERROR|Topshelf.HostFactory|An exception occurred creating the host
2014-03-28 11:14:18.7943|ERROR|Topshelf.HostFactory|The service terminated abnormally
```

Hopefully there's any easy fix for making sure the valuable diagnostic information that's being generated gets provided to the user even in the case that NLog is being used but hasn't been written to yet.

For reference, here's my nlog config:
```XML
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<configSections>
		<section name="nlog" type="NLog.Config.ConfigSectionHandler, NLog" />
	</configSections>
	<nlog autoReload="true" xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
		<targets async="true">
			<target name="console" xsi:type="Console" />
		</targets>
		<rules>
			<logger name="*" minlevel="Debug" writeTo="console" />
		</rules>
	</nlog>
</configuration>
```

**Comment by thedillonb** [comment]
I just stumbled across this as well. 

Here's what mine looks like with NLog enabled:

![image](https://cloud.githubusercontent.com/assets/1644068/5657229/3ffa90c2-96b9-11e4-9a1c-31dfdd34672e.png)


vs when it's disabled:

![image](https://cloud.githubusercontent.com/assets/1644068/5657232/54baa07e-96b9-11e4-93b9-cdc09de852ba.png)


I know there's an obvious error with a command line argument. However, when NLog is used it is completely hidden from the user.

**Comment by thedillonb** [comment]
Ah hah, so I just fell into the same trap I think @solyutor did. It looks like my NLog Console target didn't have the ${exception} renderer in the layout. So I only got the message. The rest of the exception contains the log messages I saw when I disabled NLog.

@solyutor, try setting layout="${exception}" for your console. Run your app again. You should see what you want. If so, I think you can close this bad boy.

**Comment by drusellers** [comment]
@pettys can you confirm the `layout="${exception}"`

**Comment by pettys** [comment]
@drusellers I think the `layout="${exception}"` takes this issue in a slightly different direction. My main stumbling block about a year ago was the completely silent fail that only occurred using NLog, regardless of how it was configured. I feel good assuming solyutor's commit 4406dcf fixed this issue. 

I'm not exactly sure what to make of thedillonb's comments -- I don't see in this thread that solyutor was having any issue, both of thedillonb's test cases were **not** a completely silent fail, and the root of that was to better configure NLog. I'm pretty sure adding `layout="${exception}"` **before** solyutor's 4406dcf still would have resulted in a completely silent fail in my test case.

I'll hit the Close button here, because I do think the issue I reported was fixed last July.

**Comment by solyutor** [comment]
Sorry for being late. 
@thedillonb `layout="${exception}"` was not the case. I got silent crash without any message. I tested the issue combining sync/async targets and changes to Topshelf code. It works as expected with async targets after 4406dcff4e9cf3f103bdf105f040b48958b10c9c.

**Comment by jackjwilliams** [comment]
I know this is old, but Topshelf is swallowing my exception and I can't see WHY it's crashing! How do I stop this? I've been trying to fix my service for over a day now.

**Comment by solyutor** [comment]
@jackjwilliams,  try setting up any logger with appropriate level of logging, it should log the exception. To make it simpler, set up the logger to work in synchronous manner.

**Comment by jeffward01** [comment]
I was having a similar error.  I would try to install a service from command line `serviceName.exe install,` and I was greeted with the exception `Service abnormally terminated`.  I discovered the reason behind the problem was my NLog.config file was wrong (minor syntax errors).  Once i fixed the NLog file, it was all good :)
