### ISSUE TITLE
The service did not respond to the start or control request in a timely fashion

### ISSUE THREAD

**Issue by kimschurmann** [Topshelf/Topshelf#176]
I am trying to create a topshelf service that depends on input from the commandline. But when using the configureration of the commandline argument the service can't "start in a timely fashion".

My configuration of the service:

If I remove the configuration of the language setting and hardcode the value, the service starts just fine... Any ideas?

	HostFactory.Run(conf =>
	{
        CultureInfo language = null; 

		conf.AddCommandLineDefinition("language", lang => { language = new CultureInfo(lang); });
		conf.ApplyCommandLine();
		var countryCode = new RegionInfo(language.Name).TwoLetterISORegionName.ToUpper();
		conf.SetDescription("{0} Order Broker".FormatWith(countryCode));
		conf.SetDisplayName("{0} Order Broker".FormatWith(countryCode));
		conf.SetServiceName("{0}OrderBroker".FormatWith(countryCode));
		
		conf.StartAutomatically();
		conf.RunAsLocalSystem();
		conf.Service<IOrderService>(svc =>
		{
		svc.ConstructUsing(name => Creator.Current.Create<IOrderService>());
		svc.WhenStarted(service => service.Start(language));
		svc.WhenStopped(service => service.Stop());
		});
	});

Stacktrace:

    System.ComponentModel.Win32Exception: The service did not respond to the start
    or control request in a timely fashion --- End of inner exception stack trace ---
    at System.ServiceProcess.ServiceController.Start(String[] args)
    at System.ServiceProcess.ServiceController.Start()
    at Topshelf.Runtime.Windows.WindowsHostEnvironment.StartService(String serviceName)
    at Topshelf.Hosts.StartHost.Run()

Thanks in advance...

Also on stackexchange:
https://stackoverflow.com/questions/23027443/topshelf-the-service-did-not-respond-to-the-start-or-control-request-in-a-time

**Comment by drusellers** [comment]
When service started is called you can ask for more time.

```
 x.WhenStarted((svc, hostControl) =>
{
    hostControl.RequestAdditionalTime();
});
```

**Comment by TravisTheTechie** [comment]
Nearly 2 years from opening, closing this issue. Feel free to reopen it if there's more info to add.

**Comment by JGCreator** [comment]
Is `.RequestAdditionalTime()` the only solution for this?

I'm getting the same behavior for a slightly different problem domain.

I want to implement a strategy pattern for my service to run as a service (both as a console service and an installed service) OR run as a one-time execution. The CMD argument driving the strategy decision is looked for before creating the Topshelf host. If any of the Topshelf commands are given, the decision is to use topshelf.

```
internal class Program
{
	public static void Main(string[] args)
	{
		string buildMode;
        if (args != null && args.Length > 0 && !TopShelfParameters.List.Contains(args[0]))
        {
            Log.Info($"First param not TopShelf cmd: {args[0]}");
            Log.Info("Setting arg[0] as buildMode.");
            buildMode = args[0];
        }
        else
        {
            Log.Info("Getting buildMode from AppSettings.");
            buildMode = ConfigurationManager.AppSettings["BuildMode"];
        }
		
		...
		
		var factory = new ExecutionStrategyFactory(appInfoBag, logFactory);
        var strategy = factory.GetStrategy();
		strategy.Execute();
	} // Main

} // Program

public static class TopShelfParameters
{
  public static System.Collections.Generic.List<string> List { get; } = new System.Collections.Generic.List<string>()
  {
    "run",
    "help",
    "install",
    "start",
    "stop",
    "uninstall"
  };
}

public class ExecutionStrategyFactory : OneTimeOrTopshelfStrategyFactory
{
    private readonly ILog _log;

    public ExecutionStrategyFactory(ApplicationInfoBag infoBag, ILogFactory logFactory)
        : base(infoBag)
    {
        _log = logFactory.GetLogger();

        try
        {
			...
		
            _oneTimeTimer = new OneTimeImmediatlyElapsingTimer();
            _standardTimer = new StandardTimerProxy(intervalMilliseconds);

            OneTimeService = () => new Service(..., _oneTimeTimer);
            RepeatingService = () => new Service(..., _standardTimer);
        }
        catch (Exception e)
        {
            _log.Error(e.Message, e);
            throw;
        }
    }

    private readonly ITimerProxy _oneTimeTimer;
    private readonly ITimerProxy _standardTimer;
}

public abstract class OneTimeOrTopshelfStrategyFactory : IExecutionStrategyFactory
{	
	protected Func<IService> OneTimeService { get; set; }
	
	protected Func<IService> RepeatingService { get; set; }
	
	protected OneTimeOrTopshelfStrategyFactory(ApplicationInfoBag infoBag)
	{
		...
	}
	
	public IExecutionStrategy GetStrategy()
	{
		if (this._infoBag.BuildMode == "Localhost")
			return (IExecutionStrategy) new SimpleStartInvocationStrategy(this.OneTimeService());
		return (IExecutionStrategy) new TopShelfExecutionStrategy(this.RepeatingService(), this._infoBag.ApplicationName, this._infoBag.Description, this._infoBag.RunAsUserName, this._infoBag.RunAsPassword);
	}
}

public class TopShelfExecutionStrategy : IExecutionStrategy
{
  private readonly IService _executionComponent;
  private readonly string _applicationName;
  private readonly string _description;
  private readonly string _runAsUserName;
  private readonly string _runAsPassword;

  public TopShelfExecutionStrategy(IService executionComponent, string applicationName, string description, string runAsUserName, string runAsPassword)
  {
    ...
  }

  public void Execute()
  {
    int num = (int) HostFactory.Run((Action<HostConfigurator>) (configurator =>
    {
      configurator.SetServiceName(this._applicationName);
      configurator.SetDisplayName(this._applicationName);
      configurator.SetDescription(this._description);
      configurator.StartAutomaticallyDelayed();
      configurator.RunAs(this._runAsUserName, this._runAsPassword);
      configurator.DependsOnEventLog();
      configurator.Service<IService>((Action<ServiceConfigurator<IService>>) (s =>
      {
        s.ConstructUsing<IService>((Func<IService>) (() => this._executionComponent));
        s.WhenStarted<IService>((Action<IService>) (service => service.Start()));
        s.WhenStopped<IService>((Action<IService>) (service => service.Stop()));
      }));
    }));
  }
}
```
