### ISSUE TITLE
F# API for Topshelf

### ISSUE THREAD

**Issue by haf** [Topshelf/Topshelf#177]
Nice fluent interface, consistent return values from configuration methods.

**Comment by ghuntley** [comment]
Yo @haf what is the status of this issue?

What is https://github.com/haf/Topshelf.FSharp (and the NuGet package available there)

**Comment by haf** [comment]
Well, I created that API that you're linking to. It's what I'm using when I'm writing TopShelf services. It's also a nuget, published to NuGet.org.

You could send it as a PR to this project and let it go through review. In this case I just wanted it out there to get something up.
