### ISSUE TITLE
Topshlef 3.1.107.0 Service not starting only on windows server 2012

### ISSUE THREAD

**Issue by hkollner** [Topshelf/Topshelf#183]
Hi Guys,

I am having a problem where my topshelf service is not starting on Windows server 2012 but starts on all other windows servers.

As soon as I start the windows service I am instantly presented with a 1053 error: Did not respond in a timely fashion. even though it did not try to run for 30 secs but rather 1 second.

Once again note that this same service runs on all other Windows servers except for 2012. My Start() method does not even get fired.

I have not idea where else to look.

I have tried the following:
* Logging (NLog) - No exceptions are thrown
* RequestAdditionalTime() 
* Permissions

After the logging failed I replaced all logging with writing to the windows event log. No errors aside from the error 1053.

Here's an example of my Main constructor.

static void Main()
        {
            try
            {

                HostFactory.Run(x =>
                {
                    x.Service<ApplicationStartup>(s =>
                    {
                        s.ConstructUsing(name => new ApplicationStartup());
                        s.WhenStarted(tc => tc.Start());
                        s.WhenStopped(tc => tc.Stop());
                    });
                    x.RunAsLocalSystem();
                    x.StartManually();
                    x.SetDescription("SERVICE SOLUTION ENGINE");
                    x.SetDisplayName("SERVICE SOLUTION ENGINE");
                    x.SetServiceName("SERVICESOLUTIONENGINE");
                });
            }
            catch (Exception ex)
            {
                Logger.ErrorException("Main Registered an Exception.", ex);
                throw;
            }
        }

Your help is GREATLY appreciated.

**Comment by jackfoxy** [comment]
I have possibly the same issue. Service remains in start pending status forever, but the service is working fine. The annoying thing is I cannot stop the service from the local services console.

OS: Windows Server 2012 R2 DataCenter
TopShelf compiled for Any CPU, NOT Prefer 32-bit
Target .NET Framework 4.6

**Comment by AliShahrivarian** [comment]
I have same issue in windows 7. Service remains in start pending and for stopping it I should use "taskkill".

**Comment by AliShahrivarian** [comment]
The interesting thing is the services running account. I have multiple service which one of doesn't start on any account but local "local system account" and others doesn't start on that but others.
I'm receiving "1053" error and for accounts I'm receiving "access denied".

**Comment by AliShahrivarian** [comment]
After a lot of search finally I found the issue. The problem was in my "start" method. This method have to call a service that doesn't respond in time. so windows service thrown the timeout exception. I've changed method and now I'm calling the service in thread.
now everything going well.

**Comment by jackfoxy** [comment]
@AliShahrivarian can you throw-up a quick line of code for me. I've been coding in F# so long my C# is very rusty. Just the simple C# TopShelf wrapper for my F# ddl is the only C# I've seriously looked at in a long time...thanks!

**Comment by jackfoxy** [comment]
So the "bug" is really in the sample code and documentation. Should show calling in a thread.

**Comment by AliShahrivarian** [comment]
Sorry for my late @jackfoxy .

It is from the topshelf documentation https://topshelf.readthedocs.org/en/latest/configuration/quickstart.html:
```cs
public class Program
{
    public static void Main()
    {
        HostFactory.Run(x =>                                 //1
        {
            x.Service<TownCrier>(s =>                        //2
            {
               s.ConstructUsing(name=> new TownCrier());     //3
               s.WhenStarted(tc => tc.Start());              //4
               s.WhenStopped(tc => tc.Stop());               //5
            });
            x.RunAsLocalSystem();                            //6

            x.SetDescription("Sample Topshelf Host");        //7
            x.SetDisplayName("Stuff");                       //8
            x.SetServiceName("Stuff");                       //9
        });                                                  //10
    }
}
```

The thing you'll got from the line 4 is that the service started and your start method will run after service start but it's not the truth. `s.WhenStarted` is same as "start" button in Windows service and your method will run in windows service start and should finish before timeout and (should or not) return true (I didn't test return matter) for windows service.

Suppose you have this `start` method:
```cs
public bool start(){
    // to do other config which run fast

    while(true){
          // to do something forever
    }
    return true;
}
```
This method doesn't return anything to windows service and work forever. It is matter for win service. because it's waiting for response and when it get nothing it'll throw exception.
I've changed `start` method like this one:
```cs
public bool start(){
    // to do other config which run fast

    var myThread = new Thread(new ThreadStart(foreverWhile));
    myThread.Start();
    return true;
}
public void foreverWhile(){
     while(true){
         // to do something forever
     }
}
```
The thread will work independent and service will start.
Hope this help you.

**Comment by phatboyg** [comment]
And technically you should signal your background thread when Stop is called so that it can exit cleanly.

**Comment by jackfoxy** [comment]
Thanks, all. This worked out well for me. I suggest adding this tip prominently in documentation. I'm sure a lot of installations must run into similar situations, and its easy to overlook threading.

**Comment by dallancarr** [comment]
@phatboyg if you could provide an example of how you would signal the thread on exit.

**Comment by diogoandrei** [comment]
I'm facing a similar problem here, my service works fine if I run on debug or release, but when I try to install and run via cmd the Start() method apparently is not being called.

**Comment by hsbeaumier** [comment]
Thanks Ali Shahrivarian!  Your suggestion saved the day.  Creating the looping process code on a separate thread worked.  It is strange, because I did not have to do this on an older version of Windows using .net 4.7.2, but I had to do this on the latest version of windows using .net version 4.8.0.
