### ISSUE TITLE
Stop delegate is called twice in the ConsoleRunHost after clicking Ctrl+C

### ISSUE THREAD

**Issue by smax48** [Topshelf/Topshelf#186]
Configuration: Topshelf 3.1.3, .Net Framework 3.5 SP1, Windows 8 64bit

Issue:
After clicking Ctrl+C, the Stop() method in my service is called twice in the console mode:
the first time from the ConsoleRunHost.HandleCancelKeyPress()
the second time from the ConsoleRunHost.Run()  (in the finally clause -> StopService()).

Precondition: our application sets processor affinity to a single CPU core.

I think the reason is a race condition related to the handling of the _hasCancelled flag and _exit ManualResetEvent: HandleCancelKeyPress method sets the event first, then updates the _hasCancelled to true. So the StopService() method sometimes can read "false" from _hasCancelled and call the stop delegate again :).

**Comment by David-Brabant** [comment]
I have that behavior with version 3.3.1 (?).

**Comment by easyalgoltd** [comment]
same issue with 3.3.1

**Comment by easyalgoltd** [comment]
The issue is not related to topshelf. The second call of Stop handler is caused by Prometheus.Net MetricServer in my case.
