### ISSUE TITLE
Topshelf logging is not working in Framework 3.5

### ISSUE THREAD

**Issue by smax48** [Topshelf/Topshelf#187]
I installed a Topshelf package from nuGet, package version is 3.1.3.
My application uses .Net Framework 3.5
I tried to setup logging for Topshelf, but with no luck.
When I tested it with Framework 4.5.1, everything worked just fine.

After spending couple of hours, I decided to compare decompiled code for two versions of topshelf.dll - built for framework 3.5 & 4 (using JetBrains dotPeek).
According to this tool, the implementation of TraceLogWriter.LogInternal is a bit different:

1) .NET 4:

```
private void LogInternal(LoggingLevel level, object obj, Exception exception)
{
  string message = obj == null ? "" : obj.ToString();
  if (exception == null)
    this._source.TraceEvent(level.TraceEventType, 0, message);
  else
    this._source.TraceData(level.TraceEventType, 0, (object) message, (object) exception);
}
```
1. .NET 3.5:

```
private void LogInternal(LoggingLevel level, object obj, Exception exception)
{
    if (obj != null)
        obj.ToString();
}
```

I guess this explains what's happening.... :)
The question is - why is it implemented in this way for framework 3.5?..

**Comment by TravisTheTechie** [comment]
.NET Framework v3.5 is unsupported. Closing.
