### ISSUE TITLE
Deployment && Updating services at Service Farm

### ISSUE THREAD

**Issue by dimzon** [Topshelf/Topshelf#191]
I'm developing message-based backend - multiple worker instances runs onto multiple servers, takes tasks from message queue (RabbitMQ), execute them and send results back to service bus.
I'm planning to implement workers as windows services but I have a real problem - how to easy deploy\upgrade them on multiple servers at data-center...

Is it possible to implement some kind of auto-update feature to Topshelf?

**Comment by phatboyg** [comment]
Yeah, look at using Octopus or Puppet or something to deploy your service upgrades. Doing something specifically inside Topshelf is out of scope, since most operations teams have standard ways they deploy code to servers and this would just create another one.
