### ISSUE TITLE
Installing a service using a command line with a password containing special characters

### ISSUE THREAD

**Issue by alekseycs** [Topshelf/Topshelf#195]
It appears that password are not being set properly to the service when it contains special characters. I am trying to install a service using this command

service.exe install -username:DOMAIN\username -password:Pa$$w0rd=

Then when trying to start a service I am getting "Error 1069: The service did not start due to a logon failure." However when going into Services console and setting the password manually it then starts fine. Username is set correctly.

**Comment by derekgreer** [comment]
Was this resolved with a fix or was the comment by TravisTheTechie supposed to be the resolution?

**Comment by phatboyg** [comment]
pretty sure you need to use `-password "Pa$$w0rd="` for it to parse correctly.
