### ISSUE TITLE
Service stuck in 'Stopping' state when HostControl.Stop is called

### ISSUE THREAD

**Issue by gregtayl** [Topshelf/Topshelf#204]
I have a TopShelf (3.1.3) service that hangs in a 'Stopping' state when HostControl.Stop is invoked. 

What is the recommended approach for killing a service if something fatal occurs? I do not wish to simply swallow/log the exception and continue, nor do I want my processing thread to die without killing the service. I would like for the service to die, and ideally for the service recovery actions to be run.

Thoughts?

    HostFactory.Run(o =>
    {
        o.Service<TaskRunner>();
        o.RunAsLocalSystem();
        o.SetServiceName("MyService");
        o.SetDisplayName("MyService");
        o.SetDescription("MyService");
        o.EnableServiceRecovery(r => r.RunProgram(1, "notepad.exe"));
    });

    public class TaskRunner : ServiceControl
    {
        private CancellationTokenSource cancellationTokenSource;
        private Task mainTask;

        public bool Start(HostControl hostControl)
        {
            var cancellationToken = cancellationTokenSource.Token;
            this.mainTask = Task.Factory.StartNew(() =>
                {
                    try
                    {
                        while (!this.cancellationTokenSource.IsCancellationRequested)
                        {
                            // ... service logic ...
                            throw new Exception("oops!");
                        }
                    }
                    catch (Exception)
                    {
                        hostControl.Stop();
                    }
                });
            return true;
        }

        public bool Stop(HostControl control)
        {
            this.cancellationTokenSource.Cancel();
            this.mainTask.Wait();
            return true;
        }
    }

**Comment by phatboyg** [comment]
Return ```false``` or just throw the exception out so that Topshelf will recognize that your service didn't start and handle it appropriately. By catching the exception yourself, Topshelf is unable to detect that your service failed to start. So, let it ```throw```.
