### ISSUE TITLE
A question about Topshelf.Supervise.

### ISSUE THREAD

**Issue by swallowcamel** [Topshelf/Topshelf#205]
hi：
      I want to ask Topshelf. Supervise can use? 
      I run SampleTopshelfSuperviseService.exe get an exception。
###### 

System.Runtime.Serialization.SerializationException: 程序集“Topshelf, Version=3.1.4.0, Culture=neutral, PublicKeyToken=null”中的类型“Topshelf.ServiceExtensions+<>c__DisplayClass1`1”未标记为可序列化。
   在 Topshelf.Supervise.ServiceHandleStub.Create(ServiceBuilderFactory serviceBuilderFactory, HostSettings settings, HostLoggerConfigurator loggerConfigurator)
   在 Topshelf.Supervise.ServiceHandleProxy.CreateServiceHandle(AppDomain appDomain) 位置 e:\开源项目\FoundationFramework\Topshelf\src\Topshelf.Supervise\ServiceHandleProxy.cs:行号 159
   在 Topshelf.Supervise.ServiceHandleProxy.CreateServiceInAppDomain() 位置 e:\开源项目\FoundationFramework\Topshelf\src\Topshelf.Supervise\ServiceHandleProxy.cs:行号 142
   在 Topshelf.Supervise.ServiceHandleProxy..ctor(HostSettings settings, HostControl hostControl, ServiceBuilderFactory serviceBuilderFactory) 位置 e:\开源项目\FoundationFramework\Topshelf\src\Topshelf.Supervise\ServiceHandleProxy.cs:行号 44
   在 Topshelf.Supervise.Scripting.Commands.CreateServiceCommand.Execute(CommandScriptStep task) 位置 e:\开源项目\FoundationFramework\Topshelf\src\Topshelf.Supervise\Scripting\Commands\CreateServiceCommand.cs:行号 44
   在 Topshelf.Supervise.Scripting.CommandScript.ExecuteNext() 位置 e:\开源项目\FoundationFramework\Topshelf\src\Topshelf.Supervise\Scripting\CommandScript.cs:行号 94
# 

Can someone answer me?

**Comment by JamesTryand** [comment]
what was the issue / solution here?

**Comment by phatboyg** [comment]
I don't think Supervise is ready for prime time, I'm not sure how it ever got released (mistake most likely).
