### ISSUE TITLE
Finalizers aren't being called when the service runs as a service

### ISSUE THREAD

**Issue by albertjan** [Topshelf/Topshelf#209]
When I start the service from the commandline I don't have a memory leak problem. But when I start it as a service I do. 

And the leak has to do with unmanaged handles not being cleaned up by finalizers. It's like the garbage collector doesn't do the finalize queue, they are all on there. 

Because we're only seeing it when running it as a service I thought it might have to do with topshelf. Do you have any clue maybe?

**Comment by phatboyg** [comment]
First I've heard of something like this happening, I'm not sure how Topshelf could be involved.

If you find an issue with Topshelf, please feel free to reopen this issue.

**Comment by ianfoster99** [comment]
I'm having the very same issue where unmanaged handles are not being cleaned up by finalizers when running as a service. albertjan. Did you track it down?
