### ISSUE TITLE
Password with a pipe

### ISSUE THREAD

**Issue by buckleyGI** [Topshelf/Topshelf#210]
I guess this was Murphy waiting to pop up or I have to brush up mos dos skills

When there is a pipe symbol the command line complains as this is a special character

fore example:

service.exe install -username:domain\accoount-password:abc|def -servicename:servicename

Is it currently possible to use passwords with a pipe symbol in them?

**Comment by darinkes** [comment]
Does quoting work?
Pipe usually has a special meaning in Consoles/Shells.
(Piping stdout to stdin of a second tool)

```
C:\Windows\System32>echo bla
bla

C:\Windows\System32>echo bla|bla
bla not found

C:\Windows\System32>echo "bla|bla"
"bla|bla"
```

**Comment by drusellers** [comment]
@buckleyGI did the quoting help? That is a CMD type issue more than likely. If I don't hear back in 30 days (4/21/2015) I will close the issue. Thank you. :)
