### ISSUE TITLE
Topshelf should let you control when and whether it watches unhandled exceptions

### ISSUE THREAD

**Issue by gab** [Topshelf/Topshelf#212]
I want to catch those exceptions *before* topshelf to log them to my own log system and produce minidumps. Problem is, since Topshelf calls AppDomain.CurrentDomain.UnhandledException += CatchUnhandledException; as soon as the Run() method is called (cf for instance ConsoleRunHost.cs), the window of opportunity to register for those is very small. I can't do it during my own server start, I'm forced to do it in the server constructor.

- This behavior should be documented somewhere. It's extremely confusing to register for unhandled exceptions and to get nothing because topshelf silently registered for and intercepted the whole thing.
- We need a pair of public functions to register/unregister Topshelf's handling, so we can for instance insert ourselves at the beginning of the event handler list and put back topshelf after us.
- Whether Topshelf register at all for those should be optional, and some kind of control on *when* it does it would be appreciated.

**Comment by gab** [comment]
I should add that I also have issues with the thread Topshelf creates and indefinitely puts to sleep in the Unhandled Exception event handler. It causes my application to hang, whereas I'd prefer it to crash. (Perhaps something wrong with my app's threading model? But I've inherited it and can't revamp it at the moment.) I'm really not sure in what scenarios the "undying thread" behavior of Topshelf is useful.

(Thanks for Topshelf btw, great software otherwise.)

**Comment by gab** [comment]
Also very dubious is that whatever I put into the WhenStopped callback is called by TopShelf when running as service and being notified of an unhandled exception. I expect that callback to handle the regular shutdown procedure, but it's obviously not appropriate to call it when the application is crashing down and can be in a corrupted state.

**Comment by drusellers** [comment]
@gab - Where would be the best place to document this behavior? http://docs.topshelf-project.com/en/latest/ so that you would have found it?

**Comment by gab** [comment]
@drusellers Depends. If you leave the behavior as-is, I don't see an ideal place in your current documentation, you might need a new section about caveats or important things to watch for. Somewhere around here might be appropriate though: http://docs.topshelf-project.com/en/latest/overview/faq.html#whats-the-impact-to-my-service

If you actually make it configurable (and given what I've said above I see the need for at least 3 options), then documenting it here would be perfect http://docs.topshelf-project.com/en/latest/configuration/config_api.html

**Comment by solyutor** [comment]
I also have issues with non-background threads hang indefinitely while topshelf waits for them. 
Is it possible to add something like this to replace default handler implementation?
```
public interface HostConfigurator
{
    void SetExceptionHandler(UnhandledExceptionEventHandler handler);
}
```

**Comment by megakid** [comment]
I would love this also- finding it very annoying to have TopShelf intercepting my UnhandledExceptions without telling me - and doing what?

**Comment by sstorie** [comment]
I took a stab at this and just submitted a PR. Please let me know any feedback you folks have :)

https://github.com/Topshelf/Topshelf/pull/311

**Comment by TravisTheTechie** [comment]
Closing in favor of #311.
