### ISSUE TITLE
System.ServiceProcess.ServiceController.GetServices() throws InvalidOperationException when running as an unprivileged user

### ISSUE THREAD

**Issue by poizan42** [Topshelf/Topshelf#213]
A first chance exception of type 'System.InvalidOperationException' occurred in System.ServiceProcess.dll
	Topshelf.HostFactory Error: 0 : The service terminated abnormally, System.InvalidOperationException: Cannot open Service Control Manager on computer '.'. This operation might require other privileges. ---> System.ComponentModel.Win32Exception: Access is denied
	   --- End of inner exception stack trace ---
	   at System.ServiceProcess.ServiceController.GetDataBaseHandleWithAccess(String machineName, Int32 serviceControlManaqerAccess)
	   at System.ServiceProcess.ServiceController.GetDataBaseHandleWithEnumerateAccess(String machineName)
	   at System.ServiceProcess.ServiceController.GetServicesOfType(String machineName, Int32 serviceType)
	   at System.ServiceProcess.ServiceController.GetServices()
	   at Topshelf.Runtime.Windows.WindowsHostEnvironment.IsServiceInstalled(String serviceName)
	   at Topshelf.Hosts.ConsoleRunHost.Run()
	   at Topshelf.HostFactory.Run(Action`1 configureCallback)

**Comment by poizan42** [comment]
This check exists for the sole purpose of refusing to run if already running as a service - is it really Topshelf's job to do that? As we can see here it's impossible to do always as we might not have the neccessary rights to query the service manager.

**Comment by phatboyg** [comment]
Fair point, this might be a non-critical failure that could allow the service to run as a console application. 

Honestly, many of the early issues reported were because people left the service installed and running while running the console version and the errors reported were because an older version of the code was still running. That's why this check was added.

**Comment by drusellers** [comment]
@poizan42 is this still a blocker for you? If so lets discuss, otherwise in one month (4/21/2015) I will close the issue.

**Comment by poizan42** [comment]
A "blocker"? Well we currently have a workaround where we test whether we have access to list the services and then completely avoid using topshelf if we don't have access.

**Comment by drusellers** [comment]
Ok. I have an Idea I can put around this into a PR



-d

**Comment by drusellers** [comment]
@poizan42 ok, I think this should fix the issue. :)
