### ISSUE TITLE
Multiple Service

### ISSUE THREAD

**Issue by nujmail** [Topshelf/Topshelf#215]
Is there any way for me to delegate service run by specific instance system, its like what biztalk did in Host Intance

**Comment by phatboyg** [comment]
I'm unfamiliar with BizTalk, can you provide an example of what you want to do?

**Comment by drusellers** [comment]
I will close this issue in one month with out further updates. @nujmail let me know if you can help us out by providing a more concrete sample of what you would like to do. Thank you. :)
