### ISSUE TITLE
The namespace 'Internals' could not be found

### ISSUE THREAD

**Issue by win32nipuh** [Topshelf/Topshelf#217]
I am trying to build the Topshelf solution but receive this error:
The namespace 'Internals' could not be found
There are many using Internals.Extensons inside of code but no definition for Internals.

What is wrong?

**Comment by jam13c** [comment]
Not sure if this is the same user, but this issue has also been asked on SO within the last hour http://stackoverflow.com/questions/28695369/topshelf-cannot-build-from-sources

**Comment by win32nipuh** [comment]
yes, its me. I still did not find a solution

**Comment by phatboyg** [comment]
You need to clone the repository using --recursive, as shown in the README.md file.
