### ISSUE TITLE
run topshelf in mono

### ISSUE THREAD

**Issue by Jetsly** [Topshelf/Topshelf#218]
Default Error: 0 : An exception occurred creating the host Topshelf.HostConfigurationException: The service was not properly configured:
[Failure] Command Line An unknown command-line option was found: ARGUMENT: "
[Success] Name  .....
[Success] Description .....
[Success] ServiceName  .....
  at Topshelf.Configurators.ValidateConfigurationResult.CompileResults (IEnumerable`1 results) [0x00000] in <filename unknown>:0
  at Topshelf.HostFactory.New (System.Action`1 configureCallback) [0x00000] in <filename unknown>:0

**Comment by simonbaas** [comment]
Hi,

Try adding NuGet package Topshelf.Linux and call config.UseLinuxIfAvailable(); on the configureCallback when starting the service, i.e.

HostFactory.Run(config => { config.UseLinuxIfAvailable(); <left out some code for brevity> });

//Simon

**Comment by TravisTheTechie** [comment]
I expect we'll be delivering a version that runs on [`dotnet`](https://github.com/dotnet/cli) in the future. See #277.
