### ISSUE TITLE
setting Console.Title in Visual Studio debugger throws IOException

### ISSUE THREAD

**Issue by tohagan** [Topshelf/Topshelf#219]
`ConsoleRunHost.Run()` line 91 sets `Console.Title = _settings.DisplayName;`

This throws an exception when running a top shelf app from within Visual Studio 2013

**Comment by phatboyg** [comment]
Is your project a Console project? This only fails when the service is run as a service, or in an application that doesn't have a Console, such as a Windows Application.

**Comment by tohagan** [comment]
I think it was created using a Windows Service app project template (VS.NET 2013).
Should it have been a Console app instead?

**Comment by phatboyg** [comment]
Yes 

____
Chris Patterson

**Comment by tohagan** [comment]
Ok ... Thanks for this Chris ... I'll close the issue.
