### ISSUE TITLE
ServiceRecovery - RestartComputer - doesn't work

### ISSUE THREAD

**Issue by drusellers** [Topshelf/Topshelf#223]
I am trying to install a service with `RestartComputer` in the Service Recovery options, but I cannot get it to work.

.Net 4.0
Windows Server 2012

I'm trying to use the Sample Service

**Comment by phatboyg** [comment]
A pull request was just merged that may resolve this.

**Comment by TravisTheTechie** [comment]
@drusellers, is this still valid?
