### ISSUE TITLE
#Wishlist Monitor service

### ISSUE THREAD

**Issue by eggapauli** [Topshelf/Topshelf#225]
It would be great if Topshelf monitored the service to detect common misbehavior like increased memory consumption (through memory leaks) or dead-locks and then handles it like the application crashed (with the recovery configuration). Any plans on that?

**Comment by phatboyg** [comment]
That's what Supervise is intended to do, I just haven't worked on it because you can use nagios or SCOM to do the same thing.

**Comment by eggapauli** [comment]
I see. I just hoped for an integrated solution. But thanks anyway.

**Comment by hylander0** [comment]
This may or may not apply your requirements but if you want to monitor the state and get notified when your TopShelf service fails you can use this [Knowvent Extension library](https://github.com/Knowvent/KnowventTopShelf).  It uses a free Service called [Knowvent](http://www.knowvent.com) where it will monitors for heartbeats, amoung other things.  Available via Nuget:

    Install-Package Knowvent.TopShelfExtensions

*Shameless Plug: I am the founder of the Knowvent*
