### ISSUE TITLE
Publish the Serilog package to NuGet

### ISSUE THREAD

**Issue by nblumhardt** [Topshelf/Topshelf#227]
Hi all - I noticed there's now a Topshelf.Serilog project in the repository, but it doesn't seem to be published on NuGet. Is that intentional, or an oversight?

http://www.nuget.org/packages/topshelf.serilog

We're retiring the _Serilog.Extras.Topshelf_ package (it's hard for us to keep up-to-date) and would like to publish a redirect to the Topshelf.Serilog package (it looks more up-to-date).

//cc @mookid8000 

Cheers!

**Comment by mookid8000** [comment]
Maybe it's got something to do with the changes around the build that were apparently required after #221 ?

**Comment by nblumhardt** [comment]
Ah, thanks for the pointer. I've done this dance with Serilog a few times too - targeting multiple .NETs is way less fun than it should be. @phatboyg let me know if it's anything I can help with. Cheers!

**Comment by phatboyg** [comment]
I think this was an overnight on the build publishing. I can look real quick.

**Comment by phatboyg** [comment]
Okay this is in the next release.

**Comment by mookid8000** [comment]
😎
