### ISSUE TITLE
How to detect if Topshelf is running in console mode

### ISSUE THREAD

**Issue by crosswins** [Topshelf/Topshelf#229]
Is there a way when running the exe file from the Command Line (i.e. without 'install' command) to check from TopShelf that it is running in Console mode?

Refer to my original SO questions here: http://stackoverflow.com/q/28740658/161094

**Comment by phatboyg** [comment]
Replied, a cast check is the easiest solution without code changes.

**Comment by crosswins** [comment]
Ok, but can you tell me what I should cast check please? I couldn't figure out anything that might give me an indication.
Thanks

**Comment by phatboyg** [comment]
Look at the SO question, I replied with a code sample.

**Comment by crosswins** [comment]
Ok Chris, I saw it. Many thanks.

Brian

Sent from my Windows Phone
________________________________
