### ISSUE TITLE
CLI arguments that make sense

### ISSUE THREAD

**Issue by Aeal** [Topshelf/Topshelf#231]
I am having a lot of trouble with command line arguments. It would be nice if A) topshelf did not die at unknown cli arguments. B) followed its own standard for cli argumets. C) made built in arguments available through the current cli integration.

**Comment by phatboyg** [comment]
The help text explains the arguments pretty well, is there something missing or a clear course of action to be taken here?

**Comment by Aeal** [comment]
These are all issues I encountered while using topshelf on windows 8.1
Spaces in arguments do not work. If I try to wrap the arguments in quotes topshelf recognizes it as two different arguments and then dies because for some unknown reason it dies on unknown command line arguments.

 If I leave the spaces windows mangles the arguments and I dont get the full value.  You also pass commands to the service using the -name value format for the top level values, but when I add my own you force the --name:value paradigm. There should be a uniform way of handling all CLI arguments. I think my original post made it pretty clear what I would like to see:

A) the service does not die when it encounters un-known command line arguments. It seems silly to die on an unknown command line argument. This at the very least should be toggle by the consumer. 

B) Follow its own conventions for cli arguments: passing agruments to topshelf should be the same for all types of arguments. I don't understand what it not clear here. 

C) built in arguments are available to the service: when you pass -servicename servicename you cannot parse this out using the cli argument methods provided by topshelf. 

The documentation on the built in cli arguments is ok its not clear what is a switch and what is an option, but there is no documenation that I could find on defining custom arguments other than a few messages on a google group, and the processing of those arguments is very shoddy and prone to errors.

**Comment by jordansjones** [comment]
I would like to see Topshelf parse out the arguments that the library itself uses, and makes the rest, as a `string[]`, available to the hosted service in some form.

**Comment by TravisTheTechie** [comment]
Because of the way that services are launched by Windows custom command line arguments are tricky, will behave un-intuitively, and we're unlikely to support them. If you need configuration, use the app.config.

**Comment by TSteele27** [comment]
I cant use the app config. I am using topshelf as a wrapper to launch another (non .net) application as a windows service. I pass along configuration information via command line options. The service launched by the application changes based on the configuration so configuring the topshelf wrapper via an app config is not a possible solution since the same package will be used to launch multiple windows services all with different configurations, and forcing consumers of my package to edit the configuration file is a horrible/error prone idea. Even if you cannot pass command line options to the running process, topshelf still does dumb things like crash the process on unknown cli arguments, and does not give access to the built in cli arguments with the interface you supply.

**Comment by Aeal** [comment]
I cant use the app config. I am using topshelf as a wrapper to launch another (non .net) application as a windows service. I pass along configuration information via command line options. The service launched by the application changes based on the configuration so configuring the topshelf wrapper via an app config is not a possible solution since the same package will be used to launch multiple windows services all with different configurations, and forcing consumers of my package to edit the configuration file is a horrible/error prone idea. Even if you cannot pass command line options to the running process, topshelf still does dumb things like crash the process on unknown cli arguments, and does not give access to the built in cli arguments with the interface you supply.

**Comment by TravisTheTechie** [comment]
I hear your complaints about handling of the command line, but what you miss is that when the program runs as a service those command line arguments used during installation are lost. 

I could imagine a world where you edit the app.config based upon the passed configuration, which we don't currently enable. That would primarily be in your hand to implement though.

**Comment by asgerhallas** [comment]
I know this is an old issue, but some of the problems seems unsolved - specifically when using multiple instances of the same service, which means I can't edit the app.config on install. When installing using sc.exe I can just add the arguments inside the binpath like "MyService.exe -args:abc" and then they will be picked up on start too. Wouldn't it be possible for topshelf to append the command line arguments the binpath on install? Maybe optional... maybe as a command to customize the binpath directly.

Or am I missing something? :)
