### ISSUE TITLE
New Topshelf release

### ISSUE THREAD

**Issue by jozefizso** [Topshelf/Topshelf#233]
Hi, what are plans for a new Topshelf release? We would like to enjoy some bug fixes that were done in recent commits. Is Topshelf available also as nightly build package?

**Comment by TravisTheTechie** [comment]
You can grab builds from TeamCity if you want unreleased bits: http://teamcity.codebetter.com/viewType.html?buildTypeId=bt48. Just login as guest.

**Comment by phatboyg** [comment]
Done.
