### ISSUE TITLE
Single Serilog logger

### ISSUE THREAD

**Issue by pawelpabich** [Topshelf/Topshelf#234]
Hi,

Serilog docs say there should be only one Serilog logger. At the moment the TopShelf integration with Serilog takes Serilog config as input so I end up with 2 loggers. One in TopShelf and one in my code. 

Would it be a good idea to extend UseSerilog with another overload that takes an instance of Serilog Logger instead of Serilog config?

**Comment by IanYates** [comment]
:+1:  - makes sense to me.

**Comment by phatboyg** [comment]
Pull request?

**Comment by pawelpabich** [comment]
Sure, I will have a look

**Comment by pawelpabich** [comment]
Anything I should change ?

**Comment by joelweiss** [comment]
:+1: I'm waiting on this fix as well, any ETA?

**Comment by asherw** [comment]
Hi, put me down as another person who would also like this in.
Thanks!

**Comment by pawelpabich** [comment]
Anything else I can do to help with this PR ?
