### ISSUE TITLE
Upgrade Nlog to latest

### ISSUE THREAD

**Issue by tomikiss** [Topshelf/Topshelf#237]
Update Nlog to 4.0.1 which is the latest version of Nlog in the moment.

**Comment by tomikiss** [comment]
Sorry your latest commit haven't change the log call signature so exception won't be logged correctly( breaking changes in Nlog 4)

**Comment by phatboyg** [comment]
Oh, I missed that part. I'll get it in a patch release shortly.

**Comment by TravisTheTechie** [comment]
Has this been completed Chris?
