### ISSUE TITLE
topshelf seem not work in vnext 

### ISSUE THREAD

**Issue by tomsean** [Topshelf/Topshelf#238]

**Comment by TravisTheTechie** [comment]
Can you describe the context a little more? What are you trying to do?

**Comment by Lejdholt** [comment]
I get these errors when trying to start a vnext console app:

Topshelf.HostFactory Error: 0 : An exception occurred creating the host, Topshelf.HostConfigurationException: The service was not properly configured:
[Failure] Command Line An unknown command-line option was found: SWITCH: appbase (True)
[Failure] Command Line An unknown command-line option was found: ARGUMENT: "C:\Users\...\EventListner"
[Failure] Command Line An unknown command-line option was found: ARGUMENT: "Microsoft.Framework.ApplicationHost"
[Failure] Command Line An unknown command-line option was found: SWITCH: configuration (True)
[Failure] Command Line An unknown command-line option was found: ARGUMENT: Debug
[Failure] Command Line An unknown command-line option was found: ARGUMENT: "EventListner"
[Failure] Command Line An unknown command-line option was found: SWITCH: appbase (True)
[Failure] Command Line An unknown command-line option was found: ARGUMENT: "C:\Users\....\src\EventListner"
[Failure] Command Line An unknown command-line option was found: ARGUMENT: "Microsoft.Framework.ApplicationHost"
[Failure] Command Line An unknown command-line option was found: SWITCH: configuration (True)
[Failure] Command Line An unknown command-line option was found: ARGUMENT: Debug
[Failure] Command Line An unknown command-line option was found: ARGUMENT: "EventListner"
[Success] Name EventListner
[Success] ServiceName EventListner
   at Topshelf.Configurators.ValidateConfigurationResult.CompileResults(IEnumerable`1 results)
   at Topshelf.HostFactory.New(Action`1 configureCallback)
Topshelf.HostFactory Error: 0 : The service terminated abnormally, Topshelf.HostConfigurationException: The service was not properly configured:
[Failure] Command Line An unknown command-line option was found: SWITCH: appbase (True)
[Failure] Command Line An unknown command-line option was found: ARGUMENT: "C:\Users\Fredrik\Source\Repos\PlannigHub\src\EventListner"
[Failure] Command Line An unknown command-line option was found: ARGUMENT: "Microsoft.Framework.ApplicationHost"
[Failure] Command Line An unknown command-line option was found: SWITCH: configuration (True)
[Failure] Command Line An unknown command-line option was found: ARGUMENT: Debug
[Failure] Command Line An unknown command-line option was found: ARGUMENT: "EventListner"
[Failure] Command Line An unknown command-line option was found: SWITCH: appbase (True)
[Failure] Command Line An unknown command-line option was found: ARGUMENT: "C:\Users\...\src\EventListner"
[Failure] Command Line An unknown command-line option was found: ARGUMENT: "Microsoft.Framework.ApplicationHost"
[Failure] Command Line An unknown command-line option was found: SWITCH: configuration (True)
[Failure] Command Line An unknown command-line option was found: ARGUMENT: Debug
[Failure] Command Line An unknown command-line option was found: ARGUMENT: "EventListner"
[Success] Name EventListner
[Success] ServiceName EventListner
   at Topshelf.Configurators.ValidateConfigurationResult.CompileResults(IEnumera
ble`1 results)
   at Topshelf.HostFactory.New(Action`1 configureCallback)
   at Topshelf.HostFactory.Run(Action`1 configureCallback)

**Comment by TravisTheTechie** [comment]
Do you have a sample project that exhibits this behaviour? What version of Visual Studio/.NET is this running on?

**Comment by alastairs** [comment]
[This gist](https://gist.github.com/alastairs/a22ef6088f37a660d727) implements [the Topshelf sample](http://docs.topshelf-project.com/en/latest/configuration/quickstart.html) in an ASP.NET vNext Console Application. It displays the same output as above.

**Comment by Lejdholt** [comment]
@alastairs thx. You saved me some time =)

**Comment by alastairs** [comment]
@Lejdholt no worries :smile: I might have some time this afternoon to look into it myself; I'll post back here if I make any progress.

**Comment by Lejdholt** [comment]
@TravisTheTechie now that Visual Studio 2015 is released, any idea when ASP.NET 5 will be supported?

**Comment by TravisTheTechie** [comment]
@Lejdholt, this is on my radar but through next week I'm across the world. When I'm back, I'm hoping to carve out some time to take a swing at this.

**Comment by TravisTheTechie** [comment]
Alright, I've spent some time with this, and I can confirm it's an issue. I do not yet have a fix for it. 

It is possible that Topshelf, as it stands, won't run as a dnx executable. The execution environment is different enough, we might require some new magic to glue it together. Or a new solution comes to me while showering or is suggested to me.

**Comment by phatboyg** [comment]
It smells like there are arguments on the command-line with DNX that we have to accept/ignore.

**Comment by TravisTheTechie** [comment]
That will get us running it in console mode, but getting it to install as a service will be more complicated.

**Comment by AntonLosev** [comment]
Have You planned to fix problems with vnext?

**Comment by TravisTheTechie** [comment]
We do not have a planned fix for vNext.

**Comment by AntonLosev** [comment]
very bad. I seen articles about running dnx as win service
http://taskmatics.com/blog/run-dnx-applications-windows-service/
http://taskmatics.com/blog/host-asp-net-in-a-windows-service/

**Comment by phatboyg** [comment]
Well, we do accept pull requests...

That being said, I'm sure it's something we'll look at in the next beta or two.

**Comment by LeeCheneler** [comment]
bump - Any news on this front? It would be great if TopShelf worked for DNX apps, even if it was restricted to frameworks dnx451-dnx46 and not running on the core clr.

**Comment by LeeCheneler** [comment]
Turns out the dnx console apps are essentially being scrapped and will be replaced with CLI console apps that have a real entry point. My understanding is that Topshelf should "just work" as it does now. The CLI console apps will be much more stable from aspnet 5 RC2

**Comment by TravisTheTechie** [comment]
That would be awesome. The early betas of ASP.NET make this a significant undertaking. We'll wait and see what it looks like when everything final.

**Comment by marono** [comment]
If this is still an issue here's how I got it working for dnx451:
```
args = args.Where(a => a != "<service-name>").ToArray();
return (int)HostFactory.Run(c =>
            {
                c.ApplyCommandLine(String.Join(" ", args));
                ...
             }
```

To explain, inject actual args into the service, while removing the image name that's usually the first parameter in the array. It seems that when running it via DNX, some other parameters are injected by DNX itself to figure out what and how to execute.

**Comment by LeeCheneler** [comment]
@marono dnx console apps are due to change significantly in aspnet5 RC2 which is due in February. For instance, right now dnx console applications are just dlls. You then run that dll via dnx: `dnx run blah`

In RC2 the actual dotnet team have taken the reigns from the aspnet team and are formalizing the console applications so they are a true .exe with a real entry point. This should render any work arounds required for dnx obsolete.

**Comment by marono** [comment]
Hi @LeeCheneler,

Sorry I haven't specified earlier, my work is around the dotnet cli, dnx's replacement.

Regards,

**Comment by LeeCheneler** [comment]
@marono ah OK cool! I'll be sure to check back here if I'm having trouble when RC2 is released. We're planning on migrating a few of our service apps over to the new stuff once it's out :P

**Comment by TravisTheTechie** [comment]
Moved to #277 in favor of `dotnet` cli.
