### ISSUE TITLE
HostControl Restart not implemented

### ISSUE THREAD

**Issue by gthvidsten** [Topshelf/Topshelf#241]
The Restart method on HostControl is not implemented when running TopShelf as a Windows Service.
I'm guessing it's the Restart method in src/Topshelf/Runtime/Windows/WindowsServiceHost.cs that is run when I call HostControl.Restart(), and that method is indeed not implemented.

**Comment by TravisTheTechie** [comment]
Can you tell me a bit about what you're trying to do? Maybe there's a better way.

**Comment by gthvidsten** [comment]
I'm trying to have Windows restart the service. I need to do that from the service that is started by Topshelf.
It would be nice if that was available through the Restart method.

###Bootstrapper
```C#
HostFactory.Run(x => {
    x.Service<MyService>(s => {
        s.ConstructUsing(name => container.GetExportedValue<MyService>());
        s.WhenStarted((host, control) => {
            host.Start(control);
            return true;
        });
        s.WhenStopped((service, control) => service.Stop());
    });
    x.RunAsLocalSystem();
    x.SetDescription("My demo service");
    x.SetDisplayName("My demo service");
    x.SetServiceName("MyDemoService");
    x.EnableServiceRecovery(rc => rc.RestartService(0));
});
```

###MyService
```
public class MyService {
    private HostControl _topshelfController;

    public bool Start(HostControl controller) {
        _topshelfController = controller;
    }

    private void Restart() {
        _topshelfController.Restart();
    }
}
```

**Comment by TravisTheTechie** [comment]
Alright, I looked through a bunch of code and we need to just remove that item from the interface. There's no real way to request a restart -- it's just a shutdown and start. The issue with requesting a shutdown then a restart is that your service is shutdown now, who's going to ask you to start? 

If you really need to restart the service, kill it with a non-zero exit code and let the service recovery settings get you back on track.

**Comment by Peter-Optiway** [comment]
A few years later and the method still exists, if it does not work then it should be removed?
