### ISSUE TITLE
`HostControl.Restart()` is confusing

### ISSUE THREAD

**Issue by TravisTheTechie** [Topshelf/Topshelf#242]
`HostControl.Restart()` implies that we have functionality that doesn't exist. Rehab and the Supervisor work never got fully off the ground after we wiped the slate in 3.0. 

I'm guessing our best bet is to just remove that stuff.

**Comment by gthvidsten** [comment]
If `HostControl.Restart()` is removed, what would be a good way for the service class to request that Windows do a restart of the service application?

**Comment by TravisTheTechie** [comment]
You can't really tell the SCM to do a restart, it's a stop then start & after stop is effected your service is dead. Unable to ask to startup at that point. The best bet is using the recovery options and crashing your service early. This would let the SCM use your configuration to restart the service on it's own.

**Comment by gthvidsten** [comment]
After adding some recovery options and killing the service with `System.Environment.Exit(someErrorCode);` it seems that Windows does start it again.
Could this command maybe be added to `HostControl.Restart()`? Even though it looks a bit dirty it does actually work, and in case Microsoft adds some better service restart options in the future it can be added to an already existing method.

**Comment by TravisTheTechie** [comment]
Using `System.Environment.Exit` will only work if you have the recovery options set. I'd rather not bake in behaviour that only works if you have some specific configuration set. This will be non-intutitive, calling `Restart` and the service just crashes without the proper configuration.
