### ISSUE TITLE
How do I get the service instance name from within code of my service?

### ISSUE THREAD

**Issue by fandrei** [Topshelf/Topshelf#244]

**Comment by phatboyg** [comment]
The HostSettings is available when the service class is created, so it can be used there.

In the sample code, you can see the settings argument being passed to the constructor:
https://github.com/Topshelf/Topshelf/blob/develop/src/SampleTopshelfService/Program.cs#L32

The ConstructUsing() method also passed the host settings.

**Comment by fandrei** [comment]
@phatboyg, thanks
