### ISSUE TITLE
How can I make my Topshelf service stop, when a certain type of exception happens?

### ISSUE THREAD

**Issue by fandrei** [Topshelf/Topshelf#245]

**Comment by phatboyg** [comment]
If your service's ```Start``` method throws an exception, the service will fail to start.

Once the service is running, if an unhandled exception is thrown, the service will stop, and report it as a crash to the service control manager. This will allow any service restart behavior configured in the services configuration to take over as it was an abnormal exit.

If you need to Stop your service programatically, use the ```HostControl``` method ```Stop```. The ```HostControl``` interface is passed to your service class's ```Start``` method when your class implements the ```ServiceControl``` interface. If you are using the delegate-based ```WhenStart...``` methods, well, switch to ```ServiceControl```.

**Comment by AnilAwadh** [comment]
In my case, it doesn't responses when an AggregateException is thrown from Parallel.ForEach loop. Service status is running but service seems stuck and nothing happen. 

Even AppDomain.CurrentDomain.UnhandledException didn't take care as well as OS's Application event is not logged.

**Comment by phatboyg** [comment]
A code example of what you're seeing (as a Gist, etc.) really helps to understand the situation and the unexpected behavior. If you could post something that I could use to reproduce the issue, that would be very helpful.

All of the stock sample services show throwing exceptions, etc. and they work properly, so you may have encountered a situation that is unexpected.

**Comment by BlueManiac** [comment]
While testing a custom logger (using HostLogger.UseLogger) I realized that Unhandled Exceptions thrown from other threads do not seem to be catched. The service seems to just continue without any notification that anything went wrong. Exceptions thrown from the main thread seems to be catched fine.

**Comment by TravisTheTechie** [comment]
How are you generating your threads? Tasks, by default, I believe capture exceptions. If the exception doesn't bubble up to the app domain, there's no way for it be caught there.

**Comment by zanfranceschi** [comment]
```
Task.Run(() => {
// your thrown exception here won't stop the service
});
```

```
new Thread(() => {
// your exception here will stop the service
}).Start();
```

**Comment by taniaengel** [comment]
Fast forward to 2018, TopShelf has HostControl.Stop(TopshelfExitCode). https://github.com/Topshelf/Topshelf/commit/fc9bff9e99947fbdc8a889f286cebae6fe08702a

I chose to use this to stop the service host with TopshelfExitCode.UnhandledServiceException anytime I hit an unhandled exception in my async run thread. It does work to stop the windows service, and generate an Error windows system event log. The comment on the commit indicates that the recovery should trigger.
> This allows services to signal recovery states to the Windows SCM

 My service is set to recovery option " restart the service". However, it does not cause the recovery options to trigger.
