### ISSUE TITLE
Topshelf applications don't stop when started with invalid command line arguments

### ISSUE THREAD

**Issue by fandrei** [Topshelf/Topshelf#246]
AFAIK the standard behavior in such a case is to shut down the application, isn't it?

**Comment by phatboyg** [comment]
Please add some details to the issue, such as how you're accepting the command lines and where they are being determined invalid. There is currently not enough information to have any idea how to answer your question.

**Comment by fandrei** [comment]
@phatboyg, it seems the problem was in another place
