### ISSUE TITLE
TopShelf always spawns a console window when stopping\starting a service.

### ISSUE THREAD

**Issue by scratch-net** [Topshelf/Topshelf#247]
Hi There!
I have an app with TopShelf that is installed as 6 different instances. I also added pre\post build event which stops and then starts all those 6 services. But during the build I see console that pops up 6 times when services stop and then 6 times when they start. I tried many options including a separate app that does CreateProcess with the hidden console but that does not help, they continue to pop up 12 times every time I build my project. 
Could you please advise?

**Comment by phatboyg** [comment]
Those windows pop up and then disappear? The way you start the console commands to install/uninstall should dictate the window behavior, Topshelf just attaches to the console for output but doesn't do any custom window management.

**Comment by scratch-net** [comment]
Yes, they just do flash
@phatboyg So, should I somehow reinstall those services in another way?

**Comment by phatboyg** [comment]
Can you post your build event text? If it isn't using ```start```, it should write to the Output Window in Visual Studio from what I've read.

**Comment by scratch-net** [comment]
I've tried both `start` and `call`, nothing helps. There's outut to visual studio but console windows still flash.

I don't call app directly, I do it via bat file which stops/starts all of them one by one

@echo off
pushd "%~dp0"
if [%noworkers%] EQU [] (
		call Apps\Worker\bin\Worker.exe start -instance:Data
		call Apps\Worker\bin\Worker.exe start -instance:Email
...
)
popd

**Comment by phatboyg** [comment]
```start /min```

Start minimized?

**Comment by scratch-net** [comment]
@phatboyg 
It's weird,
On one of my PCs it's ok and everything runs in the same console window.
But on the other PC it spawns those console flashes. Not sure what it depends

**Comment by scratch-net** [comment]
It was UAC that caused that behaviour. It got enabled somehow.
