### ISSUE TITLE
Apply StringFormatMethodAttribute from Reshaper to the LogWriter

### ISSUE THREAD

**Issue by regisbsb** [Topshelf/Topshelf#248]
It's a tool that is ubiquitous and without that the DebugFormat and friends do not have a reshaper help.
If you are happy I could do it but I don't know where to put the Resharper.Annotations

**Comment by phatboyg** [comment]
I'd prefer to keep it clean with zero dependencies, even those that are just to make the IDE smarter.

**Comment by regisbsb** [comment]
We had that before on https://github.com/Topshelf/Topshelf/commit/4ff780bcbaab1ab8552358f1c59ce232074e5f1d but I cannot trace when it was deleted. There is not dependencies to be added, is just one file that should be added to the project and that's it really. Then we could use the attributes.

**Comment by regisbsb** [comment]
@phatboyg Can we meet in the middle? May I ask you to create a Topshelf.ReshaperAnnotations repo  with the same kind of structure as: https://github.com/vbfox/nlog-resharper-annotations .
I have already a started a Topshelf.ExternalAnnotations.xml https://gist.github.com/regisbsb/421c6da86d356c0b0e16

**Comment by phatboyg** [comment]
Absolutely. Sounds like a good approach. 

____
Chris Patterson




On Wed, Aug 26, 2015 at 2:43 AM -0700, "Regis Bittencourt" <notifications@github.com> wrote:












@phatboyg Can we meet in the middle? May I ask you to create a Topshelf.ReshaperAnnotations repo  with the same kind of structure as: https://github.com/vbfox/nlog-resharper-annotations .

I have already a started a Topshelf.ExternalAnnotations.xml https://gist.github.com/regisbsb/421c6da86d356c0b0e16

**Comment by regisbsb** [comment]
OK so should I do it on my own namespace and after that I could transfer to you or should we create it at Topshelf's one and PR?
