### ISSUE TITLE
Move the builds to fake

### ISSUE THREAD

**Issue by naveensrinivasan** [Topshelf/Topshelf#254]
The current build is using rake. Most of the new .NET Open source projects are built using FAKE. http://fsharp.github.io/FAKE/ . What are your thoughts on moving this to FAKE?

**Comment by phatboyg** [comment]
I'll move it to FAKE, as I've done with MassTransit and Automatonymous (the mt3 branches).

**Comment by naveensrinivasan** [comment]
Could I take this one and submit a PR?

**Comment by phatboyg** [comment]
Yes please!

**Comment by KevM** [comment]
@naveensrinivasan :+1:

**Comment by TravisTheTechie** [comment]
Any progress on this? I'd be happy to move beyond using albacore.

**Comment by phatboyg** [comment]
I'll do it once I drop .NET 3.5 in the next few weeks. MassTransit and Automatonymous are already there. So an easy copy once old frameworks are not an issue.
