### ISSUE TITLE
Create basic site with topshelf.github.io

### ISSUE THREAD

**Issue by phatboyg** [Topshelf/Topshelf#258]
@TravisTheTechie can you work your magic on Topshelf as well? It's the last one to convert, and they're all golden.

Be nice to get the logos moved over as well, since we paid for them! :)

**Comment by TravisTheTechie** [comment]
Yeah, I can do this soon.

**Comment by TravisTheTechie** [comment]
I just dumped the main WP site page. https://github.com/Topshelf/topshelf.github.io.
