### ISSUE TITLE
Spaces Not Allowed in Service or Display Name

### ISSUE THREAD

**Issue by splatteredbits** [Topshelf/Topshelf#259]
When installing a service, TopShelf doesn't like spaces in the service's name:

> .\TopShelfSample.exe install --interactive -servicename "Top Shelf Service" -displayname "Top Shelf Service"
> Topshelf.HostFactory Error: 0 : An exception occurred creating the host, Topshelf.HostConfigurationException: The service was not properly configured:
> [Failure] Name must not contain whitespace, '/', or '\' characters
> [Success] Name Top Shelf Service
> [Success] ServiceName Top Shelf Service
>    at Topshelf.Configurators.ValidateConfigurationResult.CompileResults(IEnumerable`1 results)
>    at Topshelf.HostFactory.New(Action`1 configureCallback)
> Topshelf.HostFactory Error: 0 : The service terminated abnormally, Topshelf.HostConfigurationException: The service was not properly configured:
> [Failure] Name must not contain whitespace, '/', or '\' characters
> [Success] Name Top Shelf Service
> [Success] ServiceName Top Shelf Service
>    at Topshelf.Configurators.ValidateConfigurationResult.CompileResults(IEnumerable`1 results)
>    at Topshelf.HostFactory.New(Action`1 configureCallback)
>    at Topshelf.HostFactory.Run(Action`1 configureCallback)

Windows does support spaces in service names. Our company's standard is to have spaces in a service's name, e.g. "CompanyName ServiceName". We have automation in place around this assumption, which means TopShelf won't work for us.

Please update TopShelf to support spaces

**Comment by StevenBonePgh** [comment]
Can this one be merged into the next TopShelf release, please?

**Comment by phatboyg** [comment]
Yeah, the next release is going to be .NET 4.5.2 only though, is that okay with you?

**Comment by StevenBonePgh** [comment]
I'm not in any great need for this, but I'm porting from some rather poor attempt at TopShelf to TopShelf and would like to retain the service name.  I believe 4.5.2 is the minimum supported version of .NET currently anyway.
