### ISSUE TITLE
Is it possible to keept the program to run as normal program and a service at the same time?

### ISSUE THREAD

**Issue by Shuliyey** [Topshelf/Topshelf#264]
Just wondering is it possible to have the Topshelf program to run as a usual program, at the same time also have the option to install the program as a service.

So far to install the program as a service

``` bash
program.exe install
```

But if say program.exe can do other things such as

``` bash
program.exe test
```

Topshelf would complain about test is an unknown command.

**Comment by phatboyg** [comment]
If you just run a Topshelf service from the console, it will start the service in "console mode." This makes it super easy to debug using F5, versus attaching to a service and all that nonsense.

In fact, that feature is one of the main reasons Topshelf was created.

**Comment by Shuliyey** [comment]
Hi @phatboyg ,

thank you :smile: , yep it's working for me :smile: 

I do have another problem.

Info
====
I have an existing CLAP application, which listens to a Redis queue, when I do

```cmd
application.exe listen
```

I was able to integrate this application well with Topshelf, by only configure application as a service when the program's first argument is "install", "uninstall" or "-displayname". If it's none of these three, then the console app (command line app) will do what ever else it suppose to do.

I've configured Topshelf's **start** method to be exactly the start method that's called, when we do **"application.exe listen"**. 

What I have now is that, I was able to get the service installed fine by running 
```cmd
application.exe install
```

I also confirmed when I type
```cmd
"D:\Documents\C#\Topshelf\test\test\application.exe"  -displayname "Topshelf Test Application" -servicename "Topshelf.Test"
```

The application will do exactly the same thing, as if we're doing 
```cmd
application.exe listen
```

Problem
======
The problem is when I try to start the service, I get the error **"Error 5: Access is Denied"**
![image](https://cloud.githubusercontent.com/assets/4773348/11326881/3dcf978c-91c9-11e5-8837-0c53eaa39cc2.png)

I have done various research on this and have set various permissions accordingly
* http://stackoverflow.com/questions/574411/system-error-5-access-is-denied-when-starting-a-net-service
* http://stackoverflow.com/questions/4267051/error-5-access-denied-when-starting-windows-service
* http://www.thewindowsclub.com/access-is-denied-local-services-windows-8-1

But The problem doesn't seem to go away, the only thing I could think of is that the problem is actually **not related to permission issue**.

I mean have do a while loop in the method that's called to **start the service**
```C#
                    while (!this.shutdownRequested)
                    {
```
When the **stop service method** is called, the this.shutdownRequested will be set to true.
```C#

        public void Stop()
        {
            this.taskRunner.ShutDown();
        }

        public void ShutDown()
        {
            this.shutdownRequested = true;
        }
```

Could this be the cause? (I don't get this permission issue problem, when I was going through the example code on the Topshelf Documentation page.

**Comment by IanYates** [comment]
As a matter of general debugging, do you have some sort of logging framework set up?  If not, get one going (eg Serilog + Seq).  Then you can at least get a handle on how far through your service startup code you reach before you get the (possibly incorrect) *permission denied* error.

Also, you could try running process monitor (www.sysinternals.com) and just watch what file & registry keys are being accessed by your service as it starts.  You may get lucky and spot some file or registry access being denied there too.

Finally, under what account are you running your service?  Is it using the same account used for testing & dev or some other account?  Try using the same account to see if that helps.  You could also try local system.  If it starts working then you have a permissions issue.

**Comment by Shuliyey** [comment]
@IanYates thanks Ian, I will do the above suggestions :smile: , will update

**Comment by TravisTheTechie** [comment]
I don't believe this is a Topshelf issue as much as an artifact of the service that's running and what it needs access too.
