### ISSUE TITLE
Core CLR Support

### ISSUE THREAD

**Issue by galvesribeiro** [Topshelf/Topshelf#265]
Hello,

CoreCLR just got released as RC1 with go-live license so, it does not come with Windows Service APIs by default.

Will Topshelf support it soon? 

We are porting Project Orleans to Coreclr (https://github.com/dotnet/orleans/issues/368) and would be interesting to have a Topshelf host for Windows Service and Azure Worker Roles as well. Any plans?

Thanks!

**Comment by phatboyg** [comment]
Absolutely. I'm hoping to start working on it soon (or maybe others have already started). I was waiting for the RC bits to get the code ready, to have a stable target to work towards until the final release.

The .Azure project would also be updated to support targeting RoleEntryPoints that are CoreCLR enabled. Also looking to add support for reliable services in Service Fabric to get higher service density!

**Comment by galvesribeiro** [comment]
That is good @phatboyg!

SF is on our radar to act as a host. We already have some people who already host Orleans on SF.

> The .Azure project would also be updated to support targeting RoleEntryPoints that are CoreCLR enabled. 

Are Azure RoleEntryPoint already support CoreCLR?

**Comment by phatboyg** [comment]
I don't think any of the assemblies for Azure have support for .NET core
yet do they? I haven't seen one for Azure Service Bus (for MassTransit) yet.

**Comment by galvesribeiro** [comment]
Some of the libraries already has at least beta versions... The problem is the main libraries which involve the role lifecycle...

**Comment by jdmcnair** [comment]
+1

**Comment by galvesribeiro** [comment]
@phatboyg Hey! Any news on this port? .Net Core now has go-live license since RC1 and is almost on RC2. 

Regarding Azure assemblies, there are preview versions with go-live licenses as well. I'm currently using WindowsAzure.Storage and it is working pretty well so far.

**Comment by TravisTheTechie** [comment]
#277 will handle this once the API surface is more settled.
