### ISSUE TITLE
Service cannot be executed from Task Scheduler as console app

### ISSUE THREAD

**Issue by Moulde** [Topshelf/Topshelf#266]
Hi

I have an issue where a topshelf service cannot be executed by the Task Scheduler.
It throws this error and exists

    2015-12-08 09:47:47.353 +01:00 [Information] Starting as a Windows service
    2015-12-08 09:47:47.368 +01:00 [Fatal] The Topshelf.Runtime.Windows.WindowsHostSettings service has not been installed yet. Please run 'Namespace.Something, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null install'.
    2015-12-08 09:47:47.415 +01:00 [Error] The service terminated abnormally
    Topshelf.TopshelfException: The Topshelf.Runtime.Windows.WindowsHostSettings service has not been installed yet. Please run 'Namespace.Something, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null install'.
       at Topshelf.Runtime.Windows.WindowsServiceHost.Run()
       at Topshelf.HostFactory.Run(Action`1 configureCallback)

Digging into the source, it seems that the reason it will attempt to execute as a windows service rather than a console application, is the following line

https://github.com/Topshelf/Topshelf/blob/201c4303a203fc513783da9854e217089154582e/src/Topshelf/Runtime/Windows/WindowsHostEnvironment.cs#L143

    public bool IsRunningAsAService
        {
            get
            {
                try
                {
                    Process process = GetParent(Process.GetCurrentProcess());
                    if (process != null && process.ProcessName == "services")
                    {
                        _log.Debug("Started by the Windows services process");
                        return true;
                    }
                }
                catch (InvalidOperationException)
                {
                    // again, mono seems to fail with this, let's just return false okay?
                }
                return false;
            }
        }

I belive the task scheduler itself is a windows service, and is executing the process from a process which has service in the name. So topshelf will attempt to run the service as a windows service, but fail when it is not installed.

And yes, I know it's odd to run a topshelf service as a console app through the task scheduler.....
The reason for this is that we started using topshelf, and then had to implement a service fast, and it is currently not implemented for continous execution. Meaning that we start it, it will do magic, and then close.

My current solution will be to remove topshelf, as it's not really needed currently.
This issue is just to notify you of this. I imagine a fix could be to either change the windows service detection code, or perhaps add a flag to allow people to force running as console.

**Comment by TravisTheTechie** [comment]
We could add a flag, I'm not sure if there's better detection methods we could use. If you'd like this, we'd happily accept a PR. This is enough of an edge case I don't know that will get address anytime soon.

**Comment by TravisTheTechie** [comment]
I'm going to close this since there hasn't been any more feedback on it. But feel free to open it if you have more thoughts or really want this.
