### ISSUE TITLE
Website layout is broken

### ISSUE THREAD

**Issue by logankp** [Topshelf/Topshelf#267]
When visiting the website, the layout appears completely broken.
See the attached image.
![image](https://cloud.githubusercontent.com/assets/5343074/11658351/c128cb16-9d87-11e5-843c-cbfe3cf520a5.png)

**Comment by DustinVenegas** [comment]
This is probably related to the missing CSS. 

http://topshelf-project.com/css/_reset.css 
http://topshelf-project.com/css/_960.css 
http://topshelf-project.com/css/_typo.css 
http://topshelf-project.com/wp-includes/js/wp-emoji-release.min.js?ver=4.3.1

**Comment by logankp** [comment]
Upon digging into this further, it seems GitHub uses Jekyll to process pages and files with underscores have a special meaning to Jekyll (https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/). This can be fixed by removing the underscore in the CSS files or adding a .nojekyll to the repository root.

**Comment by TravisTheTechie** [comment]
Thanks for pointing out what was wrong. I've just deployed changes and it appears to have fixed the layout for me.
