### ISSUE TITLE
The method UseLog4Net is not available

### ISSUE THREAD

**Issue by dougcosta** [Topshelf/Topshelf#268]
Hello!

I'm trying use Log4Net in my app, but when I try set it up as the documentation, the method UseLog4Net is not available.

What am I doing wrong?

Version: 3.3.1

My code:
-----------
    using log4net.Config;
    using Topshelf;

    namespace MyApp
    {
        class Program
        {
            static void Main(string[] args)
            {
                XmlConfigurator.Configure();

                HostFactory.Run(t =>
                {
                    //Method below is not available
                    //t.UseLog4Net();
                    t.Service<MyService>(s =>
                    {
                        s.ConstructUsing(name => new Service());
                        s.WhenStarted(tc => tc.Start());
                        s.WhenStopped(tc => tc.Stop());
                        s.WhenShutdown(tc => tc.Shutdown());
                    });

                    t.RunAsNetworkService();

                    t.SetDescription("Consume the informations.");
                    t.SetDisplayName("Consumer");
                    t.SetServiceName("Consumer");
                });
            }
        }
    }

Thank you!

**Comment by TravisTheTechie** [comment]
Did you include the matching logging package, [Topshelf.Log4net](http://www.nuget.org/packages/Topshelf.Log4Net/)?

**Comment by dougcosta** [comment]
Hello!

No, I didn't. Now it works!

Thank you so much!
