### ISSUE TITLE
TopShelf will not start when there are space characters in its install path

### ISSUE THREAD

**Issue by tofalck** [Topshelf/Topshelf#270]
I'm on a Windows 10 environment

Steps to reproduce:

* Copy your TopShelf based service to a folder somewhere with no space characters in the path and observe that the service starts fine.

* Copy your TopShelf based service to a sub folder under either 'C:\Program Files' or 'C:\Program Files (x86)' (or any other folder with a space in the path for that matter)

* On cmd prompt:
  * C:\Program Files (x86)\Your Service Folder> ```<Your Service Host>```.exe install

  * C:\Program Files (x86)\Your Service Folder> ```<Your Service Host>```.exe start

Result: 

Topshelf.Hosts.StartHost Error: 0 : The service failed to start., System.InvalidOperationException: Cannot start service <Your service name> on computer '.'. ---> System.ComponentModel.Win32Exception: The service did not respond to the start or control request in a timely fashion
   --- End of inner exception stack trace ---
   at System.ServiceProcess.ServiceController.Start(String[] args)
   at System.ServiceProcess.ServiceController.Start()
   at Topshelf.Runtime.Windows.WindowsHostEnvironment.StartService(String serviceName, TimeSpan startTimeOut)
   at Topshelf.Hosts.StartHost.Run()

**Comment by sm-g** [comment]
Why this closed? How you resolve this issue?
