### ISSUE TITLE
Force a crash from a windows service.

### ISSUE THREAD

**Issue by ivaningrooves** [Topshelf/Topshelf#271]
Hi everyone!

How do I force a crash from a windows service to have the service recovery kick in?
My service does its work in a Task which is run from the Topshelf Start lambda like so:
```c#
        public bool Start(HostControl control)
        {
            _hostControl = control;
            
            _serviceTask = new Task(() =>
            {
                // do work and if necessary crash to force a service restart
                throw new ApplicationException("Something went wrong.");
            });
            _serviceTask.Start();

            return true;
        }
```
I tried many different configurations but it seems the Exception thrown from the Task does not end up in the UndhandledException handler in Topshelf ? What am I doing wrong? Is there a way to do something like this?
```c#
        public bool Start(HostControl control)
        {
            _hostControl = control;
            
            _serviceTask = new Task(() =>
            {
               control.Crash(new ApplicationException("Something went wrong."));
            });
            _serviceTask.Start();

            return true;
        }
```

If I throw an exception from anywhere *but* my task, the service stops gracefully and the operating system (Windows Server 2012) does not restart it. So how do I make it restart? How do I make my service crash?

**Comment by TravisTheTechie** [comment]
[`Environment.Exit(1)`](https://msdn.microsoft.com/en-us/library/system.environment.exit(v=vs.110).aspx) should do what you're looking for.

**Comment by ivaningrooves** [comment]
Thanks Travis, the problem I had was using a 'Task' instead of a 'ThreadPool'. The Task does its own exception handling and 'hides' the exception in a member variable. Using a ThreadPool with a plain thread resolved my issue.

**Comment by mishrsud** [comment]
@ivaningrooves I'm curious, did you try hooking into TaskScheduler.UnobservedTaskException event? If a Task runs into an unhandled exception and is not being awaited, this event gets triggered. I've been able to use this.
