### ISSUE TITLE
Service was not properly configured when updating from v3.0.2.0b3fd3 to v3.3.154

### ISSUE THREAD

**Issue by jruizaranguren** [Topshelf/Topshelf#273]
I have some integration tests launched with NUnit of a windows service which run the following code:

            HostFactory.Run(x =>
            {
                x.Service<EtlService>(s =>
                {
                    s.ConstructUsing(_ =>
                        new EtlService(new List<ICommand> {
                            new ProcessCommand(new ConsoleLogger()),
                            new CombineCommand(new ConsoleLogger()),
                            new LoadCommand(new ConsoleLogger())
                    }));
                    s.WhenStarted(service => service.Start());
                    s.WhenStopped(service => service.Stop());
                });
                x.RunAsLocalSystem();
                x.SetDescription("description");
                x.SetDisplayName("display-name");
                x.SetServiceName("servicename");
            });

I have updated Topshelf version from v3.0.2.0b3fd3 to v3.3.154. I'm now getting a `Topshelf.HostConfigurationException`:

```
Topshelf.HostFactory Error: 0 : The service terminated abnormally, Topshelf.HostConfigurationException: The service was not properly configured: 
[Failure] Command Line An unknown command-line option was found: DEFINE: role = TestExecution
[Failure] Command Line An unknown command-line option was found: DEFINE: wexcommunication = 
[Failure] Command Line An unknown command-line option was found: ARGUMENT: _connectionid
[Success] Name irpfperfilesetl
[Success] DisplayName display-name
[Success] Description description
[Success] ServiceName servicename
   en Topshelf.Configurators.ValidateConfigurationResult.CompileResults(IEnumerable`1 results)
   en Topshelf.HostFactory.New(Action`1 configureCallback)
   en Topshelf.HostFactory.Run(Action`1 configureCallback)
```

**Comment by TravisTheTechie** [comment]
This isn't really a use case we support because we look at the process for the command line. This isn't the best behavior but not something I think we'll fix in the short term.
