### ISSUE TITLE
Cannot start app in console mode if service is running (different location)

### ISSUE THREAD

**Issue by thnk2wn** [Topshelf/Topshelf#274]
On our app server we have an app that exists in two subfolders, Dev and QA. 

The QA instance is installed and run only as a Windows Service. 

The Dev instance is intended to be run on demand as a console app only when needed.

The problem is when running the Dev instance TopShelf gives us this problem:

    MyServiceName service is running and must be stopped before running via the console

I could see that being okay if the path was the same for the service and the console app but they are two different folders, instances and configurations. I don't see any problem with them both being run when they are different instances and locations; seems TopShelf should let me.

**Comment by phatboyg** [comment]
You can use the _instance_ name parameter to change the instance name for the development instance. Check the help text to see the argument syntax.

**Comment by dabster** [comment]
You can change the service name when you call HostFactory.Run using a configuration setting that changes per build configuration for QA or Dev.

c.SetServiceName(Properties.Settings.Default.ServiceName);
