### ISSUE TITLE
ConstructUsing in Show me the code not appear in intellisense

### ISSUE THREAD

**Issue by arisliang** [Topshelf/Topshelf#275]
In Project tutorial Show me the code example (https://topshelf.readthedocs.org/en/latest/configuration/quickstart.html),

//3
s.ConstructUsing doesn't appear in intellisense, which is confusing, especially it's a tutorial on project site itself.

How can I make the intellisense work?

**Comment by TravisTheTechie** [comment]
Does `HostFactory.Run` or `x.Service<>` show up in Intellisense? The first thing to check would be that Topshelf NuGet package is installed and that `using Topshelf;` is included at the top of your file.

**Comment by phatboyg** [comment]
And that you aren't using the .NET Client library (in other words, using the full runtime).

**Comment by arisliang** [comment]
HostFactory.Run and x.Service<> do show up in intellisense.
I created fresh console app, installed Topshelf via nuget, and included using Topshelf.
The only thing that doesn't show up is s.* methods.
Despite it doesn't show up, the project compiled. And once it's compiled, the s.* methods all show up. If type myself, it doesn't show up.

The target framework is .net framework 4.

**Comment by TravisTheTechie** [comment]
If it compiles, then the code is all there and I guess it's a VS issue. Are you using any add-ons like Resharper?
