### ISSUE TITLE
Stop/ Uninstall doesn't wait for the service to stop

### ISSUE THREAD

**Issue by mjdaly** [Topshelf/Topshelf#276]
If a service is running and any of the following commands are run:
1. TopShelfService.exe stop
2. TopShelfService.exe uninstall

The service may take more than 30 seconds to stop, but the command will just continue to run after this timeout.

This can result in the uninstall process creating a state of corruption, where dependencies are unregistered and further commands issued when the service has not been uninstalled.

Can you add a wait option (with optional timeout) to these command switches so it's possible to reliably know when the service has been stopped before proceeding?

**Comment by TravisTheTechie** [comment]
I haven't revisited this in a Windows version or two, but at the time the answer was "nope." The Service Control Manager incorrectly reported the service was done even though files were in use and process still running. I just ended up putting sleeps in my deploy scripts to solve this. If you figure out how to get the SCM to properly report the status of the service, it would be brilliant to have this working right.

**Comment by mjdaly** [comment]
I came across a way that powershell does it, which is .NET code, therefore easily decompiled into readable code.

**The Powershell Way**
```
$s = Get-Service "ServiceName"
$s.WaitForStatus('Stopped')
```

Powershell `Get-Service` returns a `ServiceController`, which has the WaitForStatus method.

You can see the powershell `GetServiceCommand` implementation in Microsoft.PowerShell.Commands.Management.dll

I have verified the WaitForStatus method works when testing on a service with an artificially long, blocking, stop method. Whereas running stop through the (topshelf) service.exe exits prematurely.

**Comment by phatboyg** [comment]
It's certainly possible to add a flag to configure the wait time for the service to stop. That's part of the API, just isn't supported by Topshelf yet.

**Comment by silentnightwalk** [comment]
looking forward to 
`MyService.exe stop uninstall`

**Comment by jesseik** [comment]
Any news regarding this idea? Struggling with my uninstallation script. Application dll's still being in use after
`MyService.exe uninstall`

**Comment by DanWallaceAdslot** [comment]
I would also like an update on this if possible, a lot of our deployments have been getting stuck lately because of it

**Comment by GoaKoala** [comment]
Also hit this problem and deployments kept failing. We found out a workaround by checking the service status in the AfterUninstall. 
In the setup;
` HostFactory.Run( host => {
       
        // ... other init code ....
		
        string serviceName = "SomeService" 
		host.AfterUninstall(
                    () =>
                        {
                            try
                            {
				    int retryCount = 20;
                                int i = 0;
                                while (i < retryCount)
                                {
				        // If no exception thrown here it means service still exists
                                    using (ServiceController sc = new ServiceController(serviceName))
                                    {                                                                           
					    logger.Info($"Service still exists:{sc.Status} Wait and retry...");
                                        Thread.Sleep(2000);
                                        i++;
                                    }
                                }
                            }
                            catch (InvalidOperationException ex)
                            {
				    // Exception thrown. Service is not found, it is removed.
                                logger.Info($"No Service. Remove complete.");
                            }
                 });
       });`

It retries 20 times with 2000ms between retries to get the status of the service. If you can get it, it means service does still exist. When it throws an exception it means service is removed. Managed to fix our build this way.

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
