### ISSUE TITLE
Precise identification of changeset for NuGet package versions.

### ISSUE THREAD

**Issue by f-camera** [Topshelf/Topshelf#279]
Hi,
could you please help me identify the exact sources for NuGet package [version 3.1.3](https://www.nuget.org/packages/Topshelf/3.1.3)?
I could not find them in "[releases](https://github.com/Topshelf/Topshelf/releases)" view.

Thank you.

**Comment by TravisTheTechie** [comment]
It looks like @phatboyg didn't tag that release. You can look at the history of .semver and find when it changed to that specific version to get a good idea.
