### ISSUE TITLE
Not creating Event Source during install causing issues

### ISSUE THREAD

**Issue by mikesigs** [Topshelf/Topshelf#280]
A [recent change](https://github.com/Topshelf/Topshelf/blob/201c4303a203fc513783da9854e217089154582e/src/Topshelf/Runtime/Windows/HostServiceInstaller.cs#L92) to the HostServiceInstaller seems to have broken the services ability to write to the EventLog.

I thought that calling `DependsOnEventLog()` would force this, but that's not the case. All that does is tell the installer that the EventLog service must be running or it will fail to install the service. 

The problem I'm having is, since the EventSource isn't created by the Installer (which runs as admin) I get a SecurityException if I try to use `EventLog.SourceExists()` or `EventLog.CreateEventSource()` anywhere in my application code. That is unless I decide to run the service using `RunAsLocalSystem()`, which has the necessary permissions to create new EventSources. But both LocalService and NetworkService do not have that permission. But in the majority of cases people aren't going to want to run their service as LocalSystem, which is way too permissive.

This is why it's helpful to create the EventSource during installation when we can guarantee Admin rights are available.

Can we discuss some options here? I'm not entirely clear why the change was made to not auto-create the EventLog Source during installation. The comments indicate that "an ArgumentException is thrown when the first 8 characters of logName match the first 8 characters of an existing event log name". Could we make the EventLog name configurable by the HostFactory? Could we handle the ArgumentException and append something to the EventLog name to make it unique?

Your thoughts are most welcome. Thanks!

**Comment by mikesigs** [comment]
Or how about simply adding a `DoNotCreateEventLogSource()` option in the HostFactory?

**Comment by mikesigs** [comment]
My current work around for this is to just create the EventSource myself in `Program.Main()`.

```
static void Main(string[] args)
{
    CreateEventLogSource();
    var host = HostFactory.Run(x => /* ... */);
}

private static void CreateEventLogSource()
{
    // TopShelf no longer does this for us. https://github.com/Topshelf/Topshelf/issues/280
    if (!EventLog.SourceExists(Properties.Settings.Default.WindowsServiceName))
    {
        Logger.Info("Creating EventSource {0}", Properties.Settings.Default.WindowsServiceName);
        EventLog.CreateEventSource(Properties.Settings.Default.WindowsServiceName, "Application");
    }
}
```

**Comment by mac2000** [comment]
Or even better, if I declare that my service is depend on eventlog then eventlog installar probably should not be removed

**Comment by mac2000** [comment]
In addition to @mikesigs  workaround, here is how we can use assembly info:

```csharp
public static void Main(string[] args)
{
	HostFactory.Run(conf => conf
			.Service(settings => new Service(settings))
			.RunAsNetworkService()
			.StartAutomatically()
			.DependsOnEventLog()
			.BeforeInstall((settings) =>
			{
				if (!EventLog.SourceExists(settings.ServiceName))
				{
					EventLog.CreateEventSource(settings.ServiceName, "Application");
				}
			})
			.UseAssemblyInfoForServiceInfo());
}
```

The trick here is that in order to install service you must run install command from elevated prompt, so it seems that it is perfect time and place to register event sources

**Comment by endrig0** [comment]
This is quite old and does not seem to have a solution. Any updates that can be shared?

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
