### ISSUE TITLE
Command-line not working on windows 10

### ISSUE THREAD

**Issue by son1k** [Topshelf/Topshelf#283]
Hi, I create a bunch of topshelf services and the command-line always work fine, but since I instal windows 10 in my machine I couldn't install any service.
I can debug as console but even run from .exe is not working.
Yesterday I try to install the same services in windows 8 and today in windows server 2012 and the install is working fine.

**Comment by TravisTheTechie** [comment]
We'll need a little more information to be able help here. if you have logs of the failure or something then that would be helpful. I've ran services on Windows 10, so it's not specifically something Windows 10 related to Topshelf.
