### ISSUE TITLE
Installing against UserName with blank Password

### ISSUE THREAD

**Issue by ianbattersby** [Topshelf/Topshelf#285]
I hit a scenario today where I needed to install against a UserName that didn't have a password. Although this is likely an edge case it is a theoretically possible scenario. With `SC.exe` you can do the same by omitting the `Password= <password` parameter completely.

I wondered in the case of TopShelf if merely specifying the password parameter as blank would be sufficient from a validation point of view? This would allow it to provide some level of helpful validation in that - if the `password` option is omitted when the `username` isn't - it errors.

`myTopShelf.exe install -username:".\SomeUser" -password:""`

At a guess it might be as simple as this, which I can provide a PR w/tests/etc if you agree:
```
diff --git a/src/Topshelf/Configuration/HostConfigurators/RunAsUserHostConfigurator.cs b/src/Topshelf/Configuration/HostConfigurators/RunAsUserHostConfigurator.cs
index 25317dc..6359a5b 100644
--- a/src/Topshelf/Configuration/HostConfigurators/RunAsUserHostConfigurator.cs
+++ b/src/Topshelf/Configuration/HostConfigurators/RunAsUserHostConfigurator.cs
@@ -45,7 +45,7 @@ namespace Topshelf.HostConfigurators
         {
             if (string.IsNullOrEmpty(Username))
                 yield return this.Failure("Username", "must be specified for a User account type");
-            if (string.IsNullOrEmpty(Password))
+            if (Password == null)
                 yield return this.Failure("Password", "must be specified for a User account type");
         }
     }
```

**Comment by TravisTheTechie** [comment]
Could you include a unit test covering this behaviour? While it's an edge case, I think `-password:""` makes sense as something we should support. 

I'd remind you that having an account without a password in production is a bad idea from a security standpoint but I can see this happening in dev and test environments enough that it's worth supporting.

**Comment by ianbattersby** [comment]
Sure thing, leave it with me.

And yes, you'll get no argument from me there :-)

**Comment by ianbattersby** [comment]
Out of curiosity do you have any roadmap/schedule for releases to nuget?

**Comment by TravisTheTechie** [comment]
This is the only thing on the board to be released at the moment. @phatboyg is working up on a 4.0 release to drop support for older .NET versions, so as of right now that would be the next package for it. It's a simple change, so it's not impossible to cut a new 3.x release with just this change though, if you feel like you need it.
