### ISSUE TITLE
No support for .NET 4.5+ ?

### ISSUE THREAD

**Issue by chazt3n** [Topshelf/Topshelf#291]

**Comment by chazt3n** [comment]
![image](https://cloud.githubusercontent.com/assets/3843179/15017726/6321a834-11dc-11e6-9b2e-d7b247ae01e1.png)

**Comment by TravisTheTechie** [comment]
4.5 is no longer a supported version: https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/

You can continue to use 3.x versions of Topshelf if you must target older versions of the .NET framework.

**Comment by phatboyg** [comment]
Correct, 4.5.2 (and newer) is the only supported version of the .NET framework. Even Microsoft no longer supports the previous versions.

**Comment by chazt3n** [comment]
Good point, ok thank you @phatboyg

**Comment by crazycoder84** [comment]
You may need to install 3.3.1 version of Topshelf to get it running on 4.5.1. I had the same issue but it worked when i downgraded the Topshelf version. You may have to give up on some latest features though.
