### ISSUE TITLE
Multiple Instances of Topshelf

### ISSUE THREAD

**Issue by aai2on** [Topshelf/Topshelf#296]
I would like to have multiple Services that are running TopShelf.  Just need clarification on the no multiple for TopShelf services.  Haven't been able to find a good explanation.  I would like to have 3 services that are each started with TopShelf.  But, getting odd performance at times.  So, can I have just one service running TopShelf or can I have multiple services that each start with TopShelf and are single threaded????  Thanks for any help.
## ONE SERVICE ONE TOPSHELF

or is it

---

FIRST SERVICE WITH TOPSHELF
##

**Comment by IanYates** [comment]
Look at it from this point of view

You're an ISV and ship a service using Topshelf

Your customer has some other software which has a background service using Topshelf.

They coexist - it'd be crazy if they didn't :)

Topshelf is a helper library to register a Windows service and let the Windows services stuff run your code.  It doesn't exist as a separate entity on the end-user's system.  That is, it's not like FireDaemon.

A while ago Topshelf (before I ever used it in anger) had the capability to automatically load (and even reload) assemblies that you put into a subfolder.  That follows your "one service one topshelf" comment.  That isn't available anymore as it was problematic.

So you have 1x Windows service == 1x assembly of yours referencing the Topshelf library.

**Comment by tigerclawn82** [comment]
Hi,
    I have created a Windows Service with topshelf, is there any problem if i install this windows service multiple times on single machine with different Service Name? I have created copies of windows service in multiple folders and each copy has its unique Service Name and i can install windows service but guide says
```
You can only have ONE service! As of 3.x Topshelf the base product no longer support hosting multiple services. This was done because the code to implement was very brittle and hard to debug. We have opted for a simpler and cleaner base product. This feature will most likely come back in the form of an add on nuget.
```
is there anything i am missing? Also, what is the difference between SetInstanceName and SetServiceName?

Thanks

**Comment by phatboyg** [comment]
InstanceName is appended to the service name to allow multiple instances of the same service to run on the same machine.

> The ONE service comment is related to an obsolete feature of 2.x that allows multiple services to be hosted in the same _process_. That's long dead, thankfully.

**Comment by janus007** [comment]
As a new user to Topshelf this question struck me as well. 
I believe the documentation is a bit unclear, it would be nice to update the documentation to reflect this :)
