### ISSUE TITLE
how to use NLog or Log4Net by configuration file?

### ISSUE THREAD

**Issue by StevenFlyover** [Topshelf/Topshelf#298]
i wonder to know how to use NLog or Log4Net by configuration file? not used UseNLog() or UseLog4Net.

**Comment by aai2on** [comment]
Seems like this is the wrong area to ask this.

**Comment by phatboyg** [comment]
Yeah, there are good examples out there of how to use it.

https://github.com/Topshelf/Topshelf/blob/develop/src/SampleTopshelfService/Program.cs#L24
