### ISSUE TITLE
Unable to install Nuget package on Visual Studio 2013 Ultimate due to nuget package not being compatible with plain old .NET 4.0

### ISSUE THREAD

**Issue by duaneking** [Topshelf/Topshelf#300]
I just tried to install Topshelf into a new project and it refused to install stating that its bound to a version of .Net that the just created project is not compatible with.  It gives me .NET version 4.5.2 as its minimal required version. I can change the project version - and have - but I know from prior painful experience that this can create issues down the line in regards to testing, external libs, etc.

Was this a mistake on your side? The documentation states that .Net 3.5 is all that is needed.  Are the docs incorrect?  If so that makes topshelf much less usable in enterprise environments, so I hope not.

**Comment by phatboyg** [comment]
Topshelf v4 is only compatible with the currently supported version of .NET, which is 4.5.2.

If you need to use an earlier version, use the most recent 3.x release.

**Comment by Tommixoft** [comment]
so topshelf isno longer XP/server 2003 compatible..sad.

**Comment by phatboyg** [comment]
You can always use the v3 packages with earlier versions of .NET.

Eventually you have to drop support for the old stuff, or it makes the project too complicated and fractured.

**Comment by Tommixoft** [comment]
anyways your plugin rocks! :) so easy to use. hated MS approach.
