### ISSUE TITLE
Install as a 64 Bit Service

### ISSUE THREAD

**Issue by fungus1487** [Topshelf/Topshelf#301]
Hi, we have been using Topshelf 3.3.1 and recently due to increased activity noticed OutOfMemory Exceptions taking place. This has led to some bugs being caught but also we noticed that TopShelf runs as a 32 bit service. From the documentation I can't see how we force it to install as a 64 bit service, is this supported?

**Comment by phatboyg** [comment]
That's entirely based on how you create your console application. If your console application is a 64-bit process, it will run the service as a 64-bit process. Topshelf is just an assembly that supports AnyCPU.

Check your build configurations and make sure you're building a 64-bit exe from Visual Studio.

> I verified that our services are indeed built and running as 64-bit, so it's likely your project settings.

**Comment by fungus1487** [comment]
Yes thanks for the clarification, I resolved this a few hours ago with a build target.

Thanks again, working as expected.

Just a comment but it would be nice to hint at it in the documentation, it's probably clear to most :) but it was the first place I checked.

Thanks again.
