### ISSUE TITLE
Can't catch unhandled exceptions

### ISSUE THREAD

**Issue by gthvidsten** [Topshelf/Topshelf#306]
I can't catch unhandled exceptions from the service being started.
Try/catch around `HostFactory.Run()` doesn't make any difference, neither does adding try/catch inside any of the actions.

As far as I've been able to read from the source it is because TopShelf catches any unhandled exceptions on its own and writes the exception to the console.

Most of the times that would be okay, but in some cases there are details in the exception that are not included in the exception printout (like LoaderException if you're working with MEF).

Are there any shortcut that makes it possible to catch any unhandled exceptions outside of TopShelf?

Tested on 3.1.3, 3.3.1 and 4.0.1.

**Comment by TravisTheTechie** [comment]
There isn't really a great way to support this currently. You could write a PR to expose an additional handler for unhandled exceptions though.

**Comment by sstorie** [comment]
Please see this PR and let me know your thoughts :)

https://github.com/Topshelf/Topshelf/pull/311

**Comment by jackjwilliams** [comment]
I'm wondering if this might help me. Currently, when I Start the service from the list of Services, it always times out and fails (Error 1053: The service did not respond to the start or control request in a timely fashion). No exceptions. No logs of anything, it's very hard to tell why. 

If I run the exe from the command line - all is well (I can verify it runs fine).

**Comment by LarsKemmann** [comment]
I think PR #311 resolved this -- this issue should be closed. :)
