### ISSUE TITLE
Topshelf debug with Paket

### ISSUE THREAD

**Issue by tigerclawn82** [Topshelf/Topshelf#310]
Hi,
   I initially installed Topshelf 3.3.1 via Paket and reference was all good and was able to build. When i tried to debug, i was able to successfully be in HostFactory.Run but it wasn't going in Start/Stop methods.

Then i added same version via Nuget and then i was able to Debug as usual.  Is there anything i am missing or something particular?

Thanks

**Comment by TravisTheTechie** [comment]
I don't use Paket for anything so I'm not sure 100% sure, but I'm not aware of anything specific you should need to do. This seems more like an IDE / debugger issue.

**Comment by tigerclawn82** [comment]
Hi, this was a bug in Paket and it has been fixed.
https://github.com/fsprojects/Paket/issues/1830
