### ISSUE TITLE
Topshelf v5 overview

### ISSUE THREAD

**Issue by TravisTheTechie** [Topshelf/Topshelf#315]
I think it's about time to push towards a v5 of Topshelf. A couple of things are still awkward because of the attempts at hosting multiple things in v2 and .NET Core support is out of the question until more Windows specific things are supported. I think a few major things need to happen...
- Make Topshelf more modular -- all hosts except the Console host need to be pulled in via Nuget packages
- Support .NET Core for the core Topshelf assembly, and all assimbles that can support that target
- Command line handling can be more robust, and be handled without access to the environment by requiring it passed in
- Force a single logical server in the host, e.g. `HostFactory<MyService>.Run(x => {...});` lifting up some of the configuration
- Ignore unknown command line args; just pass them onto the host in question to handle
- Add a Topshelf.WindowsServiceHost package for non-.NET Core stuff
- Add a Topshelf.LaunchdHost for macOS
- Add a Topshelf.SysVInitHost ?
- Add a Topshelf.UpstartHost ?
- Add migration documentation
- Update existing documentation for all the changes

So thoughts of anything that should be considered in this? Anything I'm missing before diving in?

**Comment by phatboyg** [comment]
I like the ideas, makes total sense. 

Launchdhost? Why not just `Topshelf.Mac` to avoid being fancy?

Topshelf.Windows (auto-includes Topshelf, so still an easy add for a windows service).
(not sure how this conflicts with .Core, etc.)


Just thinking out loud...

**Comment by drusellers** [comment]
This seems really strong. I'm thinking that passing in the args to the various service methods (start / stop / create) would be a great way to let others deal with them.

**Comment by TravisTheTechie** [comment]
`Topshelf.macOS` might make more sense. The underlying use of Launchd is less important. However, supporting Linux is a lot more complicated. SysVInit vs upstart vs systemd. Maybe just leave the Linux problem to someone who wants to tackle it. 

`Topshelf.Windows` could auto include Topshelf as a dependency I think? But the core Topshelf would target .NET Core and you would need a full profile .NET version for Topshelf.Windows -- since they aren't targeting everything we need for Core. Would need to play with this a bit to figure out the right way to handle it. Might poke some of the folks at MS for additional thoughts too.

**Comment by TravisTheTechie** [comment]
https://github.com/Topshelf/Topshelf/compare/v5 got `Topshelf.dll` and `TopshelfSampleService` building on Mac. Tossed a ton of stuff into `Topshelf.Windows` without any structure. A lot left still to do.

**Comment by TravisTheTechie** [comment]
https://github.com/Topshelf/Topshelf/compare/v5

**Comment by eman1986** [comment]
when will this be available? Looking to convert a legacy app to .NET Core

**Comment by TravisTheTechie** [comment]
When the APIs we need are available and the tooling is stable we can start on it.

**Comment by Adilsh4uk** [comment]
.NET Core now has a [systemd implementation](https://devblogs.microsoft.com/dotnet/net-core-and-systemd/).

**Comment by phatboyg** [comment]
Yet another reason why Topshelf isn't needed w/ .NET Core.
