### ISSUE TITLE
Too much overhead

### ISSUE THREAD

**Issue by randyriegel** [Topshelf/Topshelf#316]
I've had my own windows debbugable serverice forever.   And can install it to services using "myprogamname -install".   It's like 500 hundred lines of code if that.   No lambdas to configure (it does this when you create the project according to what you type into VS).   Your making simple things seem hard so people want it.  It's save a a VS project template so just start coding.

**Comment by phatboyg** [comment]
Is there an ask here, or are you just ranting?
