### ISSUE TITLE
Add timeout before stoping windows service that is hosted by topshelf

### ISSUE THREAD

**Issue by aviran05** [Topshelf/Topshelf#317]
I wondered if there is a way to set a timeout when stopping the service to enable on-going process that the service is currently handling to finish before the service actually closes? I want to wait X seconds before I terminate the Top-Shelf.

This is my console which I have installed as a service:

```
static int Main(string[] args)
{
    return (int)HostFactory.Run(x =>
    {
        string serviceName = new ServiceNameResolverImpl().GetServiceName();
        x.SetServiceName(serviceName);
        x.SetDisplayName(serviceName);
        x.SetDescription(serviceName);

        x.UseAssemblyInfoForServiceInfo();
        x.RunAsLocalSystem();
        x.StartAutomaticallyDelayed();
        x.SetStartTimeout(TimeSpan.FromMinutes(1));
        x.Service<ServiceImpl>();
    });
}
```

Thanks!

**Comment by TravisTheTechie** [comment]
There is a way to require more time from the Windows SCM subsystem, but I don't believe we expose it anywhere. This shouldn't be a huge deal to add.

**Comment by aviran05** [comment]
Thanks I'll check it out

**Comment by ushenkodmitry** [comment]
Hm, I thought HostControl.RequestAdditionalTime does the trick!
