### ISSUE TITLE
Application exits before custom Unhandled Exception handler is called.

### ISSUE THREAD

**Issue by niemyjski** [Topshelf/Topshelf#318]
Topshelf wires up to the application unhandled exception handler and immediately shuts down. This prevents my handlers from running (error reporting: https://github.com/exceptionless/Exceptionless.net)

https://github.com/Topshelf/Topshelf/pull/311#issuecomment-240413071

**Comment by TravisTheTechie** [comment]
To be clear, what you would like is that all UnhandledException handlers are executed, then the service shuts down? 

I'm not sure we can do that. The point is that we call shutdown so any resources can clean up correctly and not have a things just end when their threads are terminated. We just added a hook to allow you to react to our UnhandledException event, would that be sufficient for integration?

We could also talking about adding other behaviors to that event. Maybe "terminate on unhandled exception" or something. Default behavior shouldn't change though, so integration would still require flipping some bits.

**Comment by niemyjski** [comment]
@TravisTheTechie yes, but ideally the service should't be shutdown. I don't think a library should ever interfere with workflow (let the process crash). At exceptionless, we never interfere with the existing workflows, we log and let it continue. If the process or service is about to die, I'm curious about which resources you may want to cleanup?

That wouldn't be sufficient, because you are now taking every app/lib that uses those handlers and now expect them to use your callback.

**Comment by gab** [comment]
I've commented on this in the past... I strongly agree that Shutdown() shouldn't be called if you catch an unhandled exception. The process is crashing down and is in an unknown state, the correct behavior is just to do the minimum i.e. log the exception and let the process crash normally. As a bonus you'll get the stack trace in the Windows Event Log.

The way you're doing it now, users are gonna wire up their regular shutdown code to your Shutdown() method, expecting it to be called whenever the service is stopped normally, for instance with NET STOP. But you trigger their same regular shutdown code when everything is crashing down! Once again, the correct behavior in this case is to do nothing: let things crash, and allow the app's author to catch unhandled exceptions if he wants to. Or if you absolutely insist on handling this, at least call something else than Shutdown(), like OnCrash(). But that's bad software design and it just defeats the point of having exceptions.

**Comment by TravisTheTechie** [comment]
I acknowledge and understand you point @gab, though I do disagree with a couple of your points. I'm not sure this is a behavior I will change at this point, at least without a major version tick. Even then I'm not convinced this is exactly the right behavior. I believe the changes suggested in use via #337 are a better solution than just crashing without the chance to recover at this point. 

And closing this since #311 was pulled.
