### ISSUE TITLE
Log4Net BufferedAppender causes Topshelf to hang on start as service

### ISSUE THREAD

**Issue by rhessinger** [Topshelf/Topshelf#321]
I have a custom Log4net Appender that implements the BufferedAppender.  When you have more log statements than the BufferSize, It will cause Topshelf to hang.  I cannot have UseLog4Net enabled because my BufferSize is 5.  It seems to hang when the buffer flushes.  It also never finishes flushing the log4net buffer.  

Once the service is started, then logging is no longer an issue and the buffer flushes appropriately.

**Comment by TravisTheTechie** [comment]
I'm not sure what's going on here -- do you setup the appender and log4net prior to calling any of the Topshelf APIs?

**Comment by rhessinger** [comment]
Yes. We configure log4net with a buffered appender prior to calling
topshelf so I can log all of the startup messages.  We also use the log4net
topshelf add-in to log all of topshelf's messages to log4net.

**Comment by TravisTheTechie** [comment]
We don't do anything obvious that should effect this. Does this still happen if you have a minor sleep after initialization of your buffered appender and before starting up? I don't believe there's a default buffered appender to test with, which would show if this is a limitation of your appender or of buffered appenders in general. 

I think without a reproducible example I'm unlikely to be able to help. It will likely be within your appender somewhere, but if you can narrow down a specific thing that's causing things to jam up we can look at resolving that.

**Comment by rhessinger** [comment]
Thanks for the help. So far if i can prevent the buffered appender from
flushing until after startup it works fine. I also notice this more on
server 2008 r2 than 2012 r2.  I can create a reproducible project of this.
In log4net, the SQL appender is a buffered appender.

**Comment by TravisTheTechie** [comment]
Closing until we have a reproduction of the problem.
