### ISSUE TITLE
TopShelf not installing service

### ISSUE THREAD

**Issue by nathvi** [Topshelf/Topshelf#322]
I have this code, that when I run, the console says "Configuration Result:
[Success] Name Stuff, [Success] Description Sample Topshelf Host, [Success] ServiceName Stuff
Topshelf v4.0.0.0, .NET Framework v4.0.30319.42000
Doing stuff
Service started
The Stuff service is now running, press Control+C to exit."

So I went looking for a service named "Stuff" inside the service manager, while the console window was still up. Didn't find anything. What am I doing wrong?
[Problem Code.txt](https://github.com/Topshelf/Topshelf/files/448181/Problem.Code.txt)

**Comment by phatboyg** [comment]
try: `yourservice.exe install`

It looks like above you just ran the service, which defaults to console mode for debug/testing.

**Comment by nathvi** [comment]
Haha... yep. That was it.
