### ISSUE TITLE
How to set service recovery on second and and subsequent failure?

### ISSUE THREAD

**Issue by Sergey-Terekhin** [Topshelf/Topshelf#324]
Hi, 
I use following service recovery configuration:

``` C#
cfg.EnableServiceRecovery(r =>
{
         r.RestartService(1);
         r.OnCrashOnly();
});
```

And it configures service parameters as shown on picture:
![2016-09-02 09 37 33](https://cloud.githubusercontent.com/assets/5369802/18194893/741c9148-70f1-11e6-8b3e-7a5683b7e0b3.png)

Is it possible to set auto restart service on second and subsequent failures?

I use Topshelf 3.3.154.0

**Comment by phatboyg** [comment]
Yes, just add more recovery actions, in the order in which you want them applied.
