### ISSUE TITLE
No "OnException" method available. Version 4.0.1

### ISSUE THREAD

**Issue by Sharpiro** [Topshelf/Topshelf#325]
```
HostFactory.New(x =>
{
    x.OnException(ex =>
    {
        // Do something with the exception
    });
});
```

The above line comes from the topshelf documentation, but it seems to be unavailable in the version I am using. 

Is there a new method for handling exceptions?

**Comment by phatboyg** [comment]
It's there, as shown in this unit test:

https://github.com/Topshelf/Topshelf/blob/develop/src/Topshelf.Tests/ExceptionHandler_Specs.cs#L37

**Comment by awseward** [comment]
I also seem to be missing this callback using the NuGet package for `4.0.1`.

[It looks like the `HostConfigurator` interface is missing the `OnException` message here...](https://github.com/Topshelf/Topshelf/blob/7e64a47cd1d725806cee9b077c0222e95f14994a/src/Topshelf/Configuration/HostConfigurators/HostConfigurator.cs)
(I'm not 100% sure if that's the correct commit at which to search the codebase. I didn't find a `4.0.1` tag, so I just assumed the commit that changed `SolutionVersion.cs` would be a safe one to guess)

[It looks to be there in the `develop` branch, though.](https://github.com/Topshelf/Topshelf/blob/develop/src/Topshelf/Configuration/HostConfigurators/HostConfigurator.cs#L127)

Maybe it's just a question of waiting for the next nupkg to be released and pushed to nuget.org, then...?

**Comment by phatboyg** [comment]
Yeah, it hasn't been released yet. I'll work with @TravisTheTechie to get an updated NuGet released.

**Comment by Sharpiro** [comment]
FYI, 4.0.1 isn't listed as pre-release

**Comment by awseward** [comment]
Sounds great. I'm really looking forward to being able to use `OnException` :)

For what it's worth, it might be helpful to put a note in the documentation specifying that it's generated from `develop`, and that because of that, the documentation may be ahead of the latest available NuGet package.

Had me a little puzzled for a minute before I looked into it ¯\\\_(ツ)_/¯

**Comment by thj-dk** [comment]
When can we expect an updated NuGet package @phatboyg?

**Comment by phatboyg** [comment]
What does @TravisTheTechie think - he's been managing the pull requests lately. I can do a 4.0.1 anytime, just give me the signal.

**Comment by TravisTheTechie** [comment]
You can ship a v4.0.1 -- I haven't setup a working VM to build a release. I
should do that.
-- 
-Travis

**Comment by phatboyg** [comment]
Done. 4.0.2 though.

**Comment by thj-dk** [comment]
Thanks alot!
