### ISSUE TITLE
System.OutOfMemoryException in Topshelf

### ISSUE THREAD

**Issue by chenzuo** [Topshelf/Topshelf#326]
2016-09-13 00:13:50.6345|F ConsoleRunHost The service threw an unhandled exception System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 NLog.Targets.Wrappers.AsyncRequestQueue.DequeueBatch(Int32 count)
   在 NLog.Targets.Wrappers.AsyncTargetWrapper.ProcessPendingEvents(Object state)
   在 System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.TimerQueueTimer.CallCallback()
   在 System.Threading.TimerQueueTimer.Fire()
   在 System.Threading.TimerQueue.FireNextTimers()
   在 System.Threading.TimerQueue.AppDomainTimerCallback()

**Comment by RonaldMariah** [comment]
I'm experiencing this same issue. Was there a solution to this?
