### ISSUE TITLE
4.0.2 version, it cannot be referenced。

### ISSUE THREAD

**Issue by aehyok** [Topshelf/Topshelf#328]
[http://images2015.cnblogs.com/blog/401119/201609/401119-20160921102113106-971893710.png](http://images2015.cnblogs.com/blog/401119/201609/401119-20160921102113106-971893710.png)

**Comment by NKnusperer** [comment]
Looks like you're trying to reference Topshelf in a Net v4.0 project but the current NuGet package requires you to have a v4.5.2 project. Changing the target framework on your project to v4.5.2 should do the trick.

Anyway I'am a bit confused too, http://docs.topshelf-project.com/en/latest/installation/prerequisites.html says v.3.5 SP1 and v4.0 are supported but the readme.md only talks about v4.5.2.
Maybe a project member can clarify this?

**Comment by phatboyg** [comment]
Since Topshelf v4, .NET 4.5.2 is required. For previous versions of .NET, using Topshelf v3.

**Comment by aehyok** [comment]
ok,thanks @NKnusperer and @phatboyg。
