### ISSUE TITLE
Start() not being fired after start

### ISSUE THREAD

**Issue by diogoandrei** [Topshelf/Topshelf#335]
I'm facing a problem here, my service works fine if I run on debug or release, but when I try to install  and start via cmd the Start() method apparently is not being fired. Any thoughts? Thank you!

```csharp
Program.cs
HostFactory.Run(configurator =>
            {
                configurator.Service<MyService>(s =>
                {
                    s.ConstructUsing(name => new MyService());
                    s.WhenStarted(service => service.Start());
                    s.WhenStopped(service => service.Stop());
                });

                configurator.RunAsLocalSystem();
                configurator.StartAutomatically();
                configurator.SetDescription("MyService");
                configurator.SetDisplayName("MyService");
                configurator.SetServiceName("MyService");
            });
```

```csharp
MyService.cs

public bool Start()
        {
            var t = new Thread(new ThreadStart(Run));
            t.Start();

            return true;
        }

        public bool Stop()
        {
            return true;
        }

        private void Run()
        {
            while (true)
            {
                Logger.Info(interval.ToString());

                interval++;

                Thread.Sleep(1000);
            }
        }
```

**Comment by jagguk1993** [comment]
Hey,  I am also facing similar issue. I have my start method to open command line and execute some commands. But when I install service, nothing works. I think the same issue with mine the start action is not being fired. 
Somebody can help us ? Thanks in advance.

**Comment by diogoandrei** [comment]
I found the problem. My log class was writing in a file located in  %LOCALAPPDATA%. I changed to another folder and voilà, it's working! Maybe the service account do not have permission to create a folder/file in there?

**Comment by diogoandrei** [comment]
@jagguk1993 You can use [ProccessMonitor] (https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx) to check what your service is doing

**Comment by TravisTheTechie** [comment]
Looks like this is resolved then. Environment locations will change on the user; though we do set the current base path to location of the service.
