### ISSUE TITLE
How to hook to an already running instance of windows service using TopShelf

### ISSUE THREAD

**Issue by rawatn** [Topshelf/Topshelf#336]
I am looking for an option by which whenever I run my windows service through command line, it should first check if there is an already running instance for the same and then rather than starting a new process it should hook into the same process. Is it possible? I am using TopShelf for my win service.

**Comment by TravisTheTechie** [comment]
How would it hook into an existing service? What would it do instead of just letting the service run as is?

**Comment by enzoaeneas** [comment]
reopening this - one could signal the service to perform a stop or pause.
Or even pipe the output?
i am going to implement this in a service implementation base class myself
