### ISSUE TITLE
TopShelf installs a service with an ImagePath that has a different command line syntax than TopShelf itself

### ISSUE THREAD

**Issue by basbossink** [Topshelf/Topshelf#338]
I noticed there is already an issue regarding the unclarity surrounding multiple service installed using the same executable.  As many I'm trying to create an executable using TopShelf that can be used to install and start multiple instances of the same service. The problem I have is that multiple instances of the same service can be installed by using e.g. `-servicename:fred01` and `-servicename:fred02` but when this is done there is no provision in TopShelf to get the currently 'running/starting' service name inside `Main`. Following this [SO answer](http://stackoverflow.com/questions/12494508/id-like-to-use-the-topshelf-instance-name-as-part-of-the-log4net-log-file-name) I've gone down the route of parsing the command line in `Main`. However the syntax of the command line parameters for the installed service is different from how the executable was invoked to install the service. For instance:

    > fred.exe install -servicename:fred01 --localservice
    > fred.exe install -servicename:fred02 --localservice

Leads to a registry entry like:

    ImagePath : "C:\fred.exe" -displayname "fred service" -servicename "fred01"

This means that when the command line received when fred.exe is run with the `run` verb is different from the command line when `fred.exe start -servicename:fred01` is executed. 

For consistency and easy parsing I would expect the value of `ImagePath` to be:

    ImagePath : "C:\fred.exe" "-servicename:fred01"

I view parsing the command line as a workaround for the fact that TopShelf has no other way to 'get' the servicename in `Main`. The use case here is to be able to configure log4net such that a separate file per service instance is used by doing something like:
     ...
                log4net.GlobalContext.Properties["LogName"] = serviceName;
    ...
 
and in the log4net config:

      <appender name="DebugLogFileAppender" type="log4net.Appender.RollingFileAppender">
    <param name="File" type="log4net.Util.PatternString" value="../Logs/%property{LogName}.Debug.log" />
    ...

**Comment by TravisTheTechie** [comment]
So let's make sure I understand the problem here -- you are parsing the command line and it differs when run as during install vs. service vs. command line, right?

**Comment by basbossink** [comment]
Yes. Since when the service starts the commandline arguments from the ImagePath registry entry are used I would expect that the syntax is the same as the syntax used for the `run` verb on the command line.

**Comment by TravisTheTechie** [comment]
Since there are multiple ways you can express these command line parameters, I believe this will be a "won't fix" problem. I see what you're saying, and how it's confusing. We just don't have a great answer for it and I don't think we will. I would blame it on how ImagePath works, but even then I bet we could have done better if we went back to the drawing board. It's just how things work and reworking it isn't an effort or a risk anyone is interested in at this time.
