### ISSUE TITLE
Topshelf FileSystemWatcher Stopping to watch folder directory (It goes in sleep or idle mode)

### ISSUE THREAD

**Issue by Suyog-Khandagale** [Topshelf/Topshelf#339]
Topshelf FileSystemWatcher stop watching on folder when works as windows service. It shows that service is running but internally it stops watching the folder directory.

We need to manually restart the service again perform the operation for copying the files to configured folder to watch again by FileSystemWatcher.

**Comment by phatboyg** [comment]
I don't think this is a Topshelf issue, it seems like an issue with the FileSystemWatcher.

**Comment by TravisTheTechie** [comment]
I feel like I had this problem with the FireSystemWatcher previously and even wrote a wrapper to restart the component when it failed. This isn't related to Topshelf at all.
