### ISSUE TITLE
No public installers found in the assembly Version 4.0.3

### ISSUE THREAD

**Issue by nathvi** [Topshelf/Topshelf#340]
My projects are running .NET Framework 4.5.2 on Windows 10.

Steps to reproduce problem: 
Create a console application. 

Download the Nuget Topshelf assembly version 4.0.3

Save the application.

Reopen visual studio 2015 in admin mode. 

Create service class, and plug into Topshelf HostFactory.

Compile sln in Release mode.

Run applicaiton, record the results of the console output.
    Console output is as follows "Configuration Result:
[Success] Name KeyTransfer, [Success] Description Transfer Service, [Success] ServiceName KeyTransfer
Topshelf v4.0.0.0, .NET Framework v4.0.30319.42000"
I assume this means that Topshelf worked... 

Open Developer Command Prompt for Visual Studio 2015, cd in.to release directory,
do a normal installutil install of the .exe file in this directory

I get back the following text from the installer, and the service is not installed
"No public installers with the RunInstallerAttribute.Yes attribute could be found in the C:\Users\UserName\Source\Workspaces\TransferSimulator.exe assembly."

Any help is appreciated.

**Comment by phatboyg** [comment]
You should use:

    service.exe install

Instead of using InstallUtil.

**Comment by nathvi** [comment]
I'll give it a try tomorrow. Thanks.

**Comment by nathvi** [comment]
I tried that using administrator rights with both the normal windows 10 command prompt, as well as the 
command prompt for visual studio 2015. All that happens is the program locks up and nothing happens. Do I need to install the "Install" command as a separate program?

**Comment by nathvi** [comment]
I'm assuming the install command is referenced at this url here,
http://docs.topshelf-project.com/en/latest/overview/commandline.html

I tried using the "help" and "-help" commands. Those don't work either. The cursor just goes to the next line in the cmd prompt and is blinking like it's waiting to do something. There's something seriously screwed up here.

**Comment by phatboyg** [comment]
I hate to say it but it's likely your code.

The only time your code should do anything is when Start is called. If you are doing anything outside of that, you're bring your behavior into Topshelf.

Look at the samples and you can see how they work just fine.

**Comment by nathvi** [comment]
I hate to say you're right. I didn't have the correct installer code wrapper around my code. Everything is fine, I'm just a doofus.
