### ISSUE TITLE
Add command line arguments to service startup parameters

### ISSUE THREAD

**Issue by duszekmestre** [Topshelf/Topshelf#341]
When installing service please add custom command line arguments to startup arguments.

**Comment by TravisTheTechie** [comment]
I don't have a way to clearly describe the behavior around this without leaving people confused. If you do `service.exe install blah-blah` then do `service.exe install oh-no` which one should be set on the ImagePath? 

I don't want to say this will never be delivered, but it's unlikely to happen. It will be confusing and just adding more support work for us. You are welcomed to fork and add that though. See #330 for more info.
