### ISSUE TITLE
Using Topshelf.Serilog and Serilog 2.x results in MethodMissingException

### ISSUE THREAD

**Issue by burgessl** [Topshelf/Topshelf#342]
If you use Topshelf.Serilog 4.0.3 and one of the 2.x Serilog versions (e.g 2.3.0) when you call UseSerilog(LoggerConfiguration) a MethodMissingException occurs.

Stacktrace:
'TopshelfTest.vshost.exe' (CLR v4.0.30319: TopshelfTest.vshost.exe): Loaded 'C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Cannot find or open the PDB file.
Topshelf.HostFactory Error: 0 : An exception occurred creating the host, System.MissingMethodException: Method not found: 'Serilog.ILogger Serilog.LoggerConfiguration.CreateLogger()'.
   at Topshelf.SerilogConfigurationExtensions.UseSerilog(HostConfigurator configurator, LoggerConfiguration loggerConfiguration)
   at TopshelfTest.Program.<>c__DisplayClass0_0.<Main>b__0(HostConfigurator x) in C:\Code\scratch\TopshelfTest\TopshelfTest\Program.cs:line 18
   at Topshelf.HostFactory.New(Action`1 configureCallback)

I suspect this is linked to the change in method signature that occured where the method now returns a concrete Logger not an ILogger (https://github.com/serilog/serilog/commit/459dffd1ead39ef0e07f95800927d12ee00a009f#diff-58f3d160d5748def4d4cb74a54e8d9be).

I suspect a new nuget package that supports explicitly Serilog 2.x is needed due to this breaking change.

We have been able to work around this by creating the logger and passing it in on the UseSerilog(ILogger) overload.

**Comment by skovsende** [comment]
Just had the same problem...
