### ISSUE TITLE
VB.NET

### ISSUE THREAD

**Issue by Osmosis311** [Topshelf/Topshelf#343]
Does Topshelf work with VB.NET?  If so, any code samples?

Thanks!

**Comment by NKnusperer** [comment]
To do so the Topshelf assemblies needs be marked as [CLS compliant](https://msdn.microsoft.com/en-us/library/system.clscompliantattribute(v=vs.110).aspx), this is currently not the case.
However I just tried adding `[assembly: CLSCompliant(true)]` to the [SolutionVersion.cs](https://github.com/Topshelf/Topshelf/blob/develop/src/SolutionVersion.cs)  and everything recompiled without additional warnings so you could build your own Topshelf version to use with VB.Net.
From there everything  works like the existing example, just do it in VB.Net syntax.

**Comment by ssta604** [comment]
You could do the reverse in AssemblyInfo.vb:
<Assembly: CLSCompliant(False)>

**Comment by Osmosis311** [comment]
I actually just added the reference and the sample code and it just,
worked, no modification as described here required...

**Comment by TravisTheTechie** [comment]
Yeah, it should work in VB.NET without any efforts. I don't have any samples because it hasn't really been a problem for anyone up to this point. Ideally the API will be discoverable in VB.NET as well. If you have a specific question here or the mailing list could answer.

**Comment by ayman-metwally-developer** [comment]
Greetings ... I appreciate your support here:

I've spent few hours tying to get a VB.NET simple program to rub with no success.
I'm using the standard example (TownCrier) .. The debugger is complaining about this sentence "x.Service" with the following error:

> BC30518	Overload resolution failed because no accessible 'Service' can be called with these arguments:
>     'Public Shared Overloads Function Service(Of TownCrier)(configurator As HostConfigurator, serviceFactory As Func(Of TownCrier)) As HostConfigurator': Type argument 'TownCrier' does not inherit from or implement the constraint type 'ServiceControl' .....

Here's the code:

> Public Class TownCrier
> 	ReadOnly _timer As Timer
> 	Public Sub New()
> 		_timer = New Timer(1000) With { _
> 			Key .AutoReset = True _
> 		}
> 		_timer.Elapsed += Function(sender, eventArgs) Console.WriteLine("It is {0} and all is well", DateTime.Now)
> 	End Sub
> 	Public Sub Start()
> 		_timer.Start()
> 	End Sub
> 	Public Sub [Stop]()
> 		_timer.[Stop]()
> 	End Sub
> End Class
> 
> Public Class Program
> 	Public Shared Sub Main()
> 		HostFactory.Run(Function(x) 
> 		'1
> 		x.Service(Of TownCrier)(Function(s) 
> 		'2
> 		s.ConstructUsing(Function(name) New TownCrier())
> 		'3
> 		s.WhenStarted(Function(tc) tc.Start())
> 		'4
> 			'5
> 		s.WhenStopped(Function(tc) tc.[Stop]())
> 
> End Function)
> 		x.RunAsLocalSystem()
> 		'6
> 		x.SetDescription("Sample Topshelf Host")
> 		'7
> 		x.SetDisplayName("Stuff")
> 		'8
> 			'9
> 		x.SetServiceName("Stuff")
> 
> End Function)
> 		'10
> 	End Sub
> End Class

**Comment by NKnusperer** [comment]
No idea how to inline the ServiceConfigurator delegate in VB.Net syntax, however this seems to work as expected:
```
Imports System.Timers
Imports Topshelf
Imports Topshelf.ServiceConfigurators

Public Class TownCrier
    ReadOnly _timer As Timer

    Public Sub New()
        _timer = New Timer(1000.0) With {.AutoReset = True}
        AddHandler _timer.Elapsed, Sub(sender, args) Console.WriteLine("It is {0} and all is well", DateTime.Now)
    End Sub

    Public Sub Start()
        _timer.Start()
    End Sub

    Public Sub [Stop]()
        _timer.Stop()
    End Sub
End Class

Module Module1
    Sub Main()
        HostFactory.Run(sub(x)
            x.Service (Of TownCrier)(AddressOf ServiceConfiguratorCallback)
            x.RunAsLocalSystem()
            x.SetDescription("Sample Topshelf Host")
            x.SetDisplayName("Stuff")
            x.SetServiceName("Stuff")
        End sub)
    End Sub

    Private Sub ServiceConfiguratorCallback(s As ServiceConfigurator(Of TownCrier))
        s.ConstructUsing(Function(name) New TownCrier())
        s.WhenStarted(sub(tc) tc.Start())
        s.WhenStopped(sub(tc) tc.Stop)
    End Sub
End Module
```

Hope it helps :thumbsup:

**Comment by ayman-metwally-developer** [comment]
Wow .. thanks for the fast response .. and it works perfectly.

I was experiencing a moment of "Should I move to C#?" :) 
You just saved one VB.NET fan :)

**Comment by sytrox** [comment]
`HostFactory.Run(Sub(x)								
								x.Service(Of MyService)(Sub(sc As ServiceConfigurator(Of MyService))
															 sc.ConstructUsing(Function() New DataBridge)
															 sc.WhenStarted(Function(service, hostControl)
																				return service.Start(hostControl)
																			End Function)
															 sc.WhenStopped(Function(service, hostControl)
																				return service.Stop(hostControl)
																			End Function)
															 sc.WhenContinued(Sub(s)
																				  s.[Continue]
																			  End Sub)
															 sc.WhenPaused(Sub(s)
																			   s.Pause
																		   End Sub)
															sc.WhenShutdown(Sub(service, hostControl)
																				service.Stop(hostControl)
																			End Sub)
														 End Sub)
								x.SetDescription("MyService")
								x.EnablePauseAndContinue							
							End Sub)`
