### ISSUE TITLE
ServiceBase.AutoLog not exposed in TopShelf.

### ISSUE THREAD

**Issue by JohanLindvall** [Topshelf/Topshelf#344]
There doesn't seem to be a way to control ServiceBase.AutoLog from within TopShelf.

https://msdn.microsoft.com/en-us/library/system.serviceprocess.servicebase.autolog(v=vs.110).aspx

Consider exposing this property in TopShelf.

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
