### ISSUE TITLE
Uninstalling service and then trying to re-install the service too quickly leads to race condition and disabled service

### ISSUE THREAD

**Issue by haf** [Topshelf/Topshelf#35]
Repro:
1. Install service "Topshelf.Host.exe install --networkservice"
2. Try run it "Topshelf.Host.exe start"
3. See error message
4. "Topshelf.Host.exe uninstall"
5. See message 'uninstall successful'
6. Browse to system services (`services.msc`), service is in state 'disabled'. Cannot be removed with command line anymore.

**Comment by Moulde** [comment]
I just ran into this issue, and found this info
http://stackoverflow.com/questions/225275/how-to-force-uninstallation-of-windows-service

The solution that worked for me, was to just close the services window, as it seems that window has a handle on the service, resulting in topshelf being unable to uninstall the service.

The service was disabled, and "marked for deletion". Closing the "Services" window and opening it back up, fixed the issue, and i was able to install the service again.

NB. There are other solutions in the above link on stackoverflow.

**Comment by dragon788** [comment]
Per haf's comment, you CAN use sc.exe to delete a service WITHOUT rebooting, but you need to do a WMI search per Moulde's link to kill any process running mmc.exe or holding open the service executable and then you can remove the service without errors.

**Comment by ruant** [comment]
Just closing the Services window per @Moulde comment solved the issue for me.

**Comment by akanshayadav11** [comment]
Great article!

I want to do a comment if you allow me.
https://dipoletechi.com/blog-post/how-to-force-uninstallation-of-windows-service/

Thanks
