### ISSUE TITLE
Missing nuget dependency for minimum .NET Framework v4.5.2.

### ISSUE THREAD

**Issue by a-jomills** [Topshelf/Topshelf#351]
The docs say: Topshelf uses the .NET Framework v4.5.2.

This needs to be set as a minimum dependency of the nuget package.

**Comment by phatboyg** [comment]
How? The files are put into the `lib\net452` folder - is there another way to specify this dependency?

**Comment by a-jomills** [comment]
There should be. In VS 2015, Pkg Mgr does not show it as a dependency.
under Dependencies, it is empty. I only found out about it after trying to install, when it failed.

**Comment by TravisTheTechie** [comment]
That's how it's shown in the examples section of the docs: https://docs.microsoft.com/en-us/nuget/schema/nuspec#examples

**Comment by phatboyg** [comment]
?? Not sure if there is anything to do here.

**Comment by a-jomills** [comment]
If the package can be marked with such dependency that would be a real help.
Otherwise no one knows there is a higher dep until you waste time and effort trying to upgrade the package.

—
John Mills
EQS & Xpresso Software Engineering
APEX Systems Consultant
O: 425-679-7129
C: 425-736-1370

**Comment by a-jomills** [comment]
This is currently what I see in VS Package Manager:

![2018-01-05_15-56-08](https://user-images.githubusercontent.com/12143674/34633499-65a17d08-f274-11e7-9563-f22743091134.png)

Here is a package that shows the FW dependencies:

![2018-01-05_15-56-47](https://user-images.githubusercontent.com/12143674/34633508-77686d30-f274-11e7-842f-36da9764361a.png)
:

**Comment by stijnherreman** [comment]
I could be wrong, but I think only receiving the error on installation, is intended behaviour. And the dependencies you see for Automapper is due to it being a .NET Standard library.

**Comment by phatboyg** [comment]
Ported builds all to dotnet and now it shows up, ref a305af6
