### ISSUE TITLE
"HostConfigurator.UseLog4Net()" is not respecting assembly attributes and is not loading the app.config file correctly.

### ISSUE THREAD

**Issue by BrainSlugs83** [Topshelf/Topshelf#352]
When using log4net, all you have to do is add an attribute to your assembly, and it will automatically load it's data from your app.config, and watch for changes:
`[assembly: log4net.Config.XmlConfigurator(Watch = true)]`

If you have this and you grab a handle to any log4net logger, it will automatically run with the settings from your app.config file:
`var logger = log4net.LogManager.GetLogger("MyLogger");`

The documentation indicates that we should be able to just use `x.UseLog4Net();` -- but that doesn't seem to be the case.

Because that doesn't work, instead we have to provide a fully qualified path to the config file if we want topshelf to use it.

```
return (int)HostFactory.Run(x =>
{

    // . . .

    x.UseLog4Net(typeof(Program).Assembly.Location + ".config", true);

    // . . .

});
```

**Comment by grhm** [comment]
I've found that for logging to work, I needed to get a logger in my main() function before calling HostFactory.Run.
That seems to honour the assembly attribute stating where the config file lives.

So as a workaround, you can do

    public static int Main()
    {
        // Ensure logging is initialized - otherwise nothing seems to be logged at all!
        log4net.LogManager.GetLogger(typeof(MyService));

        var exitCode =
            HostFactory.Run(configure =>
            {
               ...
                configure.UseLog4Net();
                ....
            };
        return (int) exitCode;
    }

**Comment by BrainSlugs83** [comment]
Thanks, that's a better workaround, IMO. -- Would be nice if it wasn't necessary though. (This is definitely still a bug.)

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
