### ISSUE TITLE
WindowsHostSettings.CanHandlePowerEvent is not exposed for setting

### ISSUE THREAD

**Issue by davidjade** [Topshelf/Topshelf#359]
To use the new power event code, you have to be able to set WindowsHostSettings.CanHandlePowerEvent to true. However HostConfigurator (and the Impl) is missing an EnablePowerEvent method to turn this on.

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
