### ISSUE TITLE
SetStartTimeout not working 

### ISSUE THREAD

**Issue by jafmonteiro** [Topshelf/Topshelf#360]
I need to configure the SetStartTimeout param in a topshelf service, but it looks like the SetStartTimeout is not being taken into account.

I'v tried topshelf nuget package v4.02 and v4.03

Can anyone help please?
Below is an initialization example:

```
        public static int Main(string[] args)
        {
            return (int)HostFactory.Run(x =>
            {
                x.SetStartTimeout(TimeSpan.FromMilliseconds(40000));
                FactoryRun(x);
            });
        }

```

Thanks

**Comment by khasibhatla** [comment]
Same here...

**Comment by phatboyg** [comment]
You still need to use the HostControl interface to request additional time if your service takes a long time to startup. This is a windows service control manager requirement.

**Comment by jitens01** [comment]
@phatboyg How I suppose to use this interface ?

**Comment by phatboyg** [comment]
It's passed when you implement ServiceControl on your Service.

**Comment by alewmt** [comment]
SetStartTimeout is not working. Why does it exist?
