### ISSUE TITLE
Call to HostFactory.Run silently fails when called in service (needs documentation change).

### ISSUE THREAD

**Issue by casperOne** [Topshelf/Topshelf#365]
I currently wrap a call to `HostFactory.New` in a method that is *not* in `Program.cs`/the file that contains the entry point in the program.

I've deployed the app via Octopus, which sets up the service with a service name that matches the name of the **entry point** of the assembly.

I do *not* make a call to `SetServiceName`.

As a result, when running as a service (not as a console app), TopShelf silently fails; I assume this is because there's a mismatch between the service name in the Service Control Manager and what TopShelf defaults the service name to, which in this case, is the name of the assembly that contains the convenience method that wraps the call to `HostFactory.New`.

I don't expect TopShelf to work in this situation.  However, the documentation for SetServiceName doesn't give *any* indication that the names need to match.

Under ["Service Name"](https://topshelf.readthedocs.io/en/latest/configuration/config_api.html?highlight=setservicename#service-name), it states (**emphasis mine**):

> Specify the base name of the service, as it is registered in the services control manager. **This setting is optional and by default uses the namespace of the Program.cs file (well, basically, the calling assembly type namespace).**

```
HostFactory.New(x =>
{
    x.SetServiceName("MyService");
});
```

> It is recommended that service names not contains spaces or other whitespace characters.
> 
> Each service on the system must have a unique name. If you need to run multiple instances of the same service, consider using the InstanceName command-line option when registering the service.
> 

Yes, there's mention that the call is optional, but there's no mention of the consequences of taking the default name.

It's one thing if the consequence is minor, but for the library to fail completely in it's *primary* task because of this condition and not have it documented *anywhere* is a huge source of pain and frustration (it cost me a day, that's unacceptable).

It would benefit your users to have the documentation be more clear here, as well as in other places where any "gotchas" occur.

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
