### ISSUE TITLE
Service stops unexpected, but regularly

### ISSUE THREAD

**Issue by mikeongithub** [Topshelf/Topshelf#366]
I have implemented a windows service using TopShelf. The service hosts some WCF services that can be consumed by clients, one of them uses IBM MQ. 

Usually the service runs normal as expected. But sometimes the service just stops while processing a request as if anyone regularly stopped it. The event logs only shows errors that are caused **by** the stop, 

    Failed to stop service. System.InvalidOperationException: An unhandled exception was detected ---> System.NullReferenceException: Object reference not set to an instance of an object.
    at IBM.WMQ.MQFAPConnection.AsyncFailureNotify(Exception ex, Boolean quiescing)
    at IBM.WMQ.MQRcvThread.Run
    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ConctextCallback callback, Object state, Boolean preserveSyncCtx)
    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ConctextCallback callback, Object state, Boolean preserveSyncCtx)
    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ConctextCallback callback, Object state)
    at System.Threading.ThreadHelper.ThreadStart()
    --- End of inner exception stack trace ---
    at TopShelf.Runtime.Windows.Windows.ServiceHost.OnStop()
    at System.ServiceProcess.ServiceBase.DeferredStop()

I have tried several ways to force such a situation such as raising Exceptions in tasks, raising exceptions in the WCF service implementation, raising CSEs, etc. None of them caused a "regular" stop of the service.

**Comment by phatboyg** [comment]
So something in IBM.WMQ.MQFAPConnection is throwing an unhandled exception, which causes Topshelf to shut the service down. You can use the ServiceRestart policies to have it automatically restart, but fixing the Null reference exception would be the best course of action.

**Comment by mikeongithub** [comment]
The InvalidOperationException is caused when the shutdown of the service is ongoing. The question for me is, why did the service shutdown? My customer hasn't seen this behavior before without TopShelf AFAIK.

**Comment by stephenpatten** [comment]
Similar issue here:

Failed to stop service. System.InvalidOperationException: An unhandled exception was detected ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at WatchListService.WatcherWrapper.Watch(DataRowView QueueRow) in D:\Agents\A1\_work\2\s\AWD\Services\WatchList\WatchListService\WatcherWrapper.vb:line 173
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
   --- End of inner exception stack trace ---
   at Topshelf.Runtime.Windows.WindowsServiceHost.OnStop()
   at System.ServiceProcess.ServiceBase.DeferredStop()

I have also wired up Serilog to be the internal logger and to handle unhandeled exceptions here:


    class Program
    {
        static void Main()
        {
            Enterprise.Base.Utilities.ApplicationName = "WatchListService.exe";

            var logCat = PLSecuredResource.GetResource("ApplicationName", false);

            var filePath =
                $"{ConfigurationManager.AppSettings["LogFileBaseDir"]}\\{logCat}TS_{Environment.MachineName}_" +
                "{Date}.log";

            const string logTemplate = "{Timestamp:yyyy-MM-dd HH:mm:ss.fff} [{Level:u3}] [{CorrelationId}] [{MachineName}] [{Application}] [{ProcessId}] [{ThreadId}] [{SourceContext:l}] {Message}{NewLine}{Exception}";

            Log.Logger = new LoggerConfiguration()
                .ReadFrom.AppSettings()
                .Enrich.FromLogContext()
                .Enrich.WithMachineName()
                .Enrich.WithProcessId()
                .Enrich.WithThreadId()
                .Enrich.WithProperty("Application", "WatchList")
                .WriteTo.RollingFile(filePath, outputTemplate: logTemplate, fileSizeLimitBytes: null)
//#if DEBUG
//                .WriteTo.RollingFile(filePath, outputTemplate: logTemplate)
//#else
//                .WriteTo.Async(a => a.RollingFile(filePath, outputTemplate: logTemplate, buffered: true))
//#endif
                .WriteTo.Console()
                .CreateLogger();

            Log.Logger.Information("Identify main thread");

            HostFactory.Run(x =>
            {
                x.Service <WatchListService.Service> (s =>
                {
                    s.ConstructUsing(name => new WatchListService.Service());
                    s.WhenStarted(sch => sch.StartService(null));
                    s.WhenStopped(sch => sch.StopService());
                });
                x.UseSerilog();
                x.RunAsLocalSystem();

                x.SetDescription("WatchListServiceTS Host");
                x.SetDisplayName("WatchListServiceTS");
                x.SetServiceName("WatchListServiceTS");

                x.OnException(ex => {Log.Logger.Error(ex, "WatchListServiceTS Unhandled Exception");});
            });

            // At application shutdown
            Log.CloseAndFlush();
        }
    }

**Comment by ozkanb** [comment]
Same issue here... 

Log viewer event: "Service terminated unexpectedly. It has done this 7 time(s)."
