### ISSUE TITLE
Support SERVICE_CONTROL_PRESHUTDOWN

### ISSUE THREAD

**Issue by Misiu** [Topshelf/Topshelf#371]
I have a winservice that is responsible for connecting with external service. User can put doc files in specific directory and then my winservice upload's them one by one, they are processed and downloaded as PDF's to separate directory. This can last up to 10 minutes, because sometimes files added to directory are large.
In worst case scenario my service starts uploading file and user select start>shutdown.
I'd like to be sure processing of single file is completed (it is uploaded,processed and downloaded) before windows shutdown.

I've read a bit around the internet and it looks that C+ supports SERVICE_CONTROL_PRESHUTDOWN, but C# not.
There are hacks:
http://stackoverflow.com/questions/5217246/how-to-delay-shutdown-and-run-a-process-in-window-service,
https://www.atomia.com/2011/11/16/how-to-process-the-preshutdown-event-in-a-managed-windows-service/
http://installerframework.codeplex.com/SourceControl/latest#InstallerFramework/InstallerFramework/Installers/Service/ServiceInstaller.cs

but I'd like to avoid such hacks and use Topshelf.

Can I set max timeout to lets say 10 minutes and handle system shutdown (restart) events, so that I can delay them until processing completes?

If not then I'd like to ask for this feature, because I think it would be very helpful. Thanks.

**Comment by Misiu** [comment]
@phatboyg I'd like to look into this. Could You please point me any starting point?
Should I create custom ServiceInstaller with override for Install ([like here](http://installerframework.codeplex.com/SourceControl/latest#InstallerFramework/InstallerFramework/Installers/Service/ServiceInstaller.cs)) and use it in https://github.com/Topshelf/Topshelf/blob/develop/src/Topshelf/Runtime/Windows/HostServiceInstaller.cs#L171?

I also need to override `OnCustomCommand` in ServiceBase. Where can I do that?

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
