### ISSUE TITLE
How to disable permission to change service properties, through topshelf?

### ISSUE THREAD

**Issue by nrip-monotype** [Topshelf/Topshelf#374]
Reference:

![svc](https://cloud.githubusercontent.com/assets/22932714/26769078/c099562e-49cb-11e7-86b7-0df87daa13fa.png)

How to disable users from changing the service property settings? Hopefully through command line or programatically.

**Comment by nrip-monotype** [comment]
@trondr 
Thanks a lot! This should help, I'll try implementing this.

**Comment by TechnikEmpire** [comment]
@trondr How did you manage to set the SDDL back to less-restrictive settings afterward? Cranking up security via the SDDL works fine here, but you lose the ability within the same process to even get a handle on which to downgrade the security. Maybe I need to read more and try to find a setting for the host/owner process?
