### ISSUE TITLE
How to use async/await in the HostFactory.Run/New method?

### ISSUE THREAD

**Issue by jello-chen** [Topshelf/Topshelf#375]
When I use the following code,
`HostFactory.Run(async x => await DoAsync())`
it throws an error as below
`ERROR Topshelf.HostFactory - An exception occurred creating the host
 Topshelf.HostFactorynameTopshelf.HostConfigurationException: The service was not properly configured: 
[Failure] ServiceBuilderFactory must not be null`

**Comment by phatboyg** [comment]
You don't.

**Comment by mason-mcglothlin** [comment]
@phatboyg Can you explain what you mean by "you don't"? Do you mean there's no current plans to support async/await with a TopShelf service? If someone were to contribute a PR that enables async/await here, would you be willing to accept it?

**Comment by phatboyg** [comment]
There are no plans to do any further commits to Topshelf. If a PR is submitted and passes the smell test, I'll merge it and release a new version. Topshelf is purely in maintenance mode at this point, since .NET now has its own generic host that is much more flexible and integrated.
