### ISSUE TITLE
SetStartTimeout(TimeSpan startTimeOut) method is not there in HostConfigurator interface ? 

### ISSUE THREAD

**Issue by jitens01** [Topshelf/Topshelf#376]
I am using Topshelf Nuget package version 3.1.1 This is a bit older but latest only to support on .NET framework 4.5 
Now here I am not able to find a few methods in HostConfigurator.cs file or in HostConfigurator interface as 
SetStartTimeout(TimeSpan startTimeOut)
SetStopTimeout(TimeSpan stopTimeOut)
OnException(Action<Exception> callback)

I really want to use these methods, how I supposed to do so ?

**Comment by phatboyg** [comment]
Replied in other issue.
