### ISSUE TITLE
list/status command

### ISSUE THREAD

**Issue by alexdresko** [Topshelf/Topshelf#378]
It would be nice if there was a `list` or `status` command that would pull from SCM and show instances that were installed and their current status. That way, you wouldn't have to use another tool for those tasks. 

I didn't see where that's implemented already. I'd be happy to contribute, given some pointers on where to start in the Topshelf codebase. 

In the meantime, should I add that as a custom command, maybe?

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
