### ISSUE TITLE
Add ability to add custom command line arguments

### ISSUE THREAD

**Issue by jws305** [Topshelf/Topshelf#379]
I am attempting to add a custom command line argument to my application. 
 I followed the steps in this issue but I can't seems to bind the option. https://github.com/Topshelf/Topshelf/issues/333

If I am reading the code right I need to add an argument option to the [ICommandLineParser](https://github.com/Topshelf/Topshelf/blob/develop/src/Topshelf/Configuration/CommandLineParser/ICommandLineElementParser.cs).  The only public way of accessing the parser is through [HostConfiguratorImpl.AddCommandLineSwitch](https://github.com/Topshelf/Topshelf/blob/develop/src/Topshelf/Configuration/HostConfigurators/HostConfiguratorImpl.cs#L171) and [HostConfiguratorImpl.AddCommandLineDefinition](https://github.com/Topshelf/Topshelf/blob/develop/src/Topshelf/Configuration/HostConfigurators/HostConfiguratorImpl.cs#L178) but there is no hook for arguments.

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
