### ISSUE TITLE
Service not showing in services.msc list

### ISSUE THREAD

**Issue by DiegoGFritz** [Topshelf/Topshelf#380]
I have created a console application and tried to host it using TOPSHELF. Its working fine from command prompt but when trying to install it, it is not getting visible in Services.msc list.

Environment:
1. Windows 10 Enterprise version 1703 (Build 15063.413)
2. X64.
3. Visual Studio 2015/17.
4. Topshelf version 4.0.3
5. Using .Net framework 4.5.2

Thanks & Regards,
Fritz, Diego

**Comment by FSou1** [comment]
Have you try to install it using Administrator credentials?

**Comment by DiegoGFritz** [comment]
I had not tried. You are right. It works now.
I consult you. Is it the only way it exists to appear on the Windows services monitor?
