### ISSUE TITLE
Running in console mode CTRL+C on OSX doesn't exit the process

### ISSUE THREAD

**Issue by et1975** [Topshelf/Topshelf#382]
Using Topshelf 4.0 and Mono 4.8, it appears to be stopping:

>Control+C detected, attempting to stop service.
...
The Topshelf service has stopped.

But it doesn't exit the process.

**Comment by vaniovanio** [comment]
I am experiencing the same issue on Server 2016. The service is stopped, but the process (e.g. the actual executable) is still running and I can see it in Task Manager.

How should I configure the service to always exit process after service is stopped?

**Comment by nickolasacosta** [comment]
I also have this problem on Windows 10. After running `stop uninstall` the process is still running and the service stays in the list. Ending the process from the task manager finishes the job, but this step shouldn't be necessary.

**Comment by vaniovanio** [comment]
Yes, that's exactly the problem, but I don't know how to fix it...

**Comment by phatboyg** [comment]
You probably have background threads still running that are preventing the process from exiting.

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
