### ISSUE TITLE
Suggestion: Include the service installation details on the docs

### ISSUE THREAD

**Issue by vijayvepa** [Topshelf/Topshelf#383]
Please include the command-line parameters (at least mention the **help** parameter in the docs).
https://topshelf.readthedocs.io/en/latest/installation/help.html

I was an existing WindowsService developer and was stuck on this step.

https://github.com/Topshelf/Topshelf/issues/340

**Comment by i-e-b** [comment]
The link is under "Topshelf Overview -> Topshelf Commandline Reference" on the left-side navigation.

Direct link:
https://topshelf.readthedocs.io/en/latest/overview/commandline.html
