### ISSUE TITLE
Recovery options -> RestartService. Seconds.

### ISSUE THREAD

**Issue by Gnitry** [Topshelf/Topshelf#385]
I want my service to be restarted in 5 seconds after crash. I can configure it with SC utility, but how can I specify it with Topshelf?

**Comment by FSou1** [comment]
Have you checked out the [service recovery](https://topshelf.readthedocs.io/en/latest/configuration/config_api.html#id1) section?

**Comment by Gnitry** [comment]
> Have you checked out the service recovery section?

Yes. There are only minutes.

**Comment by eman1986** [comment]
set it to zero, that's what I do
