### ISSUE TITLE
Tophself problems with removing service on WIndows 10 Enterprise version 1703

### ISSUE THREAD

**Issue by IRQG** [Topshelf/Topshelf#386]
Hello,
in my company we have an issue with uninstalling service using topshelf. According to logs (application witch uses topshelf is installed / deinstalled using Wix Burn Engine along with msi package) everything is fine but service hangs in system under changed account. It was installed under networkservice account but after removing it is running under localsystem. This occurs on Windows 10 version 1703 and 1607 with latest updates.
I've cretaed a simple project with topshelf and msi package to install. Whole VS solution is attached. I also provide logs from installation and deinstallation and a screenshot from Services window. Worth mentioning  is services windows was opened after deinstallation (I've read that it can block service and prevent from being uninstalled). 
![services](https://user-images.githubusercontent.com/3007907/29170750-477db56c-7dda-11e7-8a8d-c52eab988896.PNG)

![windows](https://user-images.githubusercontent.com/3007907/29170751-4786521c-7dda-11e7-9f45-2b61b18adf7f.PNG)

[SimpleServiceInstaller.txt](https://github.com/Topshelf/Topshelf/files/1214925/SimpleServiceInstaller.txt)
[SimpleServiceUnInstaller.txt](https://github.com/Topshelf/Topshelf/files/1214926/SimpleServiceUnInstaller.txt)
[TopShelfServiceTestWindows10.zip](https://github.com/Topshelf/Topshelf/files/1214927/TopShelfServiceTestWindows10.zip)

Hope this helps.

With Best regards

Irek

**Comment by nickolasacosta** [comment]
Workaround: Check your task manager for the exe.  In my case it was still running. After you've ended it, refresh your service list and it should be gone.
