### ISSUE TITLE
TopShelf crashing when using in dotnet core 2.0 project

### ISSUE THREAD

**Issue by saleem-mirza** [Topshelf/Topshelf#387]
I'm trying to port dotnet core 1.1 project into  dotnet core 2.0. Even though it's building fine but application is crashing at run-time with following error

```
Topshelf.HostFactory Error: 0 : An exception occurred creating the host, System.TypeLoadException: Could not load type 'System.ServiceProcess.ServiceAccount' from assembly 'System.ServiceProcess, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Topshelf.RunAsExtensions.RunAsLocalSystem(HostConfigurator configurator)
   at TaskServiceCore.SacsTaskService.<>c.<Main>b__1_0(HostConfigurator r) in SacsTaskService.cs:line 62
   at Topshelf.HostFactory.New(Action`1 configureCallback)
Topshelf.HostFactory Error: 0 : The service terminated abnormally, System.TypeLoadException: Could not load type 'System.ServiceProcess.ServiceAccount' from assembly 'System.ServiceProcess, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Topshelf.RunAsExtensions.RunAsLocalSystem(HostConfigurator configurator)
   at TaskServiceCore.SacsTaskService.<>c.<Main>b__1_0(HostConfigurator r) in SacsTaskService.cs:line 62
   at Topshelf.HostFactory.New(Action`1 configureCallback)
   at Topshelf.HostFactory.Run(Action`1 configureCallback)
```

Project references looks like

```
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
    <PackageReference Include="Serilog.Sinks.Literate" Version="3.0.0" />
    <PackageReference Include="Serilog" Version="2.5.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="1.4.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="2.4.0" />
    <PackageReference Include="Serilog.Sinks.RollingFile" Version="3.3.0" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="4.4.0" />
    <PackageReference Include="Topshelf" Version="4.0.3" />
```

Environment:

Windows 10 Enterprise
Visual Studio 2017 Enterprise

**Comment by a-patel** [comment]
I am getting the same error. i am using .net core 2.0.

**Comment by a-patel** [comment]
Please reply as soon as possible.
I need it urgently.

**Comment by andreyleskov** [comment]
As temporary solution you can add binding redirect. Did not check it under linux & mono, but can be used under windows, fixed same problem for me. 
Check yours System.ServiceProcess version and add it to app.config. If file is missing, create it in console project, set "build action" to "None" and "Copy to output directory" to "Copy if newer". Sample content:
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.ServiceProcess" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-4.4.0.0" newVersion="4.4.0.0"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>`

**Comment by phatboyg** [comment]
Yeah, well, it doesn't support .NET core, so...

**Comment by a-patel** [comment]
are you planning to support .net core 2.0 in near future?

**Comment by philcroft79** [comment]
I read somewhere that you should be able to create a 4.6 console project along side a .net core project if you're using VS 2017. It allows for the co-existence. Meaning, you can use TopShelf on the console project, and reference .net core libraries.

I just verified that this works.

**Comment by jdstuart** [comment]
This a bug in Asp.net core 2.0. Apparently the bug has been fixed, but will only be released as part of 2.1

**Comment by ayoung** [comment]
I really don't see the point of Topshelf supporting .NET Core. .NET Core is meant to be OS agnostic and Windows Services is necessarily OS specific.

**Comment by saleem-mirza** [comment]
@ayoung, In my humble opinion, .NET Core should be supported in Topshelf. It has nothing to do with platform agnosticism.

**Comment by ayoung** [comment]
@saleem-mirza what would it do though? the Windows Services API is not even in .NET Core.

**Comment by saleem-mirza** [comment]
@ayoung. Good point but we are asking here to fix Topshelf. Please correct me if I'm wrong, we can still access Full Framework API from with .net core app.

I know when .net core 1 was released, there was no threading support in it and folks responsible there were defending their decision like crazy but eventually they have to add it back in .net core 2. Please see thread https://github.com/dotnet/corefx/issues/2576

So if Windows Service support is not there in .NET Core, it will be there soon :)

**Comment by urbanhusky** [comment]
There seems to be a NetStandard API for the Win32 API service support:
https://github.com/dasMulli/dotnet-win32-service
