### ISSUE TITLE
Command line verbs/arguments being silently ignored

### ISSUE THREAD

**Issue by csuzw** [Topshelf/Topshelf#388]
I'm using Topshelf 4.0.3 on Windows Server 2012 R2.

When I try to install a service with the following command it ignores the verb/options and runs in command line mode instead without any warnings/errors:
`myapp.exe install -servicename:"myapp.test" -displayname:"myapp.test" -description:"my app description" -username:"mydomain\myusername" -password:"mypassword" --manual`

I eventually realised that if I replaced the colons with spaces it works so it looks like quoted values only work with spaces.  I don't know if this is intended behaviour but if Topshelf recognises the verb surely it should not fall back silently to the command line mode?  I'd like to at least see some more explicit documentation on what is valid and invalid (another example that surprised me was that it seems like you can use space instead of colon without quotes even if the option value has spaces which is usually something that doesn't work in CLIs).

Now I am trying to uninstall the application.  Running `myapp.exe uninstall` seems to ignore verb as well and fall back to using the command line with no warning/error.  Again if this is intended behaviour it's not very good.  I am assuming this is failing because I overrode the servicename when I installed it and to uninstall it I need to provide an instancename but I don't know what this would be (using the service name does not work).  I have previously installed and uninstalled this service using `myapp.exe install` and `myapp.exe uninstall` without using any additional options and that has worked so I don't believe this is an issue with the application itself.

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
