### ISSUE TITLE
TopShelf.Log4Net nuget requires log4net 2.0.5, but is compiled for 1.2.15.0

### ISSUE THREAD

**Issue by DanJensen** [Topshelf/Topshelf#390]
The TopShelf.Log4Net nuget package has a dependency on log4net 2.0.5.  However, the csproj file of the project still says 1.2.15.0 (pasted below for reference).  I understand that log4net 2.0.5 is compatible with 1.2.15.  However, I'm finding services won't start because of this apparent conflict in version.  I tried downgrading to 1.2.15, but since I'm using paket to handle my dependencies, it blows up if it sees I'm grabbing the wrong dependency for the TopShelf.Log4Net package.  I know I can solve this with an assembly redirect in the config file.  But in my environment, the config files that actually get deployed are controlled by an install team.  I can coordinate that with them, but would prefer this type of the thing to be bullet proof before it leaves dev.

So I'm just wondering if this is here for backwards compatibility concerns, or is it a typo?  Can it be updated to match the dependency version of the package?

    <Reference Include="log4net, Version=1.2.15.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a, processorArchitecture=MSIL">
      <HintPath>..\packages\log4net.2.0.5\lib\net45-full\log4net.dll</HintPath>
      <Private>True</Private>
    </Reference>

**Comment by phatboyg** [comment]
It's movign to 2.0.8
