### ISSUE TITLE
Documentation is out of date?

### ISSUE THREAD

**Issue by nibblesnbits** [Topshelf/Topshelf#394]
I just installed the 4.0.3 version of TopShelf into my project and looked to [the documentation](https://topshelf.readthedocs.io/en/latest/configuration/quickstart.html) for how to get started, and noticed that none of the code here works with this version.  Is the documentation out of date?  Do I need to downgrade?

**Comment by Mutuduxf** [comment]
the doc by the link is ok and you can show your code for the further discussion

**Comment by tmgirvin** [comment]
The documentation is crap.  The code overview (https://topshelf.readthedocs.io/en/latest/configuration/quickstart.html) shows that the service needs no base class and that you call HostFactory.Run().  All the other doc (http://docs.topshelf-project.com/en/latest/configuration/config_api.html#simple-service) shows that you need to implement an interface and that you call HostFactory.New().  What's the difference between Run and New?  Do we have to implement the interface?  Is the configurator action supposed to return a service?  An example that actually compiles and runs would be good.  A Swagger doc that lists all of the methods and their overloads with some description would be great.

**Comment by chrkon** [comment]
**The link to the documentation is broken on http://topshelf-project.com/**  
The documentation is linked to https://topshelf.readthedocs.org/en/latest/ and this link is not working.
The link https://topshelf.readthedocs.io/en/latest/ will open the documentation, but it seems to be the documentation for Version 3.0. Ist there any newer information available?

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
