### ISSUE TITLE
Installing TopShelf service under VSTS agent (without necessary permissions) results in "fork-bomb"

### ISSUE THREAD

**Issue by flakey-bit** [Topshelf/Topshelf#397]
Our continuous-deployment  pipeline is set up in VSTS. We have a "CommandLine" task to install the topshelf service:

```
CONFIG:
=====
Tool: My.TopShelfService.exe
Arguments: install -servicename:my-service-name -displayname:my-service-name --autostart start
WorkingFolder: c:\path\to\MyService
```

Anyway when it comes to running this task it keeps spawning processes (My.TopShelfService.exe) - to the point the machine comes to a halt!

https://docs.microsoft.com/en-us/vsts/build-release/tasks/utility/command-line

Running the same command as a PowerShell task has the same effect:

```
#BEGIN POWERSHELL SCRIPT 
param (
[Parameter(Mandatory=$true)][string]$serviceName,
[Parameter(Mandatory=$true)][string]$servicePath
)

cd $servicePath
.\My.TopShelfService.exe install -servicename:$serviceName -displayname:$serviceName --autostart start
#END POWERSHELL SCRIPT
```

I should note that this is running on an external VSTS agent.

**Comment by flakey-bit** [comment]
This was caused by the VSTS Agent service running as the user "Network Service" rather than "Local System" (Network Service does not have permission to create services).

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
