### ISSUE TITLE
Selecting between multiple services when installing

### ISSUE THREAD

**Issue by btrepp** [Topshelf/Topshelf#398]
Hi there,

I'm not sure if topshelf can do this, but I figured i'd ask.
I have an application that runs various services independently. Eg. 

```
myapp.exe web
myapp.exe migrate
myapp.exe emailer
```
I'm using Argu for argument parsing and this works well. What I would like to add is something like

```
myapp.exe install web 
myapp.exe install emailer
```
Which would use topshelf to install 2 seperate services into windows. The doc implies that only one is possible, and that topshelf does it's own argument parsing. Is there any way I can use it by specifing the arguments myself?.

**Comment by supermankelly** [comment]
I just asked the same question on there google groups page, but doesn't look like they have replied to anyone for months. 

My needs a bit simpler as in I only need to run one myapp.exe at once. I have a parameter which runs a particular class at the console and another which opens a windows form to run the classes via a UI which I can live without. So I just need it to pass an existing parameter when starts.

`myapp.exe start param1
`

**Comment by phatboyg** [comment]
Yeah that isn't possible presently. There is another issue asking for startup args.
