### ISSUE TITLE
Support multiple .net version in 4.x.x release

### ISSUE THREAD

**Issue by davidshen84** [Topshelf/Topshelf#399]
I have to use **.net45** for my project, and the current latest release of this package does not support **.net45**. I have to downgrade to `v3.3.1` to use this package.

I'd prefer using the latest release of this package, while compliant to my company policy.

**Comment by tomek14** [comment]
But 4.5.1 is unsupported. You shoud keep pushing your company to use latest supported .net in 4.5.x branch.
https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/
