### ISSUE TITLE
GMSA Accounts require empty password parameter to be passed

### ISSUE THREAD

**Issue by aaronmell** [Topshelf/Topshelf#400]
if I add just the username flag I get the following error 

[Failure] Command Line An unknown command-line option was found: DEFINE: username = username

**Comment by phatboyg** [comment]
I'm not sure what the request is here, could you clarify or close?

**Comment by aaronmell** [comment]
I shouldn't be required to pass an empty password when installing a service with a GMSA account

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
