### ISSUE TITLE
Install and uninstall service without any output

### ISSUE THREAD

**Issue by Elron1179** [Topshelf/Topshelf#402]
Hi there,
I have to deploy a service in an environment where any kind of output visible to the user (such as the console window topshelf is showing) is utterly prohibited.
Before trying to build a custom action for my installer which then creates a silent process which then calls the service, I would like to know if there is any option to prevent topshelf from producing any noticeable output.
Thank you very much.

Edit: was a bit hasty, start and end actions don't create any output.

**Comment by cjpomer** [comment]
Related: Exception stack traces get dumped to output during install. How can the exception be handled by user (and installation still fail).

**Comment by maxcherednik** [comment]
I see, I would say it is rather exotic requirement, but here are few options: 
https://stackoverflow.com/questions/836427/how-to-run-a-c-sharp-console-application-with-the-console-hidden

**Comment by Elron1179** [comment]
> I see, I would say it is rather exotic requirement, but here are few options:

@maxcherednik Thank you for your response. 

Since I've found a solution for my problem, it is not that vital to me anymore. And I can imagine, that there are more important issues to solve than that.

But I think, the possibility to run Topshelf silent via command would be a nice feature for all who want to use it in a remote/auto administrated environment, where any possible user interaction with the installation process is unwelcome in order to ensure flawless installations.

Maybe I'll find some time to take a look at it myself :)

**Comment by Pellared** [comment]
@Elron1179 Are you creating the MSI using WiX? If yes then the solution may be to use WixQuietExec. See: http://wixtoolset.org/documentation/manual/v3/customactions/qtexec.html

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
