### ISSUE TITLE
Unable to write dumps when UnhandledException occurrs

### ISSUE THREAD

**Issue by advapiIT** [Topshelf/Topshelf#406]
I'm using TopShelf on a console application. If the app crashes for an unhandled exception there's no dump file written at all (I've added the entries in the registry). If I run the app as a console app, the dump is written instead.

**Comment by advapiIT** [comment]
Excuse me, any update on this?

**Comment by phatboyg** [comment]
I don't know what registry entries you are talking about, sorry. It's unlikely that I'll do anything with this unless somebody else contributes something to understand what's happening or what entries are needed, etc.

**Comment by maxcherednik** [comment]
@advapiIT, @phatboyg I believe it's not responsibility of this library.
