### ISSUE TITLE
Service Uninstalled After Windows Update?

### ISSUE THREAD

**Issue by MattHoneycutt** [Topshelf/Topshelf#407]
This is a strange issue, and I'm hoping someone else has encountered it before.  After major Windows updates (like the Fall Creators Update), an app that is installed as a service via Topshelf is somehow removed as an installed service.  All of the executable files are there, but the service is just gone.  It doesn't show up in the list of services anymore.   

I can reinstall it, and that works fine, but I'm trying to figure out why it is being removed in the first place.  Anyone have any ideas or suggestions?  I've seen this happen twice now, on two different machines.

**Comment by mario-d-s** [comment]
Googling around, it is evident that you're not the only one affected. See for example [this article](https://www.howtogeek.com/243581/windows-10-may-delete-your-programs-without-asking/).

I'm afraid you're out of luck and re-installing is the only option. Perhaps you can script this to check automatically after a reboot or something.

**Comment by phatboyg** [comment]
Right, this is an issue with Windows.

**Comment by MattHoneycutt** [comment]
Thanks for confirming!  That's what I suspected, I just hadn't heard other reports of the issue until now.
