### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by stijnherreman** [Topshelf/Topshelf#408]
Can someone give some insight on the state of the project? I notice there are only 7 commits from November 2016 to May 2017, and no commits at all since June 2017. Meanwhile there are a non-significant number of open issues.

Is the project considered to be mostly done and stable? Or is there still a lot of work to be done?
Should Topshelf still be considered for new development, or are there any alternatives to look out for?

**Comment by phatboyg** [comment]
Topshelf is still the standard for Windows services on .NET.

The picture with .NET core is still, well, uncertain considering the various hosting options (Linux, Mac, etc. with no clear standard way to make it a "service."

And there isn't a lot to do, it just works. And has for years.

**Comment by stijnherreman** [comment]
Great, that's good to know!

**Comment by phatboyg** [comment]
I just pushed a ton of commits, FYI.

**Comment by phatboyg** [comment]
Develop packages can be obtained: https://ci.appveyor.com/nuget/topshelf

**Comment by stijnherreman** [comment]
I guess this can be closed then :) thank you very much for the time you put in!
