### ISSUE TITLE
Not Responding in a Timely Manner on Start

### ISSUE THREAD

**Issue by markolbert** [Topshelf/Topshelf#409]
I'm running into a problem when I try to start a service created and installed via TopShelf. This is on a Windows 10 64 bit machine.

The service never starts, and throws the following error:

> [18:52:16 INF] Configuration Result:
> [Success] Name Community Scanner Service
> [Success] ServiceName Community Scanner Service
> [18:52:16 INF] Topshelf v4.0.0.0, .NET Framework v4.0.30319.42000
> [18:52:16 ERR] The service failed to start.
> System.InvalidOperationException: Cannot start service Community Scanner Service on computer '.'. ---> System.ComponentModel.Win32Exception: The service did not respond to the start or control request in a timely fashion
>    --- End of inner exception stack trace ---
>    at System.ServiceProcess.ServiceController.Start(String[] args)
>    at System.ServiceProcess.ServiceController.Start()
>    at Topshelf.Runtime.Windows.WindowsHostEnvironment.StartService(String serviceName, TimeSpan startTimeOut)
>    at Topshelf.Hosts.StartHost.Run()

When I look in the event viewer, there's an event that a timeout (30000 milliseconds) was reached...which is really weird, because there's no way it took more than 4 or 5 seconds for that error message to appear after typing <executable> start.

Here's the main method:

```
        static void Main( string[] args )
        {
            HostFactory.Run( x =>
            {
                x.UseSerilog( Container.Instance.Resolve<ILogger>() );
                x.UseAutofacContainer( Container.Instance );

                x.Service<ScannerService>( s =>
                {
                    s.ConstructUsingAutofacContainer();
                    s.WhenStarted( ( tc, hc ) => tc.Start( hc ) );
                    s.WhenStopped( ( tc, hc ) => tc.Stop( hc ) );
                    s.WhenPowerEvent( ( tc, z ) => tc.HandlePowerEvent( z ) );
                } );

                x.RunAsLocalSystem();
                x.StartAutomatically();

                x.SetDescription( "Community Scanner Service" );
                x.SetDisplayName( "Community Scanner Service" );
                x.SetServiceName( "Community Scanner Service" );
            } );
        }
```

And here's the code for the start method and the single private method it calls:

```
        public bool Start( HostControl hostControl )
        {
            hostControl.RequestAdditionalTime( TimeSpan.FromSeconds( 60 ) );

            // start the first scan in five minutes; if the Start method doesn't return
            // quickly, the Windows ServiceControl manager will gack
            _nextScan = DateTime.Now.AddMinutes( 5 );

            SetWakeup();

            return true;
        }

        private void SetWakeup()
        {
            var dueTime = _nextScan.ToFileTime();

            if (SetWaitableTimer(_waitableTimer, ref dueTime, 0, _timerCompleted, IntPtr.Zero, true))
                _logger.Information(
                    $"Created waitable timer {nameof(ScannerService)}WaitableTimer to trigger at {_nextScan:G}");
            else
                _logger.Error(
                    $"{nameof(ScannerService)}::{nameof(RunAndWait)}() - {nameof(SetWaitableTimer)}() failed, error was {Marshal.GetLastWin32Error()}");
        }
```

The service is intended to scan certain websites periodically, so it uses the CreateWaitableTimer() API to ensure it gets triggered even if the system is sleeping.

BTW, the service runs fine when executing the console app from within the debugger (i.e., when running the service, as opposed to starting it after installing it).

Thoughts on how to resolve this?

**Comment by markolbert** [comment]
The problem was due to insufficient permissions when running as the LocalSystem account, coupled to the fact that, apparently, when run under the Visual Studio debugger, the console app runs under the logged in user. If that user has greater permissions than LocalSystem, running the app under VS will work just fine...and then crash with that obscure error message when the system tries to run it as a standalone service.

A message to the effect that the app is running under a different account than the one specified in the HostFactory.Run() configuration would help alert people to this potential problem.

**Comment by sm-g** [comment]
I just solved same issue (immediately "Not Responding in a Timely Manner on Start"), which was caused by FileNotFoundException: 
```
new ConfigurationBuilder()
//                .SetBasePath(Directory.GetCurrentDirectory())
                .SetBasePath(Path.GetDirectoryName(typeof(Program).Assembly.Location))
                .AddJsonFile($"appsettings.json", optional: false)
```

see https://github.com/dasMulli/dotnet-win32-service/issues/54
