### ISSUE TITLE
Documentation Enhancement: Credentials Require Domain

### ISSUE THREAD

**Issue by markolbert** [Topshelf/Topshelf#410]
The documentation for the HostConfigurator::RunAs() method does not indicate that the supplied UserID must include a domain or system prefix (e.g., "Muddlehead\..."). I discovered this when the credential I supplied were rejected.

Folks experienced in writing services probably know this already. But it would come in handy for people who are still coming down the learning curve.

**Comment by jonathanbass** [comment]
@markolbert I have raised a PR for this change. Please let me know if you believe it should be worded differently. Cheers :)
