### ISSUE TITLE
Interfaces don't follow naming convention standards

### ISSUE THREAD

**Issue by InteXX** [Topshelf/Topshelf#415]
I'm trying to understand why Topshelf's interfaces don't follow the naming convention standard of beginning with a capital `I`.

This apparent oversight makes troubleshooting and debugging more difficult than would be otherwise. But I could be mistaken—it could be that it's not an oversight at all and that there's a good reason for this.

Can someone assist with an explanation?

**Comment by phatboyg** [comment]
It's the way it was chosen to be implemented at the time. It's highly unlikely to change.

**Comment by InteXX** [comment]
@phatboyg 

This will be easy to fix. It will do your users proud  :-)

1. Create the correctly-named interfaces
2. Retain the old ones, marking them as obsolete and referring devs to the new ones
3. At some safe date in the future, remove the old ones

Sample:

    Public Interface INew
      ReadOnly Property One As String
      ReadOnly Property Two As String
    End Interface



    <Obsolete("Will be removed. Use interface INew instead.")>
    Public Interface Old
      ReadOnly Property One As String
      ReadOnly Property Two As String
    End Interface



    Public Class Test
      Implements INew, Old

      Public ReadOnly Property One As String Implements INew.One, Old.One
      Public ReadOnly Property Two As String Implements INew.Two, Old.Two
    End Class
