### ISSUE TITLE
Command line consistency

### ISSUE THREAD

**Issue by biltongza** [Topshelf/Topshelf#416]
I've just spent hours trying to figure out why I kept getting logon failures after installing a topshelf service via the command line.

The command I was using was `Service.exe install -username:"DOMAIN\Username" -password:"password"`. I saw in the docs that's how you quote the password so I made the assumption the same format is used for username, but it turns out that's wrong. If you include the colon in `-username:"DOMAIN\Username"`, it _looks_ like the service installs with the correct username but it never works. Take out the colon (i.e. `-username "DOMAIN\Username"`), and suddenly things start working like they should.

I feel like that's a very easy mistake to make and I don't understand why there would be inconsistency between command line arguments like this.

**Comment by phatboyg** [comment]
If the argument value doesn't have any special characters, it's easy to inline as `-username:Frank` but if you have spaces or characters, it's, `-username "Frank"`. Not inconsistent, I think the help text shows it as well.
