### ISSUE TITLE
Required .NET Version

### ISSUE THREAD

**Issue by darinkes** [Topshelf/Topshelf#421]
I'm trying to update Topshelf Nuget from 3.2.0 to current stable release 4.0.3, cause i need the PowerEvents-Feature. But Visual Studio complains that it can't find Assemblies for .NET 4.0 in the Package.

According to https://topshelf.readthedocs.io/en/latest/installation/prerequisites.html#net-framework
.NET 4.0 should work. Is this still correct?

**Comment by phatboyg** [comment]
.NET 4.5.2 is the lowest version supported.
