### ISSUE TITLE
Question: how to mark service as safe

### ISSUE THREAD

**Issue by KevinCocquyt39** [Topshelf/Topshelf#423]
Dear,

Not really an issue but something that is unclear to me. I'm currently developing a self-hosting service which listens to a certain port using TopShelf. Once installed on a client's computer, it happens that the Windows Defender deletes the service. We can opt to add an exception to the Windows Defender but I was wondering if signing the assembly would do the trick for being safe for all virus scanners?

If so, is there a tutorial/blog on how to do it? Can't find anything searching the internet...

Kind regards,
Kevin Cocquyt

**Comment by phatboyg** [comment]
Quit writing Malware?

**Comment by phatboyg** [comment]
Joking, but seriously, why would Defender delete it? I've never seen this happen on my machine.

**Comment by KevinCocquyt39** [comment]
It's something our client informed us on. That the folder where the service was located (exe) from where it was installed got deleted and he asked us if we could create some sort of exception for our service. Dunno really what to do with it or why it would be an issue but apparently for some, it is.

**Comment by phatboyg** [comment]
Sounds like an issue with their Malware detection software, that's where exceptions are usually specified. 

Maybe some type of code signing on the EXE?
