### ISSUE TITLE
How to Get current Full ServiceName (with Instance Name) on BeforeUnistall ?

### ISSUE THREAD

**Issue by victorperez2911** [Topshelf/Topshelf#424]
Hi

On AfterInstall action, a parameter of type installHostSettings hold a property called ServiceName, how to get this in a BeforeUninstall delegate  ?

Victor Perez

**Comment by phatboyg** [comment]
That would be nice, for sure. I think the Settings need to be exposed in many places where they are currently missing.

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
