### ISSUE TITLE
Forcibly throwing exception results in Blue screen

### ISSUE THREAD

**Issue by AlexKeySmith** [Topshelf/Topshelf#427]
I'm finding if I throw an exception within a TPL action block, it results in:

Bluescreen with the error code BUGCHECK_CRITICAL_PROCESS and the windows error reporting has the exe name in the bucket id.

Reading through https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0xef--critical-process-died I can see some debugging techniques.

However, I wondered if there is anything in topshelf that I should focus into?

The service seems to restart itself a couple of times first of all, I wonder if it could be the RestartComputer recovery option?

It seems unlikely it being anything to do with .net / topshelf that would cause a BSOD. I'm using a UDPClient which would have unmanaged resources in the background, but even then it seems unrelated, perhaps more likely to do with a misbehaving virus scanner, driver or the error reporter itself or something.....

However I've repro'd it reliably a few times and it doesn't occur when running in the console, only as a service. 

Any ideas?

**Comment by maxcherednik** [comment]
@AlexKeySmith I don't think we can speak about details or possible causes without [minimal reproducible example](https://stackoverflow.com/help/mcve)

**Comment by AlexKeySmith** [comment]
Sorry guys, I never got around again to repro-ing this and working on a different project at the moment.

I'm sure we would of heard from the community if it were affecting anyone else.

Happy to close it for the moment until I get back to that project and I'll see if it happens again?

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
