### ISSUE TITLE
Question: redirecting STDOUT to a file (while running as a service)

### ISSUE THREAD

**Issue by omar-monitex** [Topshelf/Topshelf#434]
Hi,

Running `ServiceX.exe >> C:\logs\ServiceX.log` in Windows CMD _appends_ all STDOUT to the specified file.

**Is there a way to configure TopShelf to do the same while running as a service?**

_Some context..._
I configured the logging engine (using log4net) and it was useful but, I have some external components (not under my control) writing to STDOUT info that I'd like to log (ideally through built-in logging of TopShelf or just basic `STDOUT >> file` as in the example above).

Any ideas/pointers much appreciated...
Thanks

**Comment by mario-d-s** [comment]
You should use the [`Console.SetOut`](https://msdn.microsoft.com/en-us/library/system.console.setout(v=vs.110).aspx) method. I'll leave the exercise of hooking a TextWriter to Log4Net up to you.

**Comment by omar-monitex** [comment]
Thank you Mario!
