### ISSUE TITLE
Should Log.CloseAndFlush be called in SerilogLogWriterFactory.Shutdown method?

### ISSUE THREAD

**Issue by mvacha** [Topshelf/Topshelf#435]
Hi, I'm thinking whether `TopShelf.Serilog.SerilogLogWriterFactory` should handle the closing of the Serilog Logger passed by `UseSerilog` method. 
 - In case it is not called, Logger may not flush the buffer and error messages may get lost. 
 - But it is also a breaking change, because all the logs created after the `CloseAndFlush()` get lost.
 - Both `Topshelf.NLog` and `TopShelf.Log4Net` have the Shutdown implemented.

Is it just a small inconsistency or is there some logic I missed?

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
