### ISSUE TITLE
Programmatically accessing command line parameters

### ISSUE THREAD

**Issue by toadicusrex** [Topshelf/Topshelf#442]
We have a situation where our build servers deploy our TopShelf services and install them using commandline arguments.  The issue is trying to set up our logging service (we're using Serilog).  We don't want to log errors to the same place as the rest of the app because of our devops team requirements; we want to log to the event log.

The problem is that we have multiple instances of the service running on the server with different instance names, which are provided when the build server installs via the command line.

However, it appears that I need to provide the source to the event logger, and I haven't been able to find a programmatic way to access the command line instance provided at install until the configuration starts, but it requires the log at that point (at least, that's what it looks like.. i.e. 

```
`var exitCode = HostFactory.Run(config =>
				{
					config.Service<ServiceHost>(s =>
					{
						// Let Topshelf use it
						s.ConstructUsing(settings =>
						{
							**//Settings are available here, but it's too late for me to use the instance name to create the event log source.... :(**
							return new ServiceHost(hostUri);
						});
				        s.WhenStarted((service, control) =>...)
					s.WhenStopped((service, control) => ...)
					config.OnException(ex =>...)
					config.EnableServiceRecovery(recoveryOptions =>...)
					config.RunAsPrompt();
					config.StartAutomatically();
					config.SetDescription("Optiv TPRM API Services Host Application");
					config.SetDisplayName("Optiv TPRM API Services");
					config.SetServiceName("OptivTPRM-API");
					config.SetInstanceName(instanceName);
					config.EnableSessionChanged();
					config.EnableShutdown();
					config.EnablePauseAndContinue();
					config.UseAssemblyInfoForServiceInfo();
					**config.UseSerilog(logger);**
				});`

```
So is there a way for me to access the instance name before the configuration starts?  Thanks for this wonderful library.  If this is possible I would be so grateful for a point in the right direction .... otherwise I'll just have to not log some things. :(

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
