### ISSUE TITLE
netcoreapp2.0 missing methods

### ISSUE THREAD

**Issue by haf** [Topshelf/Topshelf#444]
Many of the extension methods of the latest release fail to compile in net471/netcoreapp2.0 mode:

<img width="1142" alt="screen shot 2018-05-24 at 15 19 24" src="https://user-images.githubusercontent.com/193115/40487958-ead41b08-5f65-11e8-9009-5d4fe42367a5.png">

`paket.lock`:

```
+    Topshelf (4.0.4.148-develop)
+      Microsoft.Windows.Compatibility (>= 2.0.0-rc1) - restriction: || (&& (== net461) (< net452) (>= netstandard2.0)) (== netcoreapp2.0) (== netstandard2.0)
```

If these functions don't exist it would be neat to get warnings at runtime but keeping the API the same. Perhaps PRs can solve the missing functionality?

**Comment by phatboyg** [comment]
Many of those types do not exist in .NET Core, even with the Windows compatibility package. I'd rather have it fail to compile than answer 1,000,000 questions of why "project.exe install" is not working from the command line on Linux...

**Comment by haf** [comment]
Yes indeed. However, it would be possible for Topshelf to shim e.g. the restart/service recovery setting (probably the most important one there)

**Comment by haf** [comment]
Well, in a sense yes; what I asked for. But you have a point too, so I don't want to take away too much from that; perhaps log a warning on stderr if using these APIs with noop-behaviour?
