### ISSUE TITLE
windows service set environment variable

### ISSUE THREAD

**Issue by kadkin** [Topshelf/Topshelf#446]
Is it possible to set environment parameters for the service?

**Comment by kadkin** [comment]
something like that?
nssm set <servicename> AppEnvironment key=value

**Comment by phatboyg** [comment]
I don't know what that is, honestly.

This should help: https://docs.microsoft.com/en-us/dotnet/api/system.environment.getenvironmentvariable?view=netframework-4.7.2#System_Environment_GetEnvironmentVariable_System_String_System_EnvironmentVariableTarget_

**Comment by kadkin** [comment]
http://workblog.pilin.name/2013/03/service-environment-variables.html

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.

**Comment by kendallb** [comment]
I was just looking for this feature myself. Windows Services get their environment variables from the registry, so if you want to start a windows service and provide environment variables to be passed in when it starts, you need to set them in the registry. It's not hard to do that stuff yourself, but it would actually be nice if there was a way to do that with TopShelf so it would do it for us (and then hopefully be more portable to other systems as I suspect it's quite different on Linux).

A good example of what I am looking to use it for, is to set up DataDog APM tracing for our background tasks, which needs to be set before the service starts:

https://docs.datadoghq.com/tracing/setup_overview/setup/dotnet-framework/?tab=environmentvariables

Not sure how this would best be implemented in TopShelf, but I would consider doing a PR for it but I have not really dug into the code for TopShelf yet, just used it for years :)
