### ISSUE TITLE
Microsoft Configuration and Logging Extensions Released?

### ISSUE THREAD

**Issue by mhsimkin** [Topshelf/Topshelf#452]
I grabbed version 4.0.4 from Nuget.  That package doesn't contain the Microsoft Configuration and Logging Extensions.  Where can I find the Nuget package that contains those extensions?

Also, are there any examples on how to use them?

Thanks

-marc

**Comment by phatboyg** [comment]
They'll be in the 4.1 release, which is in pre-release on NuGet now.
