### ISSUE TITLE
Topshelf and Microsoft DI

### ISSUE THREAD

**Issue by mhsimkin** [Topshelf/Topshelf#453]
Are there any examples on how to use Topshelf with the Microsoft.Extensions.DependencyInjection?

Thanks

-marc

**Comment by poteb** [comment]
I'm a bit curious, why would you want to DI Topshelf? Topshelf is for installation and startup, DI is normally handled after this.

**Comment by mhsimkin** [comment]
I was hoping that Topshelf would be DI aware so that I could avoid writing code like:

`           var provider = services.BuildServiceProvider();
            var winService = provider.GetService<MyServiceClass>();
            HostFactory.Run(x => {
                   x.Service<MyServiceClass>(s => {
                         s.ConstructUsing(name => winService);
                   }
            }
`
I need to be able have DI resolve the parameters to the constructor of my service class.

-marc

**Comment by phatboyg** [comment]
You should only configure the container in the service factory method.

```
HostFactory.Run(x => 
{
    x.Service<MyServiceClass>(s => 
    {
        s.ConstructUsing(settings =>
        {
            var provider = services.BuildServiceProvider();
            return provider.GetService<MyServiceClass>();
        });
    });
});
```
