### ISSUE TITLE
Decorator class for Assembly to improve test coverage

### ISSUE THREAD

**Issue by cjvirtucio87** [Topshelf/Topshelf#458]
We currently leverage static methods of the [Assembly](https://msdn.microsoft.com/en-us/library/system.reflection.assembly(v=vs.110).aspx) class in the codebase. For instance, [we retrieve the path of the assembly in the default application domain](https://github.com/Topshelf/Topshelf/blob/ce219df706d6acc7dc35bfc81f1ed1fab317bf07/src/Topshelf/Runtime/Windows/HostServiceInstaller.cs#L154) and pass it to the command line action to be executed.

Unfortunately, the method for retrieving the above information [returns null when called in an NUnit test method](https://sourceforge.net/p/nunit/bugs/566/#fb2b). It'd be great if we could have a decorator class that we can mock in unit tests and use to improve coverage. Specifically, I'd imagine there'd be an `interface` that we could mock. The implementations would just get injected through a setter (though the client code would instantiate the _real_ implementation by default).

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
