### ISSUE TITLE
Wrong Exit code 

### ISSUE THREAD

**Issue by AndrewSav** [Topshelf/Topshelf#461]
If we look at this line: 

https://github.com/Topshelf/Topshelf/blob/22baba8dff7ba47b12b761b03c15006a0d3cd44c/src/Topshelf/Runtime/Windows/WindowsServiceHost.cs#L150

We see, that if there is an exception thrown during service start up on windows service host [TopshelfExitCode.StartServiceFailed](https://github.com/Topshelf/Topshelf/blob/22baba8dff7ba47b12b761b03c15006a0d3cd44c/src/Topshelf/TopshelfExitCode.cs#L22) got assigned to [ServiceBase.ExitCode](https://msdn.microsoft.com/en-us/library/system.serviceprocess.servicebase.exitcode(v=vs.110).aspx).

This exit code is passed back to Windows Service Control Manager and is expected to be [Windows Error Code](https://docs.microsoft.com/en-us/windows/desktop/debug/system-error-codes--0-499-).

In our case number `5` is passed which corresponds to `Access Denied`. Needless to say that the actual exception does not have to have anything to do with `Access Denied`.

This means that TopShelf is passing wrong and misleading error code.

**Comment by maxcherednik** [comment]
Oh, that was really annoying some time ago. I did not figure out - why would it be 'Access Denied' error message.

Here are some thoughts on windows service fail messages:
https://www.devopsonwindows.com/handle-windows-service-errors/

The right error code would be: 
1064 An exception occurred in the service when handling the control request.

**Comment by maxcherednik** [comment]
@phatboyg what do you think of this? Shall I create a PR for this if it fits long term plans?

**Comment by phatboyg** [comment]
A fix would be great.

**Comment by willsmith9182** [comment]
When's this going to be released... I notice it's in a pre-release version already

**Comment by AndrewSav** [comment]
Hopefully before the end of the year ;)
