### ISSUE TITLE
Window Shutdown Event

### ISSUE THREAD

**Issue by HaroldTexas** [Topshelf/Topshelf#463]
I'm not able to get the Shutdown() to be called when Windows is restarted or shutdown.  The Stop() is called when the server is stopped via the SC.

I'm assuming that if EnableShutdown() is called and WhenShutdown configured then WhenShutdown() should be called when Windows is either restarted or shutdown.

Can someone point me in the right direction?

        private static void Main(string[] args)
        {
            try
            {
                Log($"Main() - app startup");

                HostFactory.Run(x =>
                {
                    x.SetDescription("Test TopShelf Window Service.");
                    x.SetDisplayName("TopShelf Window Service");
                    x.SetServiceName("TopShelfWindowService");
                    x.EnableShutdown();

                    x.Service<Controller>(sc =>
                    {
                        sc.ConstructUsing(name => new Controller());
                        sc.WhenStarted(tc => tc.Start());
                        sc.WhenStopped(tc => tc.Stop());
                        sc.WhenShutdown(tc => tc.Shutdown());
                    });
                    //x.RunAs("userid", "password");
                });

            }
            catch (Exception ex)
            {
                Log($"Main() - {ex}");

                throw;
            }
        }

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
