### ISSUE TITLE
ConsoleRunHost Exception Logging

### ISSUE THREAD

**Issue by meinsiedler** [Topshelf/Topshelf#464]
Hi!

We are using the `OnException` method to register a callback for handling exceptions. In that callback, we create a custom log entry like so:

```csharp
service.OnException(ex =>
{
    // some more logic ...
    Log.Fatal(ex, "An unhandled exception occurred in service.") // our custom log entry (simplified)
});
```

When running the service as console application, unhandled exceptions are logged twice, because in the `ConsoleRunHost` implementation, an error is logged too:  https://github.com/Topshelf/Topshelf/blob/22baba8dff7ba47b12b761b03c15006a0d3cd44c/src/Topshelf/Hosts/ConsoleRunHost.cs#L106

Any thoughts on how to suppress the hardcoded `_log.Error(...)` call in the `ConsoleRunHost`?

**Comment by maxcherednik** [comment]
@meinsiedler usually the logging of the internals of the library should be disabled - this is usually done with the logger configuration.

**Comment by meinsiedler** [comment]
@maxcherednik Thank you for your response.

I'm not quite sure how to turn off _only_ the internal log messages of the library. Do you have an example how to achieve that? (We are using Serilog btw.)

For our setup, it would actually be OK to log internal messages - especially the Information messages when a service starts or stops are relevant. So maybe there is a way to just ignore the above stated Error message in case of an exception?

**Comment by maxcherednik** [comment]
This is how it's done to hide asp.net core internal logging.

https://github.com/serilog/serilog-aspnetcore#instructions

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
