### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by schh** [Topshelf/Topshelf#466]
I know this has bed discussed before, but i would like to know why this behaviour is different from installing a regular windows service using sc.exe or wix.

When installing with TopShelf i get access denied when starting and trying to connect to my local sqlserver with integrated security. I have to set service to run as the logged in user, or add the machineaccount to the SQL server.

Service runs as localsystem, and this is never an issue when installing a regular windows service.

I know this has bed discussed before, but i would like to know why this behaviour is different from installing a regular windows service using sc.exe or wix.

**Comment by maxcherednik** [comment]
The reason explained here:

https://github.com/Topshelf/Topshelf/issues/466

wbr, Maxim Cherednik

**Comment by yuriburk** [comment]
Did you find a solution?

**Comment by schh** [comment]
No i did not, the linked issue in the reply was wrong.

**Comment by maxcherednik** [comment]
@schh Sorry, here is the link: https://github.com/Topshelf/Topshelf/issues/461

**Comment by schh** [comment]
Yes that is also wrong. My question is why i dont get access to domainresources like sqlserver as localsystem by default as i do when installing with sc.exe or wix. Topshelf seems to handle this differently somehow.

Even on my local machine i cant connect to my local sqlserver as localsystem. This always worked fine using our traditional windowsservices.

**Comment by igloo15** [comment]
I am running into the same issue when running as service my app can't even create logs because its permissions are denied to the folder it is in.

**Comment by maxcherednik** [comment]
@igloo15 under which account your service is installed and executed?

**Comment by igloo15** [comment]
@maxcherednik both Local System and Local Service. When I run the application normally the log is created fine but not when its installed as a service.

**Comment by davidshen84** [comment]
@igloo15 when writing log, what is the path of the log file? When running as service, the current working directory of the service is `%windir%\system32`. You should always use/configure an absolute log file path.

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.

**Comment by xorrot16** [comment]
for others my problem was that I had Registered the Service with:

SC Create "abc" binpath="c:\mystuff\myservice.exe"

configure.SetServiceName("bla");//error
configure.SetDisplayName("bla");//error because of "bla" string

that dis not work set it how you registered it:
configure.SetServiceName("abc");
configure.SetDisplayName("abc");

this worked for me 

no need for 
var myThread = new Thread(new ThreadStart(StartThread));
                myThread.IsBackground = true;  
                myThread.Start();

public void StartThread{
             while (true)
              {
                   Thread.Sleep(1000);                    
              }
}


maybe there is someone with the same idiotic problem I faced wasting too much time for things that could be done easily :)
