### ISSUE TITLE
Command line arguments are case-sensitive

### ISSUE THREAD

**Issue by miketaber** [Topshelf/Topshelf#469]
I spent 5 hours trying to troubleshoot why a Topshelf service wasn't being installed properly, only to find that it was because the command line arguments appear to be case-sensitive and are otherwise ignored if not specified in the correct case.

`myapp.exe install -serviceName "MyApp" -displayname "MyApp"`

In the above case, I'd had -displayname correct, but -serviceName was mixed case so it sort of worked but wasn't clear exactly what was wrong. I likely typed it that way out of habit more than anything else.

Given that there's a distinct set of options for the command line parameters, I'd have thought that -serviceName would have been recognized as -servicename and it would have just worked properly anyway. This was a Windows Server command line and it's just odd that it was case-sensitive because that's not usually the case with command line arguments in Windows.

**Comment by phatboyg** [comment]
They are, in fact, case sensitive.

It's unlikely that this will be changed.
