### ISSUE TITLE
4.1.0.117-develop retracted from nuget, but did exactly what I wanted

### ISSUE THREAD

**Issue by zidad** [Topshelf/Topshelf#470]
I was using 4.1.0.117-develop, which was retracted from nuget.

I know the service installation didn't work for .NET Core 2.0 Apps, but for me this package worked perfectly, because I could easily multitarget net472 and install as a service, and target netcoreapp2.0 and run in docker. And it had no other dependencies. 

What other TopShelf build will give me those possibilities?
Can I keep using it despite it being retracted, or are there other known fundamental problems with it? 
Would you consider publishing a version like this again as prerelease so I can at least continue using it?

I can't use 4.0.4.161-develop because the TopShelf.ServiceInstaller dependency can't be found.
https://github.com/Topshelf/Topshelf/issues/460

Thanks!

Wiebe

**Comment by phatboyg** [comment]
THe latest packages are now available.

**Comment by zidad** [comment]
Thanks so much!
