### ISSUE TITLE
Not Seeing the Service Under "Services" in Windows

### ISSUE THREAD

**Issue by DanJ210** [Topshelf/Topshelf#471]
Hello, sorry this might be a really newb issue. I'm using a .Net 4.6.1 Console App.

I am new to this but when I first started with a very basic service I was seeing it show up under the Services panel in Windows. But now I don't see it anywhere. My code is mostly straight from docs. Below is my configure service method and the `main()` method within `Program.cs` runs this method like standard. The service starts because the timer and code I have within the `start()` method runs so I have no problem with the application, it works. But I can no longer find the service name anywhere under the Services panel. I do build the application and use the .exe to run it on other machines including the one I'm building it on and I don't see the name anywhere on other machines either. 

Is using the .exe why I'm not seeing a service name? No service is being installed? When I debug the application I also see no service name but I swear that I used to. What am I not understanding?

```
internal static void Configure()
		{
			HostFactory.Run(configure =>
			{
				configure.Service< Initializer > (service =>
				{
					service.ConstructUsing(s => new Initializer());
					service.WhenStarted(s => s.Start());
					service.WhenStopped(s => s.Stop());
				});
				configure.RunAsLocalSystem();
				configure.SetServiceName("DataRefresherService");
				configure.SetDisplayName("DataRefresher");
				configure.SetDescription("Refreshes Public Database with NetSuite Data");
			});
		}
```

**Comment by StormShadow86** [comment]
Hi,

With the exe you builded, did you try to install like in the example here: https://topshelf.readthedocs.io/en/latest/overview/commandline.html

Ex: in cmd, try DataRefresher.exe install -autostart and check if it shows.

**Comment by DanJ210** [comment]
Yes it looks like that made it show up. Except autostart took two hyphens and it didn't actually start itself, I still had to manually start it. Thank you!

My only other question would be the command line interface that comes up when you run the .exe by double clicking. Is there any way to get that back while the service is running? Or is that not something I should be relying on to know the status of the service as it runs day by day?

**Comment by chrkon** [comment]
Dear DanJ210,
I am not sure if I understand you right, but if your service is installed, then it is running in the background without the commandline interface. The windows system will handle starting and stoping, if you have used the "-autostart" option.
There should be no need to start your DataRefresher.exe by double click.

**Comment by DanJ210** [comment]
@chrkon So when you double click the .exe a command line interface comes up, do you know that? When you install the service via command line the command line interface does not come up, the service just starts and runs in the background.

I was only wondering if there was a way to get the command line interface back without double clicking the .exe to run. Not a big deal. But if you double click the .exe you'll clearly see a command window come up telling you what the service is doing. This doesn't come up unless you double click. Very easy to notice.

Does this make sense?
