### ISSUE TITLE
Service does not start

### ISSUE THREAD

**Issue by xplatsolutions** [Topshelf/Topshelf#473]
Updating to latest develop version `4.1.0.169-develop` and installing the service `Executable.exe install` locally on my Windows 7 machine gives me the following error when I try to start it from devices management.

This is a .NET Core 2.0 console app.

> Windows could not start the VRSK.UW.FallbackMonitoring.Service service on Local Computer.
> Error 1053: The service did not respond to the start or control request in a timely fashion.

Below find the HostConfiguration code.

```
            var rc = HostFactory.Run(x =>
            {
                x.Service<StartupMain>(s =>
                {
                    s.ConstructUsing(name => new StartupMain(Settings, LoggerFactory));
                    s.WhenStarted(tc => tc.Start());
                    s.WhenStopped(tc => tc.Stop());
                });

                x.RunAsNetworkService();
                x.StartAutomatically();
                x.SetDescription(serviceDescription);
                x.SetDisplayName(serviceName);
                x.SetServiceName(serviceName);

                x.EnableServiceRecovery(r =>
                {
                    r.RestartService(0);
                    r.OnCrashOnly();
                    r.SetResetPeriod(1);
                });
            });

            var exitCode = (int)Convert.ChangeType(rc, rc.GetTypeCode());
            Environment.ExitCode = exitCode;
```

Any ideas?

**Comment by ycc3000** [comment]
try this?
static void Main(string[] args)
{
    string path = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
    Directory.SetCurrentDirectory(path);
    ....
}

**Comment by xplatsolutions** [comment]
Looks like it did the trick! Thanks :-)
