### ISSUE TITLE
WindowsServiceHost.Run() throws an exception when returning

### ISSUE THREAD

**Issue by GeorgeGee** [Topshelf/Topshelf#477]
`WindowsServiceHost.Run()` returns a `TopshelfExitCode` by parsing `ServiceBase.ExitCode` as an enum, however 9 days ago `TopshelfExitCode` was changed to be a **struct** instead of an enum. This causes an exception to be thrown when `WindowsServiceHost.Run()` returns:

```
[2018-10-01 07:57:28.677 Error] [] The service terminated abnormally
System.ArgumentException: Type provided must be an Enum.
Parameter name: enumType
   at System.Enum.ToObject(Type enumType, Int32 value)
   at Topshelf.Runtime.Windows.WindowsServiceHost.Run()
   at Topshelf.HostFactory.Run(Action`1 configureCallback)
```

Bug was introduced here: https://github.com/Topshelf/Topshelf/commit/d47f7a17312a7d35ce012eb10b3c0c7039914f67#diff-d21b3cd5c675ec89e50e60b77e005c42

For now a workaround is to use 4.1.0 stable.

**Comment by phatboyg** [comment]
@maxcherednik see my comment, please change the struct back to an enum.

**Comment by maxcherednik** [comment]
@GeorgeGee Could you please review the fix? I didn't quite get how managed to get this?

**Comment by GeorgeGee** [comment]
@maxcherednik I've reviewed and approved the PR. I was experiencing this when I would stop the service in services.msc.
