### ISSUE TITLE
When install and start in same command, username/password is ignored

### ISSUE THREAD

**Issue by johnDet** [Topshelf/Topshelf#483]
The commandline:
**Service.exe install start -username "domain\name" -password "password"**
installs and starts service as LocalSystem, not as "domain\name"

The commandlines:
**Service.exe install -username "domain\name" -password "password"
Service.exe start**
installs and starts service as "domain\name"

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
