### ISSUE TITLE
Installing a .NET Core 2.1 framework dependent console application as a Windows Service 

### ISSUE THREAD

**Issue by lazkanelov** [Topshelf/Topshelf#485]
Hello,

I'm trying to install & run a .NET Core 2.1 console application, deployed as a framework dependent app, as a Windows service without success. 

The service has been installed successfully with the _install_ command, but cannot start, because the image path of the service in the registry points to a .EXE file which is incorrect in the case of non-self-contained apps since there's no .EXE file. The service starts successfully and works fine with the _dotnet_ _<service.dll>_ command, but currently, there's no way to register it as a Windows service, without using the self-contained build option.

Is there any way to install & register framework dependent app as a Windows Service or this works only for self-contained apps?

Kind regards,
Lazar

**Comment by davidshen84** [comment]
I hit by this problem as well. I checked the code and found [this comment][1]. I trust they have a good reason to do so.

I checked the Internet, and I found publishing a netcore application in [SCD][2] is quite simply.  But if you **really** cannot deploy your netcore application in SCD, you can still use the `sc` command to create a Windows service.

    sc create "YourNetcoreService" binPath= "dotnet c:\full\path\to\the\service.dll"

Please check `sc create /?` for more options. However, the target machine **must** have the compatible netcore runtime.

[1]: https://github.com/Topshelf/Topshelf/blob/develop/src/Topshelf/Runtime/Windows/HostServiceInstaller.cs#L160

[2]: https://docs.microsoft.com/en-us/dotnet/core/deploying/

**Comment by boekabart** [comment]
To be honest, I don't see a good reason for the replacement. The _actual_ thing the installer should do, is use the path of the `dotnet` executable used to run the dll, as the service path, with the full path of the actual DLL as the first argument.

IMO, the whole point of using Topshelf for netcore applications is, by now, the self-installing feature, so NOT adding this, kind of kills the whole point of TopShelf (as the 'servicehost' itself is now easy to add in dot net core apps).

I've tested the above theory by running
`dotnet myApp.dll install --localsystem`
and then going into the registry and replacing the `e:\test\myApp.exe` that topshelf generated, with `"c:\program files\dotnet\dotnet.exe" "e:\test\myapp.dll"`
After doing that, the service starts and works perfectly.

**Comment by gavi** [comment]
I am facing the same problem and appreciate the workarounds provided in this thread. But i agree with @boekabart that this should work seamlessly with the `install`

**Comment by wuzhenda** [comment]
so  @boekabart 's  method is the best solution currently? or should we  compile  output  as SCD?

**Comment by davidshen84** [comment]
But from a netcore application point of view, deploying the service in SCD should be an option. Actually, SCD is one of netcore application's sell-point.

I think it would be nice to provide options to choose how the service execution command is generated.

**Comment by boekabart** [comment]
Seems like PR #529 fixes this exactly as I envisioned!

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
