### ISSUE TITLE
Integrate CommandLineParser library

### ISSUE THREAD

**Issue by davidshen84** [Topshelf/Topshelf#486]
I think unless there're some compelling reasons that Topshelf must have its won [CommandLineParser][1], I suggest it should integrate with the https://github.com/commandlineparser/commandline project.

[1]: https://github.com/Topshelf/Topshelf/tree/develop/src/Topshelf/Configuration/CommandLineParser

**Comment by sgrassie** [comment]
What, exactly, are the compelling reasons for TopShelf to integrate with that particular command line parsing library?

**Comment by davidshen84** [comment]
Like shared knowledge, so people don't have to read the code and understand how to use the home-brewed library to add/update a new command.

Benefit from the work of the community, so new features, bug fixes, improvements are integrated into this library faster.

Just some quick thought.

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
