### ISSUE TITLE
Configuring Logging console vs window services.

### ISSUE THREAD

**Issue by shashikumaarb** [Topshelf/Topshelf#488]
when I run the consoleapp, app is able to find the ILogger but when its running as a windows service it isn't writting the logs but it does not complain either and for sure rest of the service functionality is working as I see the events are making into datastore.

static void Main(string[] args)
        {
            ConfigureIoc();
			//var configuration = DependencyInjector.Retrieve<Serilog.ILogger>();														
			var logger = DependencyInjector.Retrieve<Microsoft.Extensions.Logging.ILogger>();
			var topshelfConfig = new ServiceConfig(eventListener, logger);

			logger.LogInformation("Configuring Topshelf1");

			HostFactory.Run(serviceConfig =>
            {
				//serviceConfig.UseSerilog(configuration);
				serviceConfig.UseLoggingExtensions(DependencyInjector.Retrieve<ILoggerFactory>());				
				serviceConfig.Service<ServiceConfig>(serviceInstance =>
                {
                    serviceInstance.ConstructUsing(
                        () => topshelfConfig);

                    serviceInstance.WhenStarted(
                        execute => { execute.Start(); });

                    serviceInstance.WhenStopped(
                        execute => execute.Stop());

                    serviceInstance.WhenPaused(
                        execute => execute.Stop());

                    serviceInstance.WhenContinued(
                        execute => execute.Start());

                    serviceInstance.WhenCustomCommandReceived((execute, hostControl, commandNumber) => { execute.CustomCommand(commandNumber); });
                });
                serviceConfig.EnableServiceRecovery(recoveryOptions =>
                {
                    recoveryOptions.RestartService(1);
                });
                serviceConfig.EnablePauseAndContinue();
                serviceConfig.SetServiceName(ConfigurationManager.AppSettings["Aim.Ess.Case.EventProcessor.ServiceName"]);
                serviceConfig.SetDisplayName(ConfigurationManager.AppSettings["Aim.Ess.Case.EventProcessor.ServiceDispalyName"]);
                serviceConfig.SetDescription(ConfigurationManager.AppSettings["Aim.Ess.Case.EventProcessor.ServiceNameDesc"]);

                serviceConfig.StartAutomatically();
                serviceConfig.OnException(onException);
            });
        }

I do see some logs being spit out but not when the events are coming in

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
