### ISSUE TITLE
WCF endPoints with topshelf

### ISSUE THREAD

**Issue by alimhabib** [Topshelf/Topshelf#489]
I have a configuration file with services endpoint like this
`  <system.serviceModel>

<services>
  <service name="zzz"  behaviorConfiguration="MetaDataBehvior" >
    <endpoint  address="net.tcp://localhost:9002/testService" binding="netTcpBinding" contract="Izzz" />
    <endpoint  address="net.tcp://localhost:9010/testService" binding="netTcpBinding" contract="Izzz" />
    <endpoint  address="net.tcp://localhost:9002/testService/mex" binding="mexTcpBinding" contract="IMetadataExchange" />
  </service>`

am using TopShelf for ServiceHost something like

` m_svcHost = new ServiceHost(zzz.Instance, new Uri[] { });
                m_svcHost.Open(); `

which get its configuration from the app.config , now I want to unit test my work so my question is how to stop one of those endpoints in a proper way so if I have three endpoints I want to close one or two and test my client if it still can use the remaining and so on. For example close the endpoint on port 9010

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
