### ISSUE TITLE
Topshelf SetAsLocalService doesn't work

### ISSUE THREAD

**Issue by alimhabib** [Topshelf/Topshelf#491]
I configure the service as following 

            var rc = HostFactory.Run(x =>
            {
                // This will change the HostLogger to use NLog.
                x.UseNLog();
                x.Service<dfdfdg>(s =>
                {

                    s.ConstructUsing(name => new RABTWindowsService());
                    s.WhenStarted(tc => tc.Start());
                    s.WhenStopped(tc => tc.Stop());
                });

                x.RunAsLocalService();
                x.OnException(exception =>
                {
                    LogManager.GetCurrentClassLogger().Fatal(exception, exception.Message);
                });

                x.SetDescription("xxxxxxxxxx");
                x.SetDisplayName("xxxxxxxxxx");
                x.SetServiceName("xxxxxxxxxx");

                // Recovery of the service 
                x.EnableServiceRecovery(r =>
                {
                    //you can have up to three of these
                    r.RestartService(0);
                    //number of days until the error count resets
                    r.SetResetPeriod(1);
                });
            });

            var exitCode = (int)Convert.ChangeType(rc, rc.GetTypeCode());
            Environment.ExitCode = exitCode;

I can't find the service in services, instead, I see it in the services tab in task manager any idea how to make it works properlly and attached to localservice group

**Comment by phatboyg** [comment]
Did you install it?

yourservice.exe install

**Comment by alimhabib** [comment]
> Did you install it?
> 
> yourservice.exe install

yah I run this in command as adminstartion

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
