### ISSUE TITLE
install / Uninstall service powershell

### ISSUE THREAD

**Issue by alimhabib** [Topshelf/Topshelf#501]
Hello All, 

am trying to uninstall/Install the service from PowerShell but it failed if anyone can help me firgure out the issue 
`& $PSScriptRoot'\Service1.exe' uninstall --sudo`
tried local system 
		`& $PSScriptRoot'\Service1.exe'  install --localsystem –autostart `	
Also with user name and passowrd 
		`& $PSScriptRoot'\Service1.exe'  install -username "$username" -password "$password" –autostart`

nothing work if you can correct those three commands for me please

**Comment by wolfsheep** [comment]
Thanks

**Comment by wolfsheep** [comment]
> Hello All,
> 
> am trying to uninstall/Install the service from PowerShell but it failed if anyone can help me firgure out the issue
> `& $PSScriptRoot'\Service1.exe' uninstall --sudo`
> tried local system
> `& $PSScriptRoot'\Service1.exe' install --localsystem –autostart `
> Also with user name and passowrd
> `& $PSScriptRoot'\Service1.exe' install -username "$username" -password "$password" –autostart`
> 
> nothing work if you can correct those three commands for me please

thanks
