### ISSUE TITLE
Document ServiceControl.cs

### ISSUE THREAD

**Issue by HugoRoss** [Topshelf/Topshelf#507]
Please add the documentation to the start and stop methods of interface ServiceControl.cs 

What is expected as the result? True if successful, false otherwise?

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.

**Comment by jakoss** [comment]
I believe that @HugoRoss was asking for information, i'm seeking the same thing right now
