### ISSUE TITLE
Specify Recovery Reset Period As Timespan

### ISSUE THREAD

**Issue by innominate227** [Topshelf/Topshelf#508]
Windows let you specify the reset period in seconds, but topshelf limits you to days.  User should be able to specify a timespan instead.

```
x.EnableServiceRecovery(r =>
{
    r.SetResetPeriod(TimeSpan.FromMinutes(60));
});
```

Windows Documentation:
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-xp/bb490995(v=technet.10)
Ctrl-F "ErrorFreePeriod"

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
