### ISSUE TITLE
Topshelf want start, after signing application

### ISSUE THREAD

**Issue by goleague-dev** [Topshelf/Topshelf#509]
When I sign the assembly of my app, I get the following error through topshelf.
NET Framework 4.6

Configuration Result:
[Success] Name GOAcService
[Success] DisplayName goleague.eu - Anti Cheat
[Success] Description GOLeague Anti-Cheat Detection Service
[Success] ServiceName GOAcService
Topshelf v4.2.0.194, .NET Framework v4.0.30319.42000
Topshelf.HostFactory Error: 0 : An exception occurred creating the host, System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Topshelf.HostConfigurators.HostConfiguratorImpl.CreateHost()
   bei Topshelf.HostFactory.New(Action`1 configureCallback)
Topshelf.HostFactory Error: 0 : The service terminated abnormally, System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Topshelf.HostConfigurators.HostConfiguratorImpl.CreateHost()
   bei Topshelf.HostFactory.New(Action`1 configureCallback)
   bei Topshelf.HostFactory.Run(Action`1 configureCallback)

Without Signing is working fine.

**Comment by xiangxingze** [comment]
> 当我签署我的应用程序的程序集时，我通过topshelf得到以下错误。
> NET Framework 4.6
> 
> 配置结果：
> [成功]名称GOAcService 
> [成功] DisplayName goleague.eu - 反作弊
> [成功]说明GOLeague反作弊检测服务
> [成功]服务名称GOAcService 
> Topshelf v4.2.0.194，.NET Framework v4.0.30319.42000 
> Topshelf。 HostFactory错误：0：创建主机时发生异常，System.NullReferenceException：Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt。
> bei Topshelf.HostConfigurators.HostConfiguratorImpl.CreateHost（）
> bei Topshelf.HostFactory.New（Action `1 configureCallback) Topshelf.HostFactory Error: 0 : The service terminated abnormally, System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt. bei Topshelf.HostConfigurators.HostConfiguratorImpl.CreateHost() bei Topshelf.HostFactory.New(Action`1 configureCallback）
> bei Topshelf.HostFactory.Run（Action`1 configureCallback）
> 
> 没有签名工作正常。

改成Topshelf.HostFactory.Run，并且Debug 模式编译在安装服务看下

**Comment by phatboyg** [comment]
Topshelf is signed, not sure why you're seeing this.

**Comment by phatboyg** [comment]
Closed due to inactivity.
