### ISSUE TITLE
how to run on ubuntu at dotnet core 2.0  platform

### ISSUE THREAD

**Issue by wuzhenda** [Topshelf/Topshelf#510]
should we still need topshelf.linux or topshelf.unix  package?

**Comment by phatboyg** [comment]
There are better options for creating services using .NET Core 2.2 with Linux.

**Comment by reinaldocoelho** [comment]
Any tips on what they are? :-D
I now that a console implementation can be a Linux Service.

**Comment by phatboyg** [comment]
https://github.com/MassTransit/Sample-ConsoleService

**Comment by reinaldocoelho** [comment]
Thanks!

**Comment by wuzhenda** [comment]
still hope topshelf can fix  this problem , one code two version would be perfectly

**Comment by wuzhenda** [comment]
waiting for next release [https://github.com/Topshelf/Topshelf/issues/533](url)
