### ISSUE TITLE
service start Exception is not logged properly for ServiceConfigurator<T>

### ISSUE THREAD

**Issue by oleksabor** [Topshelf/Topshelf#511]
Dears

I've just got issue when service start Exception is not logged properly in TopShelf 4.2.0. But it was in 4.0.4

I've used slightly modified  `Exception_callback.Should_be_called_when_exception_thrown_in_construct_using` method in the `Topshelf.Tests` source code.  It produces the same wired null reference error if no ExceptionCallback was set.
```
[Test]
public void Should_be_called_when_exception_thrown_in_construct_using()
{
    var sawException = false;

    var exitCode = HostFactory.Run(x =>
    {
        x.UseTestHost();

        x.Service<ExceptionThrowingService>(s =>
        {
            s.ConstructUsing(() => throw new Exception($"Unable to resolve {nameof(ExceptionThrowingService)} from DI container"));
            s.WhenStarted((es,hc) => true);
            s.WhenStopped((es, hc) => true);
        });

        //x.OnException(_ => sawException = true);
    });

    Assert.IsTrue(sawException);
    Assert.AreEqual(TopshelfExitCode.AbnormalExit, exitCode);
}
```
`Topshelf.HostFactory Error: 0 : An exception occurred creating the host, System.NullReferenceException: Object reference not set to an instance of an object.
   at Topshelf.HostConfigurators.HostConfiguratorImpl.CreateHost() in D:\projects\Topshelf\src\Topshelf\Configuration\HostConfigurators\HostConfiguratorImpl.cs:line 221`

I suppose it happens because of commit 4c37981e.  ExceptionCallback was added but no check for null was introduced in the catch statement

**Original code**:
```
catch (Exception ex)
{
    builder.Settings?.ExceptionCallback(ex);
    throw;
}
```
Does it mean that ExceptionCallback must be set during service configuration?
Is it possible to add check for null, like below
**Modification suggestion**
```
catch (Exception ex)
{
	if (builder.Settings?.ExceptionCallback != null)
		builder.Settings?.ExceptionCallback(ex);
    throw;
}
```

**Comment by DaniloGimenes** [comment]
I was having a problem starting my windows service because I didn't implement the onException method in version 4.2,0. After upgrade to 4.2.1 the problem was solved. Thank's.
