### ISSUE TITLE
After version 4.1.0.177-develop no more running on linux as console.

### ISSUE THREAD

**Issue by reinaldocoelho** [Topshelf/Topshelf#513]
When I update my example project (https://github.com/reinaldocoelho/dotnet-service-cross-platform) to versions after 4.1.0.177-develop any try to run on Linux result on:

```
Starting...
Configuration Result:
[Success] Name simple_service_counter
[Success] Description Serviço de apresentação TopShelf.
[Success] ServiceName simple_service_counter
Topshelf v4.2.0.194, .NET Framework v4.0.30319.42000
Topshelf.Runtime.Windows.WindowsHostEnvironment Error: 0 : Unable to get parent process (ignored), System.DllNotFoundException: Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32.dll: cannot open shared object file: No such file or directory
   at Topshelf.Runtime.Windows.Kernel32.CreateToolhelp32Snapshot(UInt32 dwFlags, UInt32 th32ProcessID)
   at Topshelf.Runtime.Windows.WindowsHostEnvironment.GetParent(Process child)
Topshelf.HostFactory Error: 0 : The service terminated abnormally, System.PlatformNotSupportedException: ServiceController enables manipulating and accessing Windows services and it is not applicable for other operating systems.
   at System.ServiceProcess.ServiceController.GetServices()
   at Topshelf.Runtime.Windows.WindowsHostEnvironment.IsServiceListed(String serviceName)
   at Topshelf.Hosts.ConsoleRunHost.Run()
   at Topshelf.HostFactory.Run(Action`1 configureCallback)

```

The build was generated with the command:
```
dotnet publish simple-service-counter.csproj -c Release -f netcoreapp2.1 -o dist\linux -r linux-x64 --self-contained
```

Why after that version the TopShelf include dependency to kernel32.dll ???

**Comment by phatboyg** [comment]
I'm assuming some pull request broke this, but I haven't taken a look to see which one yet.

**Comment by phatboyg** [comment]
I think the Topshelf.ServiceInstaller pull request broke linux, but I'm not sure yet.

**Comment by reinaldocoelho** [comment]
Thank you @phatboyg , if I find the root of problem I return here :-)

**Comment by krojew** [comment]
I've also encountered this error using 4.2. Any workaround?

**Comment by reinaldocoelho** [comment]
Hi @krojew , the linux only worked well on 4.1.0.177-develop on my tests.
Revert to this version was  the only workarround I found to work.

**Comment by krojew** [comment]
The only other version I see available is 4.1.0.172 and it has the same error.

**Comment by reinaldocoelho** [comment]
Try to check the "Include prerelease" to see DEV builds:
![image](https://user-images.githubusercontent.com/889634/53011312-dcd32880-341e-11e9-8ad8-058e0cdf4279.png)

**Comment by phatboyg** [comment]
With the ServiceInstaller on Topshelf, it is limited to Windows. That PR caused it.

In the meantime, however, I don't see much of a future for Topshelf on .NET Core/Linux given the features available right out of the box. For example: https://github.com/MassTransit/Sample-ConsoleService

**Comment by reinaldocoelho** [comment]
But @phatboyg , I need for example an solution with both, installing windows service or running as linux console giving to customer the option without changing my code.
With this aproach it insn´t possible, that´s right?

If TopShelf not follow this way, I really need to find other way without create two projects pointing to same sharing code.

You have some suggestion?

Thank you.

**Comment by krojew** [comment]
Unfortunately, 177 has a similar error:

System.DllNotFoundException: Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32.dll: cannot open shared object file: No such file or directory

**Comment by reinaldocoelho** [comment]
When this kernel32.dll error occours?
I do not receive this error when build.

**Comment by krojew** [comment]
When running the application I get:

> 2019-02-26 11:45:15,172 [1] INFO  HostConfiguratorImpl - Topshelf v4.1.0.177, .NET Framework v4.0.30319.42000
> 2019-02-26 11:45:15,184 [1] ERROR WindowsHostEnvironment - Unable to get parent process (ignored)
> System.DllNotFoundException: Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32.dll: cannot open shared object file: No such file or directory
>    at Topshelf.Runtime.Windows.Kernel32.CreateToolhelp32Snapshot(UInt32 dwFlags, UInt32 th32ProcessID)
>    at Topshelf.Runtime.Windows.WindowsHostEnvironment.GetParent(Process child)
> 2019-02-26 11:45:15,204 [1] DEBUG RunBuilder - Running as a console application, creating the console host.
> 2019-02-26 11:45:15,210 [1] ERROR HostFactory - The service terminated abnormally
> System.PlatformNotSupportedException: ServiceController enables manipulating and accessing Windows services and it is not applicable for other operating systems.
>    at System.ServiceProcess.ServiceController.GetServices()
>    at Topshelf.Runtime.Windows.WindowsHostEnvironment.IsServiceListed(String serviceName)
>    at Topshelf.Hosts.ConsoleRunHost.Run()
>    at Topshelf.HostFactory.Run(Action`1 configureCallback)
>

**Comment by reinaldocoelho** [comment]
You build it to dotnet core platform?
Try build it in this way to test:
```
dotnet publish your-project.csproj -c Release -f net461 -o dist\windows --self-contained
```

**Comment by krojew** [comment]
I'm targeting .net core, so I cannot use net461.

**Comment by reinaldocoelho** [comment]
This command may work then:

```
dotnet publish simple-service-counter.csproj -c Release -f netcoreapp2.1 -o dist\linux -r linux-x64 --self-contained
```

I realised that publish to windows not work with NetCore framework, but with focus on Linux environment it´s worked.

**Comment by krojew** [comment]
Unfortunately, the error persists:

> 2019-02-28 09:45:24,587 [1] INFO  HostConfiguratorImpl - Topshelf v4.1.0.177, .NET Framework v4.0.30319.42000
> 2019-02-28 09:45:24,599 [1] ERROR WindowsHostEnvironment - Unable to get parent process (ignored)
> System.DllNotFoundException: Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32.dll: cannot open shared object file: No such file or directory
>    at Topshelf.Runtime.Windows.Kernel32.CreateToolhelp32Snapshot(UInt32 dwFlags, UInt32 th32ProcessID)
>    at Topshelf.Runtime.Windows.WindowsHostEnvironment.GetParent(Process child)
> 2019-02-28 09:45:24,618 [1] DEBUG RunBuilder - Running as a console application, creating the console host.
> 2019-02-28 09:45:24,623 [1] ERROR HostFactory - The service terminated abnormally
> System.PlatformNotSupportedException: ServiceController enables manipulating and accessing Windows services and it is not applicable for other operating systems.
>    at System.ServiceProcess.ServiceController.GetServices()
>    at Topshelf.Runtime.Windows.WindowsHostEnvironment.IsServiceListed(String serviceName)
>    at Topshelf.Hosts.ConsoleRunHost.Run()
>    at Topshelf.HostFactory.Run(Action`1 configureCallback)
>

**Comment by phatboyg** [comment]
@krojew as you can see in the thread, the current Topshelf works for Windows .NET Core, but not Linux. 

I'd suggest using the .NET Core Host: https://github.com/MassTransit/Sample-ConsoleService

**Comment by krojew** [comment]
That's quite unfortunate, given Topshelf advertises itself as cross-platform. Any plans to make it work on something other than Windows?

**Comment by phatboyg** [comment]
Topshelf advertises itself as cross platform? As the owner, creator, and maintainer of the project, that's news to me. It flat out says on the repo it is for creating Windows services, what part of that isn't clear?

Yes, it works with .NET Core, but there is no need for a Windows service on Linux.

**Comment by reinaldocoelho** [comment]
Thank you for answer this thread @phatboyg :-)

**Comment by krojew** [comment]
It does say so on the front page, so it might need an update 😉

**Comment by slide** [comment]
FYI, I worked around this with the following:

```csharp
if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux)) {
    config.UseEnvironmentBuilder(new Topshelf.HostConfigurators.EnvironmentBuilderFactory(c => {
        return new DotNetCoreEnvironmentBuilder(c);
    }));
}
```

With this in my code, I am able to run under .NET Core on Linux.

**Comment by reinaldocoelho** [comment]
@slide on the last version (4.2.0.212-develop) it´s working too?
Thank you!

**Comment by slide** [comment]
I'm using 4.2.0 as the version in my csproj.

**Comment by reinaldocoelho** [comment]
Thank´s @slide, I´ll try too! :-)

**Comment by kilroyFR** [comment]
Thanks for the tip. 
Works great where running application on command line but how to set the Topshelf running as Daemon on Linux ?
