### ISSUE TITLE
Microsoft.Windows.Compatibility dependency

### ISSUE THREAD

**Issue by izzor** [Topshelf/Topshelf#515]
Hi,

Is it possible to replace the dependency on Microsoft.Windows.Compatibility with System.ServiceProcess.ServiceController and Microsoft.Win32.Registry in netstandard2?
For a small project Microsoft.Windows.Compatibility adds about 30 extra System dll's like SqlClient, Odbc and ServiceModel.
In some deployments it's a waste of disk space to have 6Mb of dll's installed that is not used.

**Comment by phatboyg** [comment]
Sure, if you'd like to submit a PR that would speed things along.
