### ISSUE TITLE
Code not being hit on windows server 2008

### ISSUE THREAD

**Issue by stuartbradley** [Topshelf/Topshelf#517]
I am trying to run the following code on windows server 2008, it does work on windows 10 no problem. 

The logs are being written and the timer event is hit because the log shows             twsLog.WriteEntry("Timer Hit");
but the log is not showing "DoEmailProcess started" which is the the next line of code.
Any ideas?

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Timers;
using TridentBusinessLogicLayer;
using TridentBusinessLogicLayer.ExternalAPICalls;
using TridentBusinessLogicLayer.ExternalAPICalls.ApiObjects.GraphObjects;

   namespace TridentWindowsService2._0
   {
    class TridentWindowsService2
    {
        private bool continueProcess;
         private MicrosoftGraphApiWrapper graphApiWrapper;
        private DbAction dbAction;
        private EventLog twsLog;
         private readonly Timer timer;

        public TridentWindowsService2()
        {
            startlog();
            timer = new Timer(60000) { AutoReset = true };
            twsLog.WriteEntry("Timer started");
            timer.Elapsed += TimerElapsed;
            dbAction = new DbAction()
        }
        private void TimerElapsed(object sender, ElapsedEventArgs e)
        {
            twsLog.WriteEntry("Timer Hit");
            DoEmailProcess();
        }

        public void startlog()
        {
            string eventSource = "TridentWindowsService2";
            string logName = "";
            twsLog = new EventLog();
            if (!EventLog.SourceExists(eventSource))
                EventLog.CreateEventSource(eventSource, logName);

            twsLog.Source = eventSource;
            twsLog.Log = logName;
            twsLog.WriteEntry("Initialised service.");
        }

        public void Start()

        {
            continueProcess = true;
            twsLog.WriteEntry("timer start in start Method");
            timer.Start();
        }
        private void DoEmailProcess()
        {
            twsLog.WriteEntry("DoEmailProcess started");
            graphApiWrapper = new MicrosoftGraphApiWrapper(twsLog);
            twsLog.WriteEntry("api created");

                List<int> pendingActionIds = new 
                DbAction().GetPendingActionIdsByActionTypeId((int)Enumerations.ActionType.Email);
                List<GraphEmail> emails = graphApiWrapper.GetInboundEmails();
                emails.AddRange(graphApiWrapper.GetSentEmails());
            foreach (GraphEmail email in emails)
            {
                foreach (int actionId in pendingActionIds)
                {
                    if (email.Subject.Contains(actionId.ToString()))
                    {
                        email.SaveEmailToServer();
                    }
                }
            }
        }
        public void Stop()
        {
            continueProcess = false;
            timer.Stop();
        }
    }
}

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Topshelf;
namespace TridentWindowsService2._0
{
    class Program
    {
        static void Main(string[] args)
        {
            var exitCode = HostFactory.Run(x =>
            {
                x.Service<TridentWindowsService2>(s =>
                {
                    s.ConstructUsing(h => new TridentWindowsService2());
                    s.WhenStarted(h => h.Start());
                    s.WhenStopped(h => h.Stop());
                });
                x.RunAs(@"xxx\xxx.xxxx", "xxxxx");
                x.SetServiceName("xxxxx");
                x.SetDisplayName("xxxxx");
                x.SetDescription("xxxx");
            });
            Environment.ExitCode = (int)Convert.ChangeType(exitCode, exitCode.GetTypeCode());
        }

    }

}

**Comment by phatboyg** [comment]
Closed due to inactivity.
