### ISSUE TITLE
Command Line Documentation Missing Options

### ISSUE THREAD

**Issue by mason-mcglothlin** [Topshelf/Topshelf#518]
[The documentation for the command line](http://docs.topshelf-project.com/en/latest/overview/commandline.html) is a little misleading. Certain options, such as `servicename` apply to the `uninstall` verb, but the documentation doesn't reflect this. The documentation makes it appear that `servicename` only applies to the `install` verb. I could fix that in the documentation myself, but I'm not sure what other options might apply to the different verbs.

**Comment by phatboyg** [comment]
You're welcome to submit a PR, closing.
