### ISSUE TITLE
Also add Session Events for .NET Core Console Host

### ISSUE THREAD

**Issue by darinkes** [Topshelf/Topshelf#519]
It works with the Microsoft.Win32.SystemEvents Nuget on .NET Core: 
https://github.com/Topshelf/Topshelf/blob/develop/src/Topshelf/Hosts/ConsoleRunHost.cs#L52

https://www.nuget.org/packages/Microsoft.Win32.SystemEvents/

**Comment by phatboyg** [comment]
Will you
