### ISSUE TITLE
Request to add a link to a TopShelf Azure DevOps Release Task 

### ISSUE THREAD

**Issue by Dejulia489** [Topshelf/Topshelf#521]
I recently added TopShelf support to [Windows Service Manager](https://marketplace.visualstudio.com/items?itemName=MDSolutions.WindowsServiceManagerWindowsServiceManager), an Azure DevOps build\release task for deploying windows services. 

[Github Project](https://github.com/Dejulia489/WindowsServiceManager)

Please feel free to add a link to the extension into your README.md.

Thank you kindly, 
Michael

**Comment by phatboyg** [comment]
You could submit a PR with a link, probably the only way it will happen :)

**Comment by Dejulia489** [comment]
Added pull request #522. 

Thank you
