### ISSUE TITLE
CoreRT Support (Native compile)

### ISSUE THREAD

**Issue by jonmcox** [Topshelf/Topshelf#526]
When compiling a service project using CoreRT (native compiler) it won't correct install the Windows service.  CoreRT unfortunately returns an empty string in reference to the  assembly location value.

(public sealed override string Location => string.Empty)
https://github.com/dotnet/corert/issues/5017

This is a related blog indicating why CoreRT returns string.Empty.
https://github.com/dotnet/corert/blob/2a81711d3c71e5dc3dc7a56d33f81e33f5c3f65d/src/System.Private.Reflection.Core/src/System/Reflection/Runtime/General/ThunkedApis.cs#L61

Pertaining to TopShelf when creating the 'CreateTransactedInstaller' it attempts to obtain the service exe path using the assembly.Location.
HostServiceInstaller.cs
static TransactedInstaller CreateTransactedInstaller(Installer installer,string serviceName)

suggestion: We need to determine the service path to the exe/dll however I'm not sure what the best approach would be once it has been compiled using CoreRT.  You might decide a better way to determine the executing assembly location (exe/dll).

 if (string.IsNullOrEmpty(assembly.Location))
 path = $"/assemblypath={System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, string.Format("{0}.exe" , serviceName))}";

Environment Setup:
nuget.config (custom nuget feed)
  <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />

Add Nuget Package reference
<PackageReference Include="Microsoft.DotNet.ILCompiler" Version="1.0.0-alpha-27527-01" />

Run a native compile using a command prompt.
dotnet publish -r win-x64 -c release

It should produce a native exe in the following directory.
~\bin\Release\netcoreapp2.2\win-x64\native

**Comment by phatboyg** [comment]
I'd recommend using the .NET Core Generic Host in this situation, honestly.

Similar to what was done in this sample: https://github.com/MassTransit/Sample-ConsoleService

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
