### ISSUE TITLE
gMSA command line parsing error

### ISSUE THREAD

**Issue by donig** [Topshelf/Topshelf#528]
There is a problem with command line parsing if using a group managed service account, which requires no password. If I install without any additional paramenters, as in:

MyService.exe install  -username "DOMAIN\msaAccount$" -password

the installation works fine. However, if I add other parameters, an exception is thrown:

MyService.exe install  -username "DOMAIN\msaAccount$" -password -servicename "MyService" -displayname "MyService" -description "My amazing service."

Topshelf.HostFactory Error: 0 : An exception occurred creating the host, Topshelf.HostConfigurationException: The service was not properly configured:
[Failure] Command Line An unknown command-line option was found: ARGUMENT: "MyService"
[Success] Name MyService
[Success] Description My amazing service.
[Success] ServiceName MyService
   at Topshelf.Configurators.ValidateConfigurationResult.CompileResults(IEnumerable`1 results)
   at Topshelf.HostFactory.New(Action`1 configureCallback)
Topshelf.HostFactory Error: 0 : The service terminated abnormally, Topshelf.HostConfigurationException: The service was not properly configured:
[Failure] Command Line An unknown command-line option was found: ARGUMENT: "MyService"
[Success] Name MyService
[Success] Description My amazing service.
[Success] ServiceName MyService
   at Topshelf.Configurators.ValidateConfigurationResult.CompileResults(IEnumerable`1 results)
   at Topshelf.HostFactory.New(Action`1 configureCallback)
   at Topshelf.HostFactory.Run(Action`1 configureCallback)

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
