### ISSUE TITLE
next release?

### ISSUE THREAD

**Issue by seertenedos** [Topshelf/Topshelf#533]
We are currently using 4.2.0.212-develop to get the windows support and Linux docker support in the TopShelf but we also get a lot of warnings about about using a beta version in stable builds. I was just wondering if their will likely be a new release build soon since the last one was 5 months ago.

**Comment by phatboyg** [comment]
Sure, I can kick one out with what's in develop.

**Comment by wuzhenda** [comment]
@seertenedos  what do you mean 'linux docker support',  run under linux?

**Comment by seertenedos** [comment]
https://github.com/Topshelf/Topshelf/pull/531

basically there were checks in the code that can only run on windows and if you try to do it on linux it would error. I submitted a fix so it will be able to run as a console app on linux. We mostly use this to run dotnet core as windows services on windows or as a console app in a linux docker container. This lets us get the best of both worlds and do a slow migration

**Comment by wuzhenda** [comment]
that's just what I needed. thanks.

**Comment by edwardridge** [comment]
Hi, any update on a new release? We'd love to run a stable version with #529 in it

**Comment by seertenedos** [comment]
can this please happen soon? Still waiting on #531 to ideally be in a release to meet internal requirements for production release of our apps as they are only meant to reference non pre-release nugets.

**Comment by phatboyg** [comment]
Done.
