### ISSUE TITLE
Command Line An unknown command-line option was found: SWITCH: i (True) / (DEFINE: i =)

### ISSUE THREAD

**Issue by jcprata** [Topshelf/Topshelf#536]
Hi,

I am getting this title error and don't know why.

If i use Topshelf v3.1.4.357038 i get:

> Command Line An unknown command-line option was found: SWITCH: i (True)

I i use Topshelf v4.1.0.172 i get:

> Command Line An unknown command-line option was found: DEFINE: i =

On Windows 7 or Windows 2012 Server i don't get this error.
I am running this on Windows 10.

When i install my app as a windows service, start and stop button are always disabled whatever the version of the topshelf.

Any recommendation to what i should try to do?

Thanks.

### **EDIT**

I have been confirmed that this error is also being fired in Windows Server 2012 R2 Standard production server. The difference is that in production environment we have start/stop buttons enabled, but in windows 10 machine i don't have start/stop buttons enabled.

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
