### ISSUE TITLE
Unable to print help without constucting HostFactory or when unrecognized argument are supplied

### ISSUE THREAD

**Issue by xanth** [Topshelf/Topshelf#538]
I'd like to print the help text when an unrecognized argument is supplied, rather than or in addition to the `Command Line An unknown command-line option was found: ARGUMENT: x` message. 

Without making any code changes to Topshelf I cant find a way to catch the `HostConfigurationException` and print help. This seems to me to be a missing feature as most cli applications print help when they receive unexpected or malformed arguments.

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
