### ISSUE TITLE
Question: AspNetCore run as TopShelf Windows Service

### ISSUE THREAD

**Issue by generik0** [Topshelf/Topshelf#539]
We have a long time used Topshelf (together with e.g. Nancy) to make self hosted windows services that are rest enabled.
This has worked great for many years. Thank you!..

Now dotnetcore came along, and aspnetcore rest controller actually seems to be better than nancy.
So we have started to make our services and mircoservices as aspnetcore applications...

But there still good advantages with TopShelf over the apsnetcore service...

Question:

Does anybody know how we can load a netcoreapp2.x with all the aspnetcore niceties?

Should we e.g. just start teh service (though host factory) creating the ConfigurationBuilder and WebHost? Would this be best practice?

Or are we just overcomplicating stuff, and going down the wrong track? Any thoughts?

**Comment by phatboyg** [comment]
If you're using ASP.NET Core, might as well take advantage of everything they offer. With 3.x, you also get service hosting (by way of `UseServiceBaseLifetime()`). Consider using the DI extensions to configure the bus, clients, consumers, etc.

**Comment by generik0** [comment]
@phatboyg As i see it, the biggest advantage with TopShelf (aka selling point) is you can:

- Run the same executable as a console and service. And,
- Install command line

But this is possible with Aspnetcore and Generic host also now in netcoreapp.

Does that mean that net core is a TopShelf killer? I mean, it isn't as smooth as TopShelf, But we can install as service and run as console

![image](https://user-images.githubusercontent.com/2411563/62701460-a006e800-b9e4-11e9-8ef2-2a57cb695888.png)


I also got aspnetcore into topshelf wrapping the WebHost and Configuration builder in the HostFactory:

![image](https://user-images.githubusercontent.com/2411563/62701551-e0fefc80-b9e4-11e9-8b28-6033367ad4f7.png)


So both work. 
The big question, does the TopShelf "wrapper" have value... I personally feel it does...
but @phatboyg it seams you do not feel the same from your comment above?

**Comment by phatboyg** [comment]
I don't plan to build out Topshelf for .NET core beyond what's there today. It's easy enough to do with the coming features of NetCoreApp 3.0

**Comment by generik0** [comment]
@phatboyg Your Topshelf Rocks btw.
The AspNetCore and generic host. in 3.0 are you sure it has all the functionality of the topshelf host? like installing with dealy start, and recovery interaction?

**Comment by phatboyg** [comment]
That only works on Windows, though. On Linux and Mac, none of that is available.

**Comment by generik0** [comment]
Yes and not in eg Azure either
