### ISSUE TITLE
How can a console app play well with ServiceController APIs?

### ISSUE THREAD

**Issue by nawfalhasan** [Topshelf/Topshelf#540]
So I have this console app which will be registered as a Windows Service for the client. Topshelf makes it easy to run it as a console app during debug.

But we have a lot of calls for the ServiceController class, like ServiceController.GetServices() which will fail if we are running as a console app. Is there any setting/switch within Topshelf which will mimic the console app as service, so that ServiceController.GetServices() will return our console app as well?

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
