### ISSUE TITLE
startwith/startautomatically error squelched

### ISSUE THREAD

**Issue by dylanthelion** [Topshelf/Topshelf#543]
When starting (this happens during StartWith and StartAutomatically) as a console app and encountering a file access error (which happens every time the app is running as a Service), the error is squelched.

I wouldn't consider this a crucial error, and after 2+ years of using this package, I'm down to about 10 minutes before I figure out what went wrong. But it would have saved me some severe headaches in  the past, so: can it be fixed?

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
