### ISSUE TITLE
Topshelf says it's running .NET Framework v3.0.0

### ISSUE THREAD

**Issue by Jogge** [Topshelf/Topshelf#544]
`Topshelf v4.2.1.215, .NET Framework v3.0.0` is written in the console when using Topshelf in a .NET Core 3.0 project.

https://github.com/Topshelf/Topshelf/blob/1af220dddb6530da57f56ec202c249668afc05ef/src/Topshelf/Configuration/HostConfigurators/HostConfiguratorImpl.cs#L205

**Comment by phatboyg** [comment]
Yeah, it displays the framework version. So what?

**Comment by Jogge** [comment]
@phatboyg Shouldn't it say `.NET Core v3.0.0` instead?
