### ISSUE TITLE
Can not uninstall service using -instance

### ISSUE THREAD

**Issue by cakriwut** [Topshelf/Topshelf#547]
## Steps to reproduce

1. Install using -instance and -servicename  
    [servicename.exe] install -instance:MySvc -servicename:MyService -displayname:Displayname

2. Uninstall using  
   [servicename.exe] uninstall -instance:MySvc

## Issue

1. Service still registered in Windows Service a.k.a can not remove

## Temporary solution
1.   Manual delete  
      sc delete  MyService$MySvc

## Observation
1.  Apparently the instance name will become MyService$MySvc if both -instance and -servicename are specified during the install.
2.  The framework can not uninstall even if we try to use  
     [service.exe] uninstall -instance:MyService$MySvc

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
