### ISSUE TITLE
Is this still actual with .NET Core 3.0 release?

### ISSUE THREAD

**Issue by Svetomechc** [Topshelf/Topshelf#549]
As they have [Microsoft.Extensions.Hosting.WindowsServices](https://www.nuget.org/packages/Microsoft.Extensions.Hosting.WindowsServices) now.

**Comment by phatboyg** [comment]
If you're using .NET Core 3.0, there is no reason to use Topshelf.

**Comment by Svetomechc** [comment]
@phatboyg thanks for your reply, just wanted to clarify that this project is for .NET Framework only.

**Comment by phatboyg** [comment]
Topshelf works with .NET Core, but seriously, the stuff in .NET Core 3 is just so much cleaner.
