### ISSUE TITLE
Trouble installing TopShelf

### ISSUE THREAD

**Issue by rmount** [Topshelf/Topshelf#550]
Attempting to install via PM

Install-Package : Could not install package 'Topshelf 4.0.4'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content 
files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package Topshelf -Version 4.0.4
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by phatboyg** [comment]
Minimum version is 4.5.2, so you'll need to upgrade your projects target framework.
