### ISSUE TITLE
How to install with Network Service as Log on user

### ISSUE THREAD

**Issue by awerber** [Topshelf/Topshelf#551]
I'm interested in installing a service created with Topshelf using a batch file or Powershell script. I want to use Network Service as the user. Network Service does not have a password. I've tried installing with no password parameter, leaving the parameter blank and using two double quotes (i.e. empty string). The service does not get installed. Is there a way to do this with the install option, or do I have to install the service first and change the user after that? If the latter is true, how is that done? I've looked around for a way to do that (change log on user for a service), and have not found clear guidance on this matter.

Thanks for any help.

**Comment by phatboyg** [comment]
Closed due to inactivity.
