### ISSUE TITLE
facing services initialized issue in windows services

### ISSUE THREAD

**Issue by bilalmalik777** [Topshelf/Topshelf#554]
I am using dot net core 2.2. The code is working perfectly in debug mode. but when i deploy it as window service, code and error is given below respectively
###Code###
>  HostFactory.Run(config =>
                {
                    config.SetServiceName("Downtime Service");
                    config.SetDisplayName("Downtime Service");
                    config.SetDescription("Perform different operation to calculate different values");
                    config.RunAsLocalSystem();
                    config.StartAutomatically();
                    config.RunAsLocalSystem();
                    config.Service<DownTimeWinSevice>(serviceConfigurator =>
                    {
                        serviceConfigurator.ConstructUsing(() => new DownTimeWinSevice());
                        serviceConfigurator.WhenStarted((service, hostControl) =>
                        {
                            service.Start(hostControl);
                            return true;
                        });
                        serviceConfigurator.WhenStopped((service, hostControl) =>
                        {
                            service.Stop(hostControl);
                            return true;
                        });
                    });
                });

###Error###
> Application: TT.Core.Downtime.Webjob.exe CoreCLR Version: 4.6.27110.4 Description: The process was terminated due to an unhandled exception. Exception Info: System.AggregateException: One or more errors occurred. (The string argument 'connectionString' cannot be empty.) (Value cannot be null. Parameter name: s) (Value cannot be null. Parameter name: s) (Value cannot be null. Parameter name: s) ---> System.ArgumentException: The string argument 'connectionString' cannot be empty. at Microsoft.EntityFrameworkCore.Utilities.Check.NotEmpty(String value, String parameterName) at Microsoft.EntityFrameworkCore.SqlServerDbContextOptionsExtensions.UseSqlServer(DbContextOptionsBuilder optionsBuilder, String connectionString, Action`1 sqlServerOptionsAction) at TT.Core.Downtime.Webjob.Program.<>c.<BuildServiceProvider>b__21_2(DbContextOptionsBuilder opt) in C:\Users\Bilal\source\repos\MonitoringPlatform\Source\Core\TT.Core.Downtime.Webjob\Program.cs:line 227 at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.DbContextOptionsFactory[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope) at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider) at TT.Core.Downtime.Webjob.Functions.CalculateMasterEntity() in C:\Users\Bilal\source\repos\MonitoringPlatform\Source\Core\TT.Core.Downtime.Webjob\Functions.cs:line 206 at TT.Core.Downtime.Webjob.Functions.ProcessMethod(CancellationToken token) in C:\Users\Bilal\source\repos\MonitoringPlatform\Source\Core\TT.Core.Downtime.Webjob\Functions.cs:line 56 at TT.Core.Downtime.Webjob.DownTimeWinSevice.<>c__DisplayClass3_0.<CallAllTheMethod>b__0() in C:\Users\Bilal\source\repos\MonitoringPlatform\Source\Core\TT.Core.Downtime.Webjob\DownTimeWinSevice.cs:line 63 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location where exception was thrown --- at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot) --- End of inner exception stack trace --- at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken) at System.Threading.Tasks.Task.WaitAll(Task[] tasks) at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions) --- End of stack trace from previous location where exception was thrown --- at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException) at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions) at System.Threading.Thread.ThreadMain_ThreadStart() at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by phatboyg** [comment]
Closed due to inactivity.
