### ISSUE TITLE
Installing TopShelf service with InstallUtil (or any non-topshelf deployment)

### ISSUE THREAD

**Issue by aleksey-sh** [Topshelf/Topshelf#556]
I am having a problem deploying the service. I am aware that the deployment of the topshelf-based service really should be done by passing _install_ argument to executable. I am also aware that it does not appear (or even is not expected) to be working with installutil. 

Unfortunately, in our company all our non-dev environments use company-wide standard deployment infrastructure that is using combination of installutil and probably some built-in windows/powershell commands to deploy our services. This means I am not going to be able to simply run executable. This is done due to security concerns. The deployment script sets the running user to a specific user for each environment and password is kept confidential. 

So, my question is... Is there any way the service can be deployed using standard Windows commands and/or features and not using _service.exe install_?

Thanks! Any help would be greatly appreciated!

**Comment by netactivenl** [comment]
Yes, we do this as well. You have to make sure through, that the Service name and description used to register the service do match the name and description configured for TopShelf.

**Comment by phatboyg** [comment]
Closed due to inactivity.
