### ISSUE TITLE
Unable to uninstall service

### ISSUE THREAD

**Issue by Janus88** [Topshelf/Topshelf#558]
Hi,

I have a little problem. In HostFactory occurs an exception. This leads to the problem, that I can't start the service as well as not uninstall it anymore. See the both screenshots. Does anybody have an idea what to do?

Thank you!

![image](https://user-images.githubusercontent.com/8038120/74412823-8ab0c180-4e3e-11ea-8d9d-eb7da4ca8af8.png)

![image](https://user-images.githubusercontent.com/8038120/74412893-aa47ea00-4e3e-11ea-931f-aee778d95812.png)

**Comment by Prodigio** [comment]
You should provide the exception message.
