### ISSUE TITLE
PlatformNotSupportedException is swallowed having NLog without LogFactory

### ISSUE THREAD

**Issue by HeikoStudt** [Topshelf/Topshelf#559]
If you are running a dotnet core topshelf application in windows from the publish folder with "dotnet.exe xyz.dll", it might fail with a PlatformNotSupportedException in GetServices().
(The WHY is not part of the issue here, probably there were missing runtime DLLs in the publish folder)
The problem is that Topshelf is swallowing that exception (no call to the OnException callback etc) and it is even not logged anywhere, if you are using the parameterless UseNLog() method. The service is simply not starting up, while it works all right in Visual Studio and the reason was clearly to search inside the Topshelf code.

There are two issues for Topshelf to fix:
a) UseNLog() should forward all(?) TopShelf logs into NLog instead of swallowing.
b) The exception needs to callback into OnException and/or result in a command line hosting.

The following is the log with UseNLog(logFactory) having a stacktrace of the exception:

Topshelf.HostFactory | Error | The service terminated abnormally | System.PlatformNotSupportedException: ServiceController enables manipulating and accessing Windows services and it is not applicable for other operating systems.
   at System.ServiceProcess.ServiceController.GetServices()
   at Topshelf.Runtime.Windows.WindowsHostEnvironment.IsServiceListed(String serviceName)
   at Topshelf.Runtime.Windows.WindowsHostEnvironment.IsServiceInstalled(String serviceName)
   at Topshelf.Hosts.ConsoleRunHost.Run()
   at Topshelf.HostFactory.Run(Action`1 configureCallback)

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
