### ISSUE TITLE
can't start as windows service

### ISSUE THREAD

**Issue by mfjiang** [Topshelf/Topshelf#560]
Configuration Result:
[Success] Name KafkaConsumer
[Success] DisplayName KafkaConsumer -- Transaction Compensation Service Beta Ver.1.0.1.100 (Instance: KafkaConsumer)
[Success] Description KafkaConsumer -- Kafka based event bus.
[Success] InstanceName KafkaConsumer
[Success] ServiceName KafkaConsumer$KafkaConsumer
Topshelf v4.2.1.215, .NET Framework v4.0.30319.42000
Topshelf.Hosts.StartHost Error: 0 : The service failed to start., System.InvalidOperationException: can't satart service on “.” KafkaConsumer$KafkaConsumer。 ---> System.ComponentModel.Win32Exception: The service did not respond to the start or control request in a timely manner。
   --- internal exception stack trace ---
   at System.ServiceProcess.ServiceController.Start(String[] args)
   at System.ServiceProcess.ServiceController.Start()
   at Topshelf.Runtime.Windows.WindowsHostEnvironment.StartService(String serviceName, TimeSpan startTimeOut)
   at Topshelf.Hosts.StartHost.Run()

**Comment by mfjiang** [comment]
my start codes:
static void Main(string[] args)
{

   var rc = HostFactory.Run(x =>
                {
                    x.Service<KafkaMQConsumerWinService>(s =>
                    {
                        s.ConstructUsing(() => new KafkaMQConsumerWinService());
                        s.WhenStarted(instance => instance.Start());
                        s.WhenStopped(instance => instance.Stop());
                    });
                    x.RunAsLocalSystem();

                    x.SetDescription("KafkaConsumer -- Kafka Consumer Service");
                    x.SetDisplayName("KafkaConsumer -- Transaction Compensation Service Beta Ver." + version);
                    x.SetServiceName("KafkaConsumer");
                    x.SetInstanceName("KafkaConsumer");
                });

                var exitCode = (int)Convert.ChangeType(rc, rc.GetTypeCode());
                Environment.ExitCode = exitCode;

}

**Comment by phatboyg** [comment]
Likely permissions, or config, or something. It usually is.
