### ISSUE TITLE
The suffix `(Instance: MyInstance)` should not be added when explicitly providing a display name

### ISSUE THREAD

**Issue by lauxjpn** [Topshelf/Topshelf#562]
We run the following command:

`myservice.exe install -servicename "MySvc" -instance "MyInstance" --localsystem`

It creates a service with a generated display name of `MySvc (Instance: MyInstane)`, which is absolutely fine.

However, consider us running the following command:

`myservice.exe install -servicename "MySvc" -instance "MyInstance" -displayname "My very special service" --localsystem`

It creates a service with a display name of `My very special service (Instance: MyInstane)`, which should be considered unexpected.

When explicitly specifying a display name, we naturally expect the display name to be what was specified and not something modified.
If someone wants to add a readable version of his instance name to the display name, he can do so as part of the `-displayname` value.

---
Topshelf 4.2.1.215
.NET Core 3.1.3

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
