### ISSUE TITLE
"Allow service to interact with desktop" install option is missing

### ISSUE THREAD

**Issue by lauxjpn** [Topshelf/Topshelf#564]
Services run as `LocalSystem` can optionally interact with the desktop (see [Interactive Services](https://docs.microsoft.com/en-us/windows/win32/services/interactive-services)).

This is currently not supported by Topshelf.

Because the command line option `--interactive` is already used to prompt the user for credentials, I propose that we add an additional switch like `--localsysteminteract` or `--localsystemdesktop` that can be used *instead of* `--localsystem`, if desktop interaction is necessary.

**Comment by vesuvian** [comment]
If possible, I would also like to see this configured via the HostFactory. It would make sense to add a parameter `bool localSystemInteract = false` to the `HostConfigurator.RunAsLocalSystem` method.

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
