### ISSUE TITLE
Handling Windows PreShutdown events

### ISSUE THREAD

**Issue by jackmang** [Topshelf/Topshelf#571]
I have need to respond to PreShutdown events.  These are events that were added to Windows services starting with Vista.  
https://docs.microsoft.com/en-us/windows/win32/services/service-changes-for-windows-vista
https://scottdorman.blog/2006/06/18/windows-vista-kernel-changes-can-i-get-some-service/
https://www.atomia.com/2011/11/16/how-to-process-the-preshutdown-event-in-a-managed-windows-service/ 
https://www.sivachandran.in/2012/03/handling-pre-shutdown-notification-in-c.html

See also TopShelf Issue:  Support SERVICE_CONTROL_PRESHUTDOWN #371

I've been using this functionality for 8+ years in my own library ServiceBaseEx that I built based on a decompile of ServiceBase, but TopShelf makes so many things easier I'd prefer to use it.  Alas, not supported here yet.  I'm at a loss as to why Microsoft hasn't added support to ServiceBase, but clearly they have no intention.

This week, being on furlough for Covid, I spent some time seeing what it would take.  It turns out to not be too bad to hack in, and I have done it, but I'm not sure you guys would accept it.  The solution I came up with was to modify WindowsServiceHost to add a CanPreShutdown property.  If set, the constructor calls a function that sets the properties and callbacks required.  This uses reflection against ServiceBase and is therefore somewhat dependent on the MS ServiceBase implementation details.  Maybe a bit brittle.

Alternatively, could we consider using and modifying the ServiceBase from MS on GitHub which is apparently MIT licensed.  The changes are very minor and would leave TopShelf fully in control of the implementation. 
https://github.com/microsoft/referencesource/blob/master/System.ServiceProcess/ServiceBase.cs
> The files in this repository are licensed under the MIT license unless otherwise specified in the file header. If the file header only contains a copyright header (e.g., "Copyright (c) Microsoft Corporation. All rights reserved.", you can assume the associated file to be MIT-licensed.

I'm happy to help implement this and share the code if the owners here are interested.

**Comment by jackmang** [comment]
I was hoping there might be some interest, or at least feedback.  The preshutdown events are part of the standard Windows Service API, so I'm not proposing anything that doesn't further coverage of core Windows service capabilities.  I guess the oddity here is that the .Net API doesn't cover this functionality.

I've already built a version of TopShelf for my own use that implements this support, I was thinking that contributing it back would be good manners.  I only thought I'd take feedback on how the maintainers might prefer it be implemented before creating a PR.

Regardless, I want to say that this is a great tool and I appreciate your sharing it with the community.

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
