### ISSUE TITLE
Configurable Service Shutdown Signal (for console app)

### ISSUE THREAD

**Issue by atomovski** [Topshelf/Topshelf#572]
Hi There,

I'll start off with a bit of context around the issue that I'm facing. We're using Topshelf internally to wrap our applications and provide us a service interface, these applications have two deployment models 1) via an installer that will setup a Windows service, 2) as console applications. Now traditionally the console apps have been used only for development purposes but at the moment we're planning the rollout of [Nomad](https://www.nomadproject.io/) as our workload orchestrator. 

All of that said we've run into an issue where Nomad is only capable of sending a CTRL+Break signal to the console app which Topshelf considers as a forced shutdown (or not a clean one as per [this if statement and associated log](https://github.com/Topshelf/Topshelf/blob/develop/src/Topshelf/Hosts/ConsoleRunHost.cs#L233)). The reasons why Nomad sends the CTRL+Break instead of CTRL+C are explained [here](https://github.com/hashicorp/nomad/issues/7747) but TL;DR; they use process groups when starting the app and in order to prevent process leaks CTRL+Break is required. 

To wrap it all up, I suppose the two questions I have are:
1. Was there a particular reason that CTRL+Break is considered as not a clean exit? 
2. Would a PR to either treat both signals as shutdown commands or make it configurable something that you'd accept? 

Thanks!

**Comment by phatboyg** [comment]
They behave differently for a reason, Control+C is clean exit, Control+Break forces it to shut down.

**Comment by atomovski** [comment]
@phatboyg thanks for the quick reply, I understand this is a non-issue in your opinion, just one last question: is there anything inherently wrong with making the clean and forced shutdown signals/key combinations configurable?

**Comment by phatboyg** [comment]
I don’t see what it would hurt, I just question the value in general for most.

**Comment by atomovski** [comment]
@phatboyg I suppose the only real value IMHO is the flexibility it gives to external operators (like the use case with Nomad) or when the app is running as part of a process group where you can't really trigger a clean exit (Control+C is not propagated for process groups). 

If you don't mind I'll try and create a PR for it and if it's not an intrusive/risky change I suppose you can consider merging it.

**Comment by phatboyg** [comment]
Great, once it’s ready I’ll merge it.
