### ISSUE TITLE
Session changed event logging

### ISSUE THREAD

**Issue by AlexandruIstrate** [Topshelf/Topshelf#580]
## Problem ##
I have a Windows service that uses the ```WhenSessionChanged``` method for listening to session change events. This works fine, however if I use a logging provider such as Serilog, I get a lot of log messages like this:

```
[Topshelf] Service session changed
[Topshelf] Service session changed handled
```

My service uses some custom logic to do things when a user logs on or off and as such I am bound to get a lot of messages like the ones above. My problem is that the messages fill up the logs and make it really hard to see other, more important, logs such as application specific ones. I have looked through your source code and noticed that the messages above are [logged using the Info level](https://github.com/Topshelf/Topshelf/blob/49c1c8b31b2413cc870a2dfd25041cab62bfb2d5/src/Topshelf/Runtime/Windows/WindowsServiceHost.cs#L246).

## My Fix ##
I fixed this in a hacky way, essentially by telling Serilog to filter out events starting with ```[Topshelf] Service session changed```.

```csharp
new LoggerConfiguration()
    .Filter.ByExcluding(e => e.MessageTemplate.Text.StartsWith("[Topshelf] Service session changed"))
```

## Proposed Solution ##
I would suggest sending these logs to the Debug level instead or providing some more granular control over how these events are logged. I really don't believe that this information is useful outside of a debugging context.

## Environment ##

- .NET Framework 4.8
- Windows Server 2016

**Comment by phatboyg** [comment]
You're welcome to submit a PR to change the log level.

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
