### ISSUE TITLE
Run topshelf app as console app without console window.

### ISSUE THREAD

**Issue by mrt181** [Topshelf/Topshelf#581]
Is it possible to suppress the console window when running a topshelf app as a console app.

I started building my app as a service but this does not work because it is supposed to start and automate another GUI app - that does not work when runnin as a service.

In console mode this works but I would like to get rid of the console window.

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
