### ISSUE TITLE
Password in plaintext

### ISSUE THREAD

**Issue by BigHoss** [Topshelf/Topshelf#582]
Is it possible to install a service with a useraccount without having to have the password in the code or the parameter in plaintext?

My constellation:
I build the service in azure and deploy it to a server and install it via an included powershell script.
So the pw stays either in the code or in the powershell which are both not acceptable.

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.

And I don't know of another way, sorry.
