### ISSUE TITLE
[Question] 4.2.2 - Estimated Release Date

### ISSUE THREAD

**Issue by atomovski** [Topshelf/Topshelf#584]
Hi There, 

We're eager to get our hands on the next release of TopShelf especially given the development branch contains one PR #578 related to #572 that is on the critical path for some of our initiatives for early next year. That said I was wondering if there is any plan to release 4.2.2 any time soon? 

Thanks!

**Comment by phatboyg** [comment]
Are there other PR's that should be included before getting the release out?

**Comment by atomovski** [comment]
@phatboyg for what we need from this version not really.

**Comment by phatboyg** [comment]
So it's all merged in, I can release 4.3.0 anytime. I pulled in all open PR's, updated packages, and even merged the CAKE build migration so that it actually builds and updates NuGet.
