### ISSUE TITLE
Command Line Unknown Argument

### ISSUE THREAD

**Issue by yonkavalow** [Topshelf/Topshelf#585]
I am using Top Shelf version 3.3.1 because my project currently need to target .NET 3.5 and I need to be able to handle the following command line arguments "-listen tcp:7500 -no-permanent" I've used AddCommandLineDefinition to support most of that but still choking on "tcp:7500" part. Getting this error: [Failure] Command Line An unknown command-line option was found: ARGUMENT: tcp:7500.

I dont need to use the argument, basically just need to ignore it. Is there any way to workaround this issue?

**Comment by phatboyg** [comment]
Dunno, probably something throwing off the command-line parser.
