### ISSUE TITLE
Current ConsoleRunHost.CatchUnhandledException code is likely to fail when thread already has a name

### ISSUE THREAD

**Issue by pruiz** [Topshelf/Topshelf#586]
A Thread's name can only be set once, but at https://github.com/Topshelf/Topshelf/blob/f28b7fc5bc290ce3596a062fb9b4c17adcf0b69c/src/Topshelf/Hosts/ConsoleRunHost.cs#L173

The name is set unconditionally, so if the unhandled exception comes from a named thread, this code will fail and no wait will be done to let the service finish gracefully.

**Comment by phatboyg** [comment]
Glad to accept a PR on this one.
