### ISSUE TITLE
Topshelf with Serilog and MassTransit not logging MT logs while running as service

### ISSUE THREAD

**Issue by CesarD** [Topshelf/Topshelf#588]
Hello. I have an app with Topshelf that runs a few MassTransit consumers and uses Serilog to log everything in 2 sinks: console and rolling file. The app is a .NET Framework 4.8 one.

So far, while running the app as a console, everything works perfectly. The problem comes when I intend to install the app as a service on Windows, and that's when the weird stuff begins: The Topshelf bootstrapping messages they all get logged, but none from the MassTransit bus. If I stop the service and execute it directly from the command line, all logs are reflected in both the console and the rolling file.

I don't understand what is the difference and if I'm missing something. I post this here as a Topshelf issue because this is surely something related to it, as the only difference is running the app as console or as installed Win service.

**Comment by phatboyg** [comment]
Probably not Topshelf.

**Comment by CesarD** [comment]
Hi, sorry for not closing this up earlier as I found the cause, but in the meantime I completely forgot I opened this one.

There seems to be some constraint on the Windows Services that when you configure any logging to a file, you have to be very explicit about the logfile path and indicate the full path, and not just a relative one. I eventually found out that was the reason and as soon as I configured the full path for the logfile, it worked just fine. The same happens when developing the new Worker Processes from .NET Core and running them as Win Service.

Cheers.
