### ISSUE TITLE
Reengineer Shelving as a v3.x Feature over Topshelf

### ISSUE THREAD

**Issue by drusellers** [Topshelf/Topshelf#59]
Since v3 removed support for shelving (and greatly simplified the internal behavior), consider creating a service (using Topshelf, of course) that has the ability to identify and monitor services in a folder below them. Each 'shelved' service would run as a separate service in the SCM for monitoring and isolation reasons, but the main Topshelf "service manager" would make sure that services were registered and running.

This would be done in a way that leaves the base Topshelf service alone, simple, and unencumbered.

**Comment by TravisTheTechie** [comment]
This conversation is stale and there's no one who is currently interested in owning this work moving forward. Closing.
