### ISSUE TITLE
cannot assign void to implicitly-typed local variable

### ISSUE THREAD

**Issue by varkalasrikanth** [Topshelf/Topshelf#590]
I am trying to use topshelf for triggering an ever for every 180 mins using timer.(C# console application.). I am using Topshelf 3.0 However I am getting following  error

Error: cannot assign void to implicitly-typed local variable
for the code:
 var Startprocessing  = HostFactory.Run(x =>
            {
                x.Service<InsertFeed>(K =>
                {
                    K.ConstructUsing(InsertFeed => new InsertFeed());
                    K.WhenStarted(InsertFeed => InsertFeed.Start());
                    K.WhenStopped(InsertFeed => InsertFeed.Stop());
                });
                x.RunAsLocalSystem();
                x.SetServiceName("Sercantofeed");
                x.SetDisplayName("Sercanto Jobs feed");
                x.SetDescription("This service will process Sercanto Jobs feed and Insert them into the database");
            });

**Comment by phatboyg** [comment]
This is something in your configuration, not Topshelf.
