### ISSUE TITLE
TopShelf, .net core & Microsoft.Extensions.Hosting.WindowsServices extension

### ISSUE THREAD

**Issue by chrisdot** [Topshelf/Topshelf#591]
Hello,
With the new version of .net core 5 (but introduced in v3.x I think), we get a new [BackgroundService](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-5.0&tabs=visual-studio) class to make it easy to write services/daemons. And with the Microsoft.Extensions.Hosting.WindowsServices package, we can now even add the service entry points faster, with the simple `.UseWindowsService()` extension.
BUT we don't get the same cool features which I loved with TopShelf, which is the self-installable capability (without having to use SC.exe nor other power shell stuff).

Is there any plan to adapt TopShelf to that case?

Thanks,
Christophe

**Comment by phatboyg** [comment]
There are no plans. Now that .NET has caught up (The generic host in 3.1 was more than enough honestly) there will unlikely be any major updates to Topshelf.
