### ISSUE TITLE
role of  TopShelf.ServiceInstaller project

### ISSUE THREAD

**Issue by chrisdot** [Topshelf/Topshelf#592]
Hello,

I would like to get the same features as TopShelf with .net core's generic host (this means the auto installation features). As [there are no plans](https://github.com/Topshelf/Topshelf/issues/591) for any TopShelf evolution regarding that, I was curious to understand how TopShelf does that in .net core/standard.

I briefly tried to understand the code, and saw the [TopShelf.ServiceInstaller project](https://github.com/Topshelf/Topshelf/tree/develop/src/TopShelf.ServiceInstaller). It is targetting .netstandard2. Is this a kind of shim for the missing installation stuff that is present in the .NET4.8 version ? Is that taken from the .net 4.8 implementation?

Thanks
Christophe

**Comment by phatboyg** [comment]
It only works on Windows, with .NET Standard projects.
