### ISSUE TITLE
Issue with Nuget package for version 4.3.0

### ISSUE THREAD

**Issue by jscarle** [Topshelf/Topshelf#595]
If I update my services to use the Nuget package 4.3.0, the services will no longer start.

CoreCLR Version: 5.0.321.7212
.NET Version: 5.0.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException: 
File name: 'Topshelf, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b800c4cfcdeea87b'

If I revert to the Nuget package version 4.2.1, without any code changes, then my services start.

**Comment by phatboyg** [comment]
So don't update? Topshelf is in limited support at this point. If you're using .NET 5, seriously, use the Generic Host included with .NET.
