### ISSUE TITLE
.NET Standard 2.0

### ISSUE THREAD

**Issue by madmonkey** [Topshelf/Topshelf#596]
Just wanted to verify - I've an SDK style project (netstandard2.0) - I include the nuget reference but when I run I get the exception cannont load TopShelf version(x.x) - no matter which package > 4.1 I try. Is this compatible with Net Standard?

Thanks in advance.

Project file:

```
`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Topshelf" Version="4.1.0" />
  </ItemGroup>

</Project>
```
`

**Comment by phatboyg** [comment]
The latest version, https://www.nuget.org/packages/Topshelf/4.3.0, is compatible with netstandard2.0. You can see the dependencies at that link.

**Comment by madmonkey** [comment]
If I just create a 4.72 project - I can run as normal. I'll see if I can get away with this for this project. Thanks
