### ISSUE TITLE
Add support for pre-shutdown-notification

### ISSUE THREAD

**Issue by Brunni** [Topshelf/Topshelf#599]
I would like to handle a pre-shutdown-notification, to detect, when a shutdown is schedueld, so that I have more time finishing / cleaning up the service before the actual shutdown happens.

Is it possible to do this with Topshelf?

https://www.sivachandran.in/2012/03/handling-pre-shutdown-notification-in-c.html

**Comment by jackmang** [comment]
FYI:  See issues #371 and #571 where this question is discussed. I think that the repo owner has essentially deprecated this library with the introduction of .net core and the end of development of the classic framework.
