### ISSUE TITLE
Windows PreShutdown event?

### ISSUE THREAD

**Issue by toddkc** [Topshelf/Topshelf#608]
I use Topshelf for a service that also uses SQL Server.  On computer shutdown/restart pretty much all of the time SQL Server is stopped before my service gets any sort of notification.  I've tried leveraging EnableShutdown/WhenShutdown, WhenStopped, DependsOnMsSql, and even WhenCustomCommandReceived.  Nothing is helping me to ensure my service stops before SQL server is stopped.  I've tried adding in a preshutdown event listener with no success.  Any tips?

**Comment by phatboyg** [comment]
Topshelf is no longer supported.
