### ISSUE TITLE
Granted Account Rights Not Removed During Uninstall

### ISSUE THREAD

**Issue by SoftwareGuyRob** [Topshelf/Topshelf#610]
Inside the [ServiceProcessInstaller](https://github.com/Topshelf/Topshelf/blob/03bde8963da8c057ffc6df07ef9600ffdf6047c1/src/TopShelf.ServiceInstaller/System.ServiceProcess/ServiceProcessInstaller.cs#L316) we GrantAccountRight to grant "SeServiceLogonRight", allowing the user the ability to logon as a service...but I don't see an equivalent line of code to remove it (except during a rollback).

The issue is that, after installing/uninstalling a service, the granted permissions remain.

Local Security Policy / Security Settings / Local Policies / User Rights Assignment / Log on as a service

Is this by design, or a defect?

**Comment by phatboyg** [comment]
Topshelf is no longer supported.
