### ISSUE TITLE
Allow configuration of command line parameters when installing a service

### ISSUE THREAD

**Issue by jonnii** [Topshelf/Topshelf#74]
My application expects a few (optional) command line parameters to be passed into the service when it is started and It'd be great if I could configure these through topshelf when the service is installing. When doing this manually I can set the Start parameters textbox in the service configuration window, but there doesn't seem to be a corresponding method in topshelf.

I'm currently trying to hack this together by getting it to pass through the service name, but so far this isn't working ... =(

**Comment by dragon788** [comment]
This is an old issue but according to the documentation when passing a quoted string you do NOT supply the colon between the -displayname the quoted string.

**Comment by sm-g** [comment]
@phatboyg What about this issue? [HostserviceInstaller adds](https://github.com/Topshelf/Topshelf/blob/develop/src/Topshelf/Runtime/Windows/HostServiceInstaller.cs#L132) some set of arguments, but to add custom args (i.e. value to be used as Environment value - staging/production) we need to [edit registry manually in AfterInstall](https://stackoverflow.com/a/36044058/3009578)
