### ISSUE TITLE
Service not showing in services.msc list

### ISSUE THREAD

**Issue by madhukarjha** [Topshelf/Topshelf#98]
I have created a console application and tried to host it using TOPSHELF. Its working fine from command prompt but when trying  to install it, it is not getting visible in Services.msc list. Need help.

Thnaks & Regards,
Madhukar Jha

**Comment by Serexx** [comment]
An old thread but it still happens so : In my case I opened a Command window from VS 2017 which I had launched as admin, but that didn't work - the console needs to be opened explicitly as Administrator.
